#ifndef SWIFT_GNUSTEP_COMPAT_TARGETCONDITIONALS_H
#define SWIFT_GNUSTEP_COMPAT_TARGETCONDITIONALS_H

#define TARGET_OS_MAC 0
#define TARGET_OS_IPHONE 0
#define TARGET_OS_IOS 0
#define TARGET_OS_TV 0
#define TARGET_OS_WATCH 0
#define TARGET_OS_SIMULATOR 0

#endif
