
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierTitle: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierCreator: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierSubject: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierDescription: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierPublisher: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierContributor: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierCreationDate: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierLastModifiedDate: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierType: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierFormat: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierAssetIdentifier: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierSource: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierLanguage: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierRelation: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierLocation: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierCopyrights: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierAlbumName: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierAuthor: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierArtist: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierArtwork: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierMake: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierModel: String
@available(iOS 8.0, *)
let AVMetadataCommonIdentifierSoftware: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataAlbum: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataArranger: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataAuthor: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataChapter: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataComment: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataComposer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataCreationDate: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataDirector: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataDisclaimer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataEncodedBy: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataFullName: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataGenre: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataHostComputer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataInformation: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataKeywords: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataMake: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataModel: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataOriginalArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataOriginalFormat: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataOriginalSource: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataPerformers: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataProducer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataPublisher: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataProduct: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataSoftware: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataSpecialPlaybackRequirements: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataTrack: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataWarning: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataWriter: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataURLLink: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataLocationISO6709: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataTrackName: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataCredits: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataPhonogramRights: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeUserDataTaggedCharacteristic: String
@available(iOS 8.0, *)
let AVMetadataIdentifierISOUserDataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifierISOUserDataTaggedCharacteristic: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataAuthor: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataPerformer: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataGenre: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataRecordingYear: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataLocation: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataCollection: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataUserRating: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataThumbnail: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataAlbumAndTrack: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataKeywordList: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataMediaClassification: String
@available(iOS 8.0, *)
let AVMetadataIdentifier3GPUserDataMediaRating: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataAuthor: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataComment: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCreationDate: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataDirector: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataDisplayName: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataInformation: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataKeywords: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataProducer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataPublisher: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataAlbum: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataArtwork: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataSoftware: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataYear: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataGenre: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataiXML: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationISO6709: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataMake: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataModel: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataArranger: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataEncodedBy: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataOriginalArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataPerformer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataComposer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCredits: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataPhonogramRights: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCameraIdentifier: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataCollectionUser: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataRatingUser: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationName: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationBody: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationNote: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationRole: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataLocationDate: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataDirectionFacing: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataDirectionMotion: String
@available(iOS 8.0, *)
let AVMetadataIdentifierQuickTimeMetadataPreferredAffineTransform: String
@available(iOS 9.0, *)
let AVMetadataIdentifierQuickTimeMetadataDetectedFace: String
@available(iOS 9.0, *)
let AVMetadataIdentifierQuickTimeMetadataVideoOrientation: String
@available(iOS 9.0, *)
let AVMetadataIdentifierQuickTimeMetadataContentIdentifier: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAlbum: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataUserComment: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataCoverArt: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataReleaseDate: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataEncodedBy: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataPredefinedGenre: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataUserGenre: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataSongName: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataTrackSubTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataEncodingTool: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataComposer: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAlbumArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAccountKind: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAppleID: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataArtistID: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataSongID: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataDiscCompilation: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataDiscNumber: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataGenreID: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataGrouping: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataPlaylistID: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataContentRating: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataBeatsPerMin: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataTrackNumber: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataArtDirector: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataArranger: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAuthor: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataLyrics: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataAcknowledgement: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataConductor: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataDirector: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataEQ: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataLinerNotes: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataRecordCompany: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataOriginalArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataPhonogramRights: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataProducer: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataPerformer: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataPublisher: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataSoundEngineer: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataSoloist: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataCredits: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataThanks: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataOnlineExtras: String
@available(iOS 8.0, *)
let AVMetadataIdentifieriTunesMetadataExecProducer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataAudioEncryption: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataAttachedPicture: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataAudioSeekPointIndex: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataComments: String
@available(iOS 9.0, *)
let AVMetadataIdentifierID3MetadataCommercial: String
@available(iOS, introduced: 8.0, deprecated: 9.0)
let AVMetadataIdentifierID3MetadataCommerical: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEncryption: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEqualization: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEqualization2: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEventTimingCodes: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataGeneralEncapsulatedObject: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataGroupIdentifier: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInvolvedPeopleList_v23: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataLink: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataMusicCDIdentifier: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataMPEGLocationLookupTable: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOwnership: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPrivate: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPlayCounter: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPopularimeter: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPositionSynchronization: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataRecommendedBufferSize: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment2: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataReverb: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSeek: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSignature: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSynchronizedLyric: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSynchronizedTempoCodes: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataAlbumTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataBeatsPerMinute: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataComposer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataContentType: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataCopyright: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataDate: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEncodingTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPlaylistDelay: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalReleaseTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataRecordingTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataReleaseTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTaggingTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEncodedBy: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataLyricist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataFileType: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTime: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInvolvedPeopleList_v24: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataContentGroupDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTitleDescription: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSubTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInitialKey: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataLanguage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataLength: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataMusicianCreditsList: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataMediaType: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataMood: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalAlbumTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalFilename: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalLyricist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalArtist: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOriginalReleaseYear: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataFileOwner: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataLeadPerformer: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataBand: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataConductor: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataModifiedBy: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPartOfASet: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataProducedNotice: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPublisher: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTrackNumber: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataRecordingDates: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInternetRadioStationName: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInternetRadioStationOwner: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSize: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataAlbumSortOrder: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPerformerSortOrder: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTitleSortOrder: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataInternationalStandardRecordingCode: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataEncodedWith: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataSetSubtitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataYear: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataUserText: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataUniqueFileIdentifier: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataTermsOfUse: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataUnsynchronizedLyric: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataCommercialInformation: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataCopyrightInformation: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOfficialAudioFileWebpage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOfficialArtistWebpage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOfficialAudioSourceWebpage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOfficialInternetRadioStationHomepage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataPayment: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataOfficialPublisherWebpage: String
@available(iOS 8.0, *)
let AVMetadataIdentifierID3MetadataUserURL: String
@available(iOS 8.0, *)
let AVMetadataIdentifierIcyMetadataStreamTitle: String
@available(iOS 8.0, *)
let AVMetadataIdentifierIcyMetadataStreamURL: String
