
@available(iOS 4.0, *)
let AVMetadataKeySpaceCommon: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyTitle: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyCreator: String
@available(iOS 4.0, *)
let AVMetadataCommonKeySubject: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyDescription: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyPublisher: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyContributor: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyCreationDate: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyLastModifiedDate: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyType: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyFormat: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyIdentifier: String
@available(iOS 4.0, *)
let AVMetadataCommonKeySource: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyLanguage: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyRelation: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyLocation: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyCopyrights: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyAlbumName: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyAuthor: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyArtist: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyArtwork: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyMake: String
@available(iOS 4.0, *)
let AVMetadataCommonKeyModel: String
@available(iOS 4.0, *)
let AVMetadataCommonKeySoftware: String
@available(iOS 4.0, *)
let AVMetadataFormatQuickTimeUserData: String
@available(iOS 4.0, *)
let AVMetadataKeySpaceQuickTimeUserData: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyAlbum: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyArranger: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyArtist: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyAuthor: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyChapter: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyComment: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyComposer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyCopyright: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyCreationDate: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyDescription: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyDirector: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyDisclaimer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyEncodedBy: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyFullName: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyGenre: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyHostComputer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyInformation: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyKeywords: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyMake: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyModel: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyOriginalArtist: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyOriginalFormat: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyOriginalSource: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyPerformers: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyProducer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyPublisher: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyProduct: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeySoftware: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeySpecialPlaybackRequirements: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyTrack: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyWarning: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyWriter: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyURLLink: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyLocationISO6709: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyTrackName: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyCredits: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeUserDataKeyPhonogramRights: String
@available(iOS 5.0, *)
let AVMetadataQuickTimeUserDataKeyTaggedCharacteristic: String
@available(iOS 7.0, *)
let AVMetadataFormatISOUserData: String
@available(iOS 7.0, *)
let AVMetadataKeySpaceISOUserData: String
@available(iOS 4.0, *)
let AVMetadataISOUserDataKeyCopyright: String
@available(iOS 8.0, *)
let AVMetadataISOUserDataKeyTaggedCharacteristic: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyCopyright: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyAuthor: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyPerformer: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyGenre: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyRecordingYear: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyLocation: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyTitle: String
@available(iOS 4.0, *)
let AVMetadata3GPUserDataKeyDescription: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyCollection: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyUserRating: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyThumbnail: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyAlbumAndTrack: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyKeywordList: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyMediaClassification: String
@available(iOS 7.0, *)
let AVMetadata3GPUserDataKeyMediaRating: String
@available(iOS 4.0, *)
let AVMetadataFormatQuickTimeMetadata: String
@available(iOS 4.0, *)
let AVMetadataKeySpaceQuickTimeMetadata: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyAuthor: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyComment: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyCopyright: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyCreationDate: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyDirector: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyDisplayName: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyInformation: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyKeywords: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyProducer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyPublisher: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyAlbum: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyArtist: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyArtwork: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyDescription: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeySoftware: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyYear: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyGenre: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyiXML: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyLocationISO6709: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyMake: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyModel: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyArranger: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyEncodedBy: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyOriginalArtist: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyPerformer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyComposer: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyCredits: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyPhonogramRights: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyCameraIdentifier: String
@available(iOS 4.0, *)
let AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyTitle: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyCollectionUser: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyRatingUser: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyLocationName: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyLocationBody: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyLocationNote: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyLocationRole: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyLocationDate: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyDirectionFacing: String
@available(iOS 4.3, *)
let AVMetadataQuickTimeMetadataKeyDirectionMotion: String
@available(iOS 9.0, *)
let AVMetadataQuickTimeMetadataKeyContentIdentifier: String
@available(iOS 4.0, *)
let AVMetadataFormatiTunesMetadata: String
@available(iOS 4.0, *)
let AVMetadataKeySpaceiTunes: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAlbum: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyArtist: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyUserComment: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyCoverArt: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyCopyright: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyReleaseDate: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyEncodedBy: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyPredefinedGenre: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyUserGenre: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeySongName: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyTrackSubTitle: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyEncodingTool: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyComposer: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAlbumArtist: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAccountKind: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAppleID: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyArtistID: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeySongID: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyDiscCompilation: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyDiscNumber: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyGenreID: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyGrouping: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyPlaylistID: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyContentRating: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyBeatsPerMin: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyTrackNumber: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyArtDirector: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyArranger: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAuthor: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyLyrics: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyAcknowledgement: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyConductor: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyDescription: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyDirector: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyEQ: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyLinerNotes: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyRecordCompany: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyOriginalArtist: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyPhonogramRights: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyProducer: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyPerformer: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyPublisher: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeySoundEngineer: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeySoloist: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyCredits: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyThanks: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyOnlineExtras: String
@available(iOS 4.0, *)
let AVMetadataiTunesMetadataKeyExecProducer: String
@available(iOS 4.0, *)
let AVMetadataFormatID3Metadata: String
@available(iOS 4.0, *)
let AVMetadataKeySpaceID3: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyAudioEncryption: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyAttachedPicture: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyAudioSeekPointIndex: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyComments: String
@available(iOS 9.0, *)
let AVMetadataID3MetadataKeyCommercial: String
@available(iOS, introduced: 4.0, deprecated: 9.0)
let AVMetadataID3MetadataKeyCommerical: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEncryption: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEqualization: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEqualization2: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEventTimingCodes: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyGeneralEncapsulatedObject: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyGroupIdentifier: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInvolvedPeopleList_v23: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyLink: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyMusicCDIdentifier: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyMPEGLocationLookupTable: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOwnership: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPrivate: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPlayCounter: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPopularimeter: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPositionSynchronization: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyRecommendedBufferSize: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyRelativeVolumeAdjustment: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyRelativeVolumeAdjustment2: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyReverb: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySeek: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySignature: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySynchronizedLyric: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySynchronizedTempoCodes: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyAlbumTitle: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyBeatsPerMinute: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyComposer: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyContentType: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyCopyright: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyDate: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEncodingTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPlaylistDelay: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalReleaseTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyRecordingTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyReleaseTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTaggingTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEncodedBy: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyLyricist: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyFileType: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTime: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInvolvedPeopleList_v24: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyContentGroupDescription: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTitleDescription: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySubTitle: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInitialKey: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyLanguage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyLength: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyMusicianCreditsList: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyMediaType: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyMood: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalAlbumTitle: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalFilename: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalLyricist: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalArtist: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOriginalReleaseYear: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyFileOwner: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyLeadPerformer: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyBand: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyConductor: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyModifiedBy: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPartOfASet: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyProducedNotice: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPublisher: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTrackNumber: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyRecordingDates: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInternetRadioStationName: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInternetRadioStationOwner: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySize: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyAlbumSortOrder: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPerformerSortOrder: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTitleSortOrder: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyInternationalStandardRecordingCode: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyEncodedWith: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeySetSubtitle: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyYear: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyUserText: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyUniqueFileIdentifier: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyTermsOfUse: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyUnsynchronizedLyric: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyCommercialInformation: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyCopyrightInformation: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOfficialAudioFileWebpage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOfficialArtistWebpage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOfficialAudioSourceWebpage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOfficialInternetRadioStationHomepage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyPayment: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyOfficialPublisherWebpage: String
@available(iOS 4.0, *)
let AVMetadataID3MetadataKeyUserURL: String
@available(iOS 8.0, *)
let AVMetadataKeySpaceIcy: String
@available(iOS 8.0, *)
let AVMetadataIcyMetadataKeyStreamTitle: String
@available(iOS 8.0, *)
let AVMetadataIcyMetadataKeyStreamURL: String
@available(iOS 8.0, *)
let AVMetadataFormatHLSMetadata: String
@available(iOS 9.3, *)
let AVMetadataKeySpaceHLSDateRange: String
@available(iOS 8.0, *)
let AVMetadataExtraAttributeValueURIKey: String
@available(iOS 8.0, *)
let AVMetadataExtraAttributeBaseURIKey: String
@available(iOS 9.0, *)
let AVMetadataExtraAttributeInfoKey: String
