
@available(iOS 4.0, *)
let AVMediaTypeVideo: String
@available(iOS 4.0, *)
let AVMediaTypeAudio: String
@available(iOS 4.0, *)
let AVMediaTypeText: String
@available(iOS 4.0, *)
let AVMediaTypeClosedCaption: String
@available(iOS 4.0, *)
let AVMediaTypeSubtitle: String
@available(iOS 4.0, *)
let AVMediaTypeTimecode: String
@available(iOS 6.0, *)
let AVMediaTypeMetadata: String
@available(iOS 4.0, *)
let AVMediaTypeMuxed: String
@available(iOS 9.0, *)
let AVMediaTypeMetadataObject: String
@available(iOS 4.0, *)
let AVMediaCharacteristicVisual: String
@available(iOS 4.0, *)
let AVMediaCharacteristicAudible: String
@available(iOS 4.0, *)
let AVMediaCharacteristicLegible: String
@available(iOS 4.0, *)
let AVMediaCharacteristicFrameBased: String
@available(iOS 5.0, *)
let AVMediaCharacteristicIsMainProgramContent: String
@available(iOS 5.0, *)
let AVMediaCharacteristicIsAuxiliaryContent: String
@available(iOS 5.0, *)
let AVMediaCharacteristicContainsOnlyForcedSubtitles: String
@available(iOS 5.0, *)
let AVMediaCharacteristicTranscribesSpokenDialogForAccessibility: String
@available(iOS 5.0, *)
let AVMediaCharacteristicDescribesMusicAndSoundForAccessibility: String
@available(iOS 6.0, *)
let AVMediaCharacteristicEasyToRead: String
@available(iOS 5.0, *)
let AVMediaCharacteristicDescribesVideoForAccessibility: String
@available(iOS 9.0, *)
let AVMediaCharacteristicLanguageTranslation: String
@available(iOS 9.0, *)
let AVMediaCharacteristicDubbedTranslation: String
@available(iOS 9.0, *)
let AVMediaCharacteristicVoiceOverTranslation: String
@available(iOS 4.0, *)
let AVFileTypeQuickTimeMovie: String
@available(iOS 4.0, *)
let AVFileTypeMPEG4: String
@available(iOS 4.0, *)
let AVFileTypeAppleM4V: String
@available(iOS 4.0, *)
let AVFileTypeAppleM4A: String
@available(iOS 4.0, *)
let AVFileType3GPP: String
@available(iOS 4.0, *)
let AVFileType3GPP2: String
@available(iOS 4.0, *)
let AVFileTypeCoreAudioFormat: String
@available(iOS 4.0, *)
let AVFileTypeWAVE: String
@available(iOS 4.0, *)
let AVFileTypeAIFF: String
@available(iOS 4.0, *)
let AVFileTypeAIFC: String
@available(iOS 4.0, *)
let AVFileTypeAMR: String
@available(iOS 7.0, *)
let AVFileTypeMPEGLayer3: String
@available(iOS 7.0, *)
let AVFileTypeSunAU: String
@available(iOS 7.0, *)
let AVFileTypeAC3: String
@available(iOS 9.0, *)
let AVFileTypeEnhancedAC3: String
@available(iOS 9.0, *)
let AVStreamingKeyDeliveryContentKeyType: String
@available(iOS 9.0, *)
let AVStreamingKeyDeliveryPersistentContentKeyType: String
