
SWIFT = $(wildcard /Users/sabre/Library/Developer/Xcode/DerivedData/*/Build/Products/Debug/Swift)
#SWIFT = swift

test:
	$(SWIFT) data.swift
	$(SWIFT) name-binding.swift
	$(SWIFT) expr-stmt.swift
#	$(SWIFT) arrays.swift

clean:
	@#
