
var VMCS_VPID: Int { get }
var VMCS_CTRL_POSTED_INT_N_VECTOR: Int { get }
var VMCS_CTRL_EPTP_INDEX: Int { get }
var VMCS_GUEST_ES: Int { get }
var VMCS_GUEST_CS: Int { get }
var VMCS_GUEST_SS: Int { get }
var VMCS_GUEST_DS: Int { get }
var VMCS_GUEST_FS: Int { get }
var VMCS_GUEST_GS: Int { get }
var VMCS_GUEST_LDTR: Int { get }
var VMCS_GUEST_TR: Int { get }
var VMCS_GUEST_INT_STATUS: Int { get }
var VMCS_HOST_ES: Int { get }
var VMCS_HOST_CS: Int { get }
var VMCS_HOST_SS: Int { get }
var VMCS_HOST_DS: Int { get }
var VMCS_HOST_FS: Int { get }
var VMCS_HOST_GS: Int { get }
var VMCS_HOST_TR: Int { get }
var VMCS_CTRL_IO_BITMAP_A: Int { get }
var VMCS_CTRL_IO_BITMAP_B: Int { get }
var VMCS_CTRL_MSR_BITMAPS: Int { get }
var VMCS_CTRL_VMEXIT_MSR_STORE_ADDR: Int { get }
var VMCS_CTRL_VMEXIT_MSR_LOAD_ADDR: Int { get }
var VMCS_CTRL_VMENTRY_MSR_LOAD_ADDR: Int { get }
var VMCS_CTRL_EXECUTIVE_VMCS_PTR: Int { get }
var VMCS_CTRL_TSC_OFFSET: Int { get }
var VMCS_CTRL_VIRTUAL_APIC: Int { get }
var VMCS_CTRL_APIC_ACCESS: Int { get }
var VMCS_CTRL_POSTED_INT_DESC_ADDR: Int { get }
var VMCS_CTRL_VMFUNC_CTRL: Int { get }
var VMCS_CTRL_EPTP: Int { get }
var VMCS_CTRL_EOI_EXIT_BITMAP_0: Int { get }
var VMCS_CTRL_EOI_EXIT_BITMAP_1: Int { get }
var VMCS_CTRL_EOI_EXIT_BITMAP_2: Int { get }
var VMCS_CTRL_EOI_EXIT_BITMAP_3: Int { get }
var VMCS_CTRL_EPTP_LIST_ADDR: Int { get }
var VMCS_CTRL_VMREAD_BITMAP_ADDR: Int { get }
var VMCS_CTRL_VMWRITE_BITMAP_ADDR: Int { get }
var VMCS_CTRL_VIRT_EXC_INFO_ADDR: Int { get }
var VMCS_CTRL_XSS_EXITING_BITMAP: Int { get }
var VMCS_GUEST_PHYSICAL_ADDRESS: Int { get }
var VMCS_GUEST_LINK_POINTER: Int { get }
var VMCS_GUEST_IA32_DEBUGCTL: Int { get }
var VMCS_GUEST_IA32_PAT: Int { get }
var VMCS_GUEST_IA32_EFER: Int { get }
var VMCS_GUEST_IA32_PERF_GLOBAL_CTRL: Int { get }
var VMCS_GUEST_PDPTE0: Int { get }
var VMCS_GUEST_PDPTE1: Int { get }
var VMCS_GUEST_PDPTE2: Int { get }
var VMCS_GUEST_PDPTE3: Int { get }
var VMCS_HOST_IA32_PAT: Int { get }
var VMCS_HOST_IA32_EFER: Int { get }
var VMCS_HOST_IA32_PERF_GLOBAL_CTRL: Int { get }
var VMCS_CTRL_PIN_BASED: Int { get }
var VMCS_CTRL_CPU_BASED: Int { get }
var VMCS_CTRL_EXC_BITMAP: Int { get }
var VMCS_CTRL_PF_ERROR_MASK: Int { get }
var VMCS_CTRL_PF_ERROR_MATCH: Int { get }
var VMCS_CTRL_CR3_COUNT: Int { get }
var VMCS_CTRL_VMEXIT_CONTROLS: Int { get }
var VMCS_CTRL_VMEXIT_MSR_STORE_COUNT: Int { get }
var VMCS_CTRL_VMEXIT_MSR_LOAD_COUNT: Int { get }
var VMCS_CTRL_VMENTRY_CONTROLS: Int { get }
var VMCS_CTRL_VMENTRY_MSR_LOAD_COUNT: Int { get }
var VMCS_CTRL_VMENTRY_IRQ_INFO: Int { get }
var VMCS_CTRL_VMENTRY_EXC_ERROR: Int { get }
var VMCS_CTRL_VMENTRY_INSTR_LEN: Int { get }
var VMCS_CTRL_TPR_THRESHOLD: Int { get }
var VMCS_CTRL_CPU_BASED2: Int { get }
var VMCS_CTRL_PLE_GAP: Int { get }
var VMCS_CTRL_PLE_WINDOW: Int { get }
var VMCS_RO_INSTR_ERROR: Int { get }
var VMCS_RO_EXIT_REASON: Int { get }
var VMCS_RO_VMEXIT_IRQ_INFO: Int { get }
var VMCS_RO_VMEXIT_IRQ_ERROR: Int { get }
var VMCS_RO_IDT_VECTOR_INFO: Int { get }
var VMCS_RO_IDT_VECTOR_ERROR: Int { get }
var VMCS_RO_VMEXIT_INSTR_LEN: Int { get }
var VMCS_RO_VMX_INSTR_INFO: Int { get }
var VMCS_GUEST_ES_LIMIT: Int { get }
var VMCS_GUEST_CS_LIMIT: Int { get }
var VMCS_GUEST_SS_LIMIT: Int { get }
var VMCS_GUEST_DS_LIMIT: Int { get }
var VMCS_GUEST_FS_LIMIT: Int { get }
var VMCS_GUEST_GS_LIMIT: Int { get }
var VMCS_GUEST_LDTR_LIMIT: Int { get }
var VMCS_GUEST_TR_LIMIT: Int { get }
var VMCS_GUEST_GDTR_LIMIT: Int { get }
var VMCS_GUEST_IDTR_LIMIT: Int { get }
var VMCS_GUEST_ES_AR: Int { get }
var VMCS_GUEST_CS_AR: Int { get }
var VMCS_GUEST_SS_AR: Int { get }
var VMCS_GUEST_DS_AR: Int { get }
var VMCS_GUEST_FS_AR: Int { get }
var VMCS_GUEST_GS_AR: Int { get }
var VMCS_GUEST_LDTR_AR: Int { get }
var VMCS_GUEST_TR_AR: Int { get }
var VMCS_GUEST_IGNORE_IRQ: Int { get }
var VMCS_GUEST_ACTIVITY_STATE: Int { get }
var VMCS_GUEST_SMBASE: Int { get }
var VMCS_GUEST_IA32_SYSENTER_CS: Int { get }
var VMCS_GUEST_VMX_TIMER_VALUE: Int { get }
var VMCS_HOST_IA32_SYSENTER_CS: Int { get }
var VMCS_CTRL_CR0_MASK: Int { get }
var VMCS_CTRL_CR4_MASK: Int { get }
var VMCS_CTRL_CR0_SHADOW: Int { get }
var VMCS_CTRL_CR4_SHADOW: Int { get }
var VMCS_CTRL_CR3_VALUE0: Int { get }
var VMCS_CTRL_CR3_VALUE1: Int { get }
var VMCS_CTRL_CR3_VALUE2: Int { get }
var VMCS_CTRL_CR3_VALUE3: Int { get }
var VMCS_RO_EXIT_QUALIFIC: Int { get }
var VMCS_RO_IO_RCX: Int { get }
var VMCS_RO_IO_RSI: Int { get }
var VMCS_RO_IO_RDI: Int { get }
var VMCS_RO_IO_RIP: Int { get }
var VMCS_RO_GUEST_LIN_ADDR: Int { get }
var VMCS_GUEST_CR0: Int { get }
var VMCS_GUEST_CR3: Int { get }
var VMCS_GUEST_CR4: Int { get }
var VMCS_GUEST_ES_BASE: Int { get }
var VMCS_GUEST_CS_BASE: Int { get }
var VMCS_GUEST_SS_BASE: Int { get }
var VMCS_GUEST_DS_BASE: Int { get }
var VMCS_GUEST_FS_BASE: Int { get }
var VMCS_GUEST_GS_BASE: Int { get }
var VMCS_GUEST_LDTR_BASE: Int { get }
var VMCS_GUEST_TR_BASE: Int { get }
var VMCS_GUEST_GDTR_BASE: Int { get }
var VMCS_GUEST_IDTR_BASE: Int { get }
var VMCS_GUEST_DR7: Int { get }
var VMCS_GUEST_RSP: Int { get }
var VMCS_GUEST_RIP: Int { get }
var VMCS_GUEST_RFLAGS: Int { get }
var VMCS_GUEST_DEBUG_EXC: Int { get }
var VMCS_GUEST_SYSENTER_ESP: Int { get }
var VMCS_GUEST_SYSENTER_EIP: Int { get }
var VMCS_HOST_CR0: Int { get }
var VMCS_HOST_CR3: Int { get }
var VMCS_HOST_CR4: Int { get }
var VMCS_HOST_FS_BASE: Int { get }
var VMCS_HOST_GS_BASE: Int { get }
var VMCS_HOST_TR_BASE: Int { get }
var VMCS_HOST_GDTR_BASE: Int { get }
var VMCS_HOST_IDTR_BASE: Int { get }
var VMCS_HOST_IA32_SYSENTER_ESP: Int { get }
var VMCS_HOST_IA32_SYSENTER_EIP: Int { get }
var VMCS_HOST_RSP: Int { get }
var VMCS_HOST_RIP: Int { get }
var VMCS_MAX: Int { get }
var VMX_BASIC_TRUE_CTLS: UInt { get }
var PIN_BASED_INTR: UInt32 { get }
var PIN_BASED_NMI: UInt32 { get }
var PIN_BASED_VIRTUAL_NMI: UInt32 { get }
var PIN_BASED_PREEMPTION_TIMER: UInt32 { get }
var PIN_BASED_POSTED_INTR: UInt32 { get }
var CPU_BASED_IRQ_WND: UInt32 { get }
var CPU_BASED_TSC_OFFSET: UInt32 { get }
var CPU_BASED_HLT: UInt32 { get }
var CPU_BASED_INVLPG: UInt32 { get }
var CPU_BASED_MWAIT: UInt32 { get }
var CPU_BASED_RDPMC: UInt32 { get }
var CPU_BASED_RDTSC: UInt32 { get }
var CPU_BASED_CR3_LOAD: UInt32 { get }
var CPU_BASED_CR3_STORE: UInt32 { get }
var CPU_BASED_CR8_LOAD: UInt32 { get }
var CPU_BASED_CR8_STORE: UInt32 { get }
var CPU_BASED_TPR_SHADOW: UInt32 { get }
var CPU_BASED_VIRTUAL_NMI_WND: UInt32 { get }
var CPU_BASED_MOV_DR: UInt32 { get }
var CPU_BASED_UNCOND_IO: UInt32 { get }
var CPU_BASED_IO_BITMAPS: UInt32 { get }
var CPU_BASED_MTF: UInt32 { get }
var CPU_BASED_MSR_BITMAPS: UInt32 { get }
var CPU_BASED_MONITOR: UInt32 { get }
var CPU_BASED_PAUSE: UInt32 { get }
var CPU_BASED_SECONDARY_CTLS: UInt32 { get }
var CPU_BASED2_VIRTUAL_APIC: UInt32 { get }
var CPU_BASED2_EPT: UInt32 { get }
var CPU_BASED2_DESC_TABLE: UInt32 { get }
var CPU_BASED2_RDTSCP: UInt32 { get }
var CPU_BASED2_X2APIC: UInt32 { get }
var CPU_BASED2_VPID: UInt32 { get }
var CPU_BASED2_WBINVD: UInt32 { get }
var CPU_BASED2_UNRESTRICTED: UInt32 { get }
var CPU_BASED2_APIC_REG_VIRT: UInt32 { get }
var CPU_BASED2_VIRT_INTR_DELIVERY: UInt32 { get }
var CPU_BASED2_PAUSE_LOOP: UInt32 { get }
var CPU_BASED2_RDRAND: UInt32 { get }
var CPU_BASED2_INVPCID: UInt32 { get }
var CPU_BASED2_VMFUNC: UInt32 { get }
var CPU_BASED2_VMCS_SHADOW: UInt32 { get }
var CPU_BASED2_RDSEED: UInt32 { get }
var CPU_BASED2_EPT_VE: UInt32 { get }
var CPU_BASED2_XSAVES_XRSTORS: UInt32 { get }
var VMX_EPT_VPID_SUPPORT_AD: UInt32 { get }
var VMX_EPT_VPID_SUPPORT_EXONLY: UInt32 { get }
var VMEXIT_SAVE_DBG_CONTROLS: UInt32 { get }
var VMEXIT_HOST_IA32E: UInt32 { get }
var VMEXIT_LOAD_IA32_PERF_GLOBAL_CTRL: UInt32 { get }
var VMEXIT_ACK_INTR: UInt32 { get }
var VMEXIT_SAVE_IA32_PAT: UInt32 { get }
var VMEXIT_LOAD_IA32_PAT: UInt32 { get }
var VMEXIT_SAVE_EFER: UInt32 { get }
var VMEXIT_LOAD_EFER: UInt32 { get }
var VMEXIT_SAVE_VMX_TIMER: UInt32 { get }
var VMENTRY_LOAD_DBG_CONTROLS: UInt32 { get }
var VMENTRY_GUEST_IA32E: UInt32 { get }
var VMENTRY_SMM: UInt32 { get }
var VMENTRY_DEACTIVATE_DUAL_MONITOR: UInt32 { get }
var VMENTRY_LOAD_IA32_PERF_GLOBAL_CTRL: UInt32 { get }
var VMENTRY_LOAD_IA32_PAT: UInt32 { get }
var VMENTRY_LOAD_EFER: UInt32 { get }
var VMX_REASON_EXC_NMI: Int { get }
var VMX_REASON_IRQ: Int { get }
var VMX_REASON_TRIPLE_FAULT: Int { get }
var VMX_REASON_INIT: Int { get }
var VMX_REASON_SIPI: Int { get }
var VMX_REASON_IO_SMI: Int { get }
var VMX_REASON_OTHER_SMI: Int { get }
var VMX_REASON_IRQ_WND: Int { get }
var VMX_REASON_VIRTUAL_NMI_WND: Int { get }
var VMX_REASON_TASK: Int { get }
var VMX_REASON_CPUID: Int { get }
var VMX_REASON_GETSEC: Int { get }
var VMX_REASON_HLT: Int { get }
var VMX_REASON_INVD: Int { get }
var VMX_REASON_INVLPG: Int { get }
var VMX_REASON_RDPMC: Int { get }
var VMX_REASON_RDTSC: Int { get }
var VMX_REASON_RSM: Int { get }
var VMX_REASON_VMCALL: Int { get }
var VMX_REASON_VMCLEAR: Int { get }
var VMX_REASON_VMLAUNCH: Int { get }
var VMX_REASON_VMPTRLD: Int { get }
var VMX_REASON_VMPTRST: Int { get }
var VMX_REASON_VMREAD: Int { get }
var VMX_REASON_VMRESUME: Int { get }
var VMX_REASON_VMWRITE: Int { get }
var VMX_REASON_VMOFF: Int { get }
var VMX_REASON_VMON: Int { get }
var VMX_REASON_MOV_CR: Int { get }
var VMX_REASON_MOV_DR: Int { get }
var VMX_REASON_IO: Int { get }
var VMX_REASON_RDMSR: Int { get }
var VMX_REASON_WRMSR: Int { get }
var VMX_REASON_VMENTRY_GUEST: Int { get }
var VMX_REASON_VMENTRY_MSR: Int { get }
var VMX_REASON_MWAIT: Int { get }
var VMX_REASON_MTF: Int { get }
var VMX_REASON_MONITOR: Int { get }
var VMX_REASON_PAUSE: Int { get }
var VMX_REASON_VMENTRY_MC: Int { get }
var VMX_REASON_TPR_THRESHOLD: Int { get }
var VMX_REASON_APIC_ACCESS: Int { get }
var VMX_REASON_VIRTUALIZED_EOI: Int { get }
var VMX_REASON_GDTR_IDTR: Int { get }
var VMX_REASON_LDTR_TR: Int { get }
var VMX_REASON_EPT_VIOLATION: Int { get }
var VMX_REASON_EPT_MISCONFIG: Int { get }
var VMX_REASON_EPT_INVEPT: Int { get }
var VMX_REASON_RDTSCP: Int { get }
var VMX_REASON_VMX_TIMER_EXPIRED: Int { get }
var VMX_REASON_INVVPID: Int { get }
var VMX_REASON_WBINVD: Int { get }
var VMX_REASON_XSETBV: Int { get }
var VMX_REASON_APIC_WRITE: Int { get }
var VMX_REASON_RDRAND: Int { get }
var VMX_REASON_INVPCID: Int { get }
var VMX_REASON_VMFUNC: Int { get }
var VMX_REASON_RDSEED: Int { get }
var VMX_REASON_XSAVES: Int { get }
var VMX_REASON_XRSTORS: Int { get }
var IRQ_INFO_EXT_IRQ: UInt32 { get }
var IRQ_INFO_NMI: UInt32 { get }
var IRQ_INFO_HARD_EXC: UInt32 { get }
var IRQ_INFO_SOFT_IRQ: UInt32 { get }
var IRQ_INFO_PRIV_SOFT_EXC: UInt32 { get }
var IRQ_INFO_SOFT_EXC: UInt32 { get }
var IRQ_INFO_ERROR_VALID: UInt32 { get }
var IRQ_INFO_VALID: UInt32 { get }
