set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(BUILD_SHARED_LIBS YES CACHE BOOL "")
set(SwiftToolchain_INSTALL_NESTED_SUBDIR OFF CACHE BOOL "")
set(SwiftToolchain_ENABLE_LIBRARY_EVOLUTION ON CACHE BOOL "")
set(SwiftToolchain_ENABLE_BACKDEPLOYMENT_SUPPORT ON CACHE BOOL "")

set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -g -DNDEBUG" CACHE STRING "")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -g -DNDEBUG" CACHE STRING "")
set(CMAKE_Swift_FLAGS_MINSIZEREL "-Osize -g" CACHE STRING "")
