set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "")
set(SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET "13.1" CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET "arm64e-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "arm64e-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Swift_COMPILER_TARGET "arm64e-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

set(SwiftToolchain_ARCH_SUBDIR arm64e CACHE STRING "")
set(SwiftToolchain_PLATFORM_SUBDIR macosx CACHE STRING "")

set(SwiftToolchain_COMPILER_VARIANT_TARGET "arm64e-apple-ios${SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET}-macabi" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
