
set(CMAKE_OSX_DEPLOYMENT_TARGET "2.0" CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET "arm64_32-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "arm64_32-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Swift_COMPILER_TARGET "arm64_32-apple-watchos${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

set(SwiftToolchain_ARCH_SUBDIR arm64_32 CACHE STRING "")
set(SwiftToolchain_PLATFORM_SUBDIR watchos CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
