
if(NOT DEFINED SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET)
  message(SEND_ERROR "SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET not defined")
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "")
set(SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET "13.1" CACHE STRING "")
set(CMAKE_C_COMPILER_TARGET "x86_64-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_CXX_COMPILER_TARGET "x86_64-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")
set(CMAKE_Swift_COMPILER_TARGET "x86_64-apple-macosx${CMAKE_OSX_DEPLOYMENT_TARGET}" CACHE STRING "")

set(SwiftToolchain_ARCH_SUBDIR x86_64 CACHE STRING "")
set(SwiftToolchain_PLATFORM_SUBDIR macosx CACHE STRING "")

set(SwiftToolchain_COMPILER_VARIANT_TARGET "x86_64-apple-ios${SwiftToolchain_TARGET_VARIANT_DEPLOYMENT_TARGET}-macabi" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/apple-common.cmake")
