#!/usr/bin/env python3
import sys
def outputname():
	for i in range(len(sys.argv)):
		if sys.argv[i] == "-o":
			return sys.argv[i + 1]
	return "a.out"
with open(outputname(), "wb") as outfile:
	pass
