#!/usr/bin/env node --disable-warning=ExperimentalWarning

const { readFile } = require('node:fs/promises');
const { WASI } = require('node:wasi');
const { argv, env } = require('node:process');

const wasmFile = argv[2];

const wasi = new WASI({
  version: 'preview1',
  args: argv.splice(2),
  env,
  preopens: {
  },
});

(async () => {
  const wasm = await WebAssembly.compile(
    await readFile(wasmFile)
  );
  const instance = await WebAssembly.instantiate(wasm, wasi.getImportObject());

  wasi.start(instance);
})();
