// REQUIRES: swift_swift_parser
// REQUIRES: swift_feature_SafeInteropImplementations

// RUN: %empty-directory(%t)
// RUN: split-file %s %t

// RUN: %target-swift-frontend %t/test.swift -emit-module -plugin-path %swift-plugin-dir -import-bridging-header %t/test.h -verify -Rmacro-expansions -enable-experimental-feature SafeInteropImplementations -disable-objc-interop -suppress-notes -verify-ignore-unrelated

//--- test.h
#define __counted_by(x) __attribute__((__counted_by__(x)))
// __counted_by without __noescape: `_SwiftifyImport` generates an
// `UnsafeBufferPointer<Int32>` overload (not `Span`). An
// `@implementation(safe)` using `UnsafeBufferPointer` should match that peer
// exactly, so no signature mismatch is diagnosed.
void bar(const int *__counted_by(len) x, int len);

//--- test.swift
// When the C function has `__counted_by` but not `__noescape`, the safe
// wrapper generated by `@_SwiftifyImport` uses `UnsafeBufferPointer<Int32>`.
// An `@implementation(safe)` with the same `UnsafeBufferPointer<CInt>`
// parameter type matches and the macro-expanded peer takes the unsafe
// `(UnsafePointer<Int32>?, Int32)` signature.
@c @implementation(safe)
public func bar(_ x: UnsafeBufferPointer<CInt>) {
// expected-expansion@+7:2{{
//   expected-remark@1{{macro content: |@c @implementation|}}
//   expected-remark@2{{macro content: |public func bar(_ x: UnsafePointer<CInt>?, _ len: CInt) {|}}
//   expected-remark@3{{macro content: |    let _ptr0 = UnsafeBufferPointer(start: x, count: Int(len))|}}
//   expected-remark@4{{macro content: |    bar(_ptr0)|}}
//   expected-remark@5{{macro content: |}|}}
// }}
}
