
@available(tvOS 7.0, *)
let CBCentralManagerOptionShowPowerAlertKey: String
@available(tvOS 7.0, *)
let CBCentralManagerOptionRestoreIdentifierKey: String
let CBCentralManagerScanOptionAllowDuplicatesKey: String
@available(tvOS 7.0, *)
let CBCentralManagerScanOptionSolicitedServiceUUIDsKey: String
@available(tvOS 6.0, *)
let CBConnectPeripheralOptionNotifyOnConnectionKey: String
let CBConnectPeripheralOptionNotifyOnDisconnectionKey: String
@available(tvOS 6.0, *)
let CBConnectPeripheralOptionNotifyOnNotificationKey: String
@available(tvOS 7.0, *)
let CBCentralManagerRestoredStatePeripheralsKey: String
@available(tvOS 7.0, *)
let CBCentralManagerRestoredStateScanServicesKey: String
@available(tvOS 7.0, *)
let CBCentralManagerRestoredStateScanOptionsKey: String
