
@available(OSX 10.7, *)
let NSMetadataItemFSNameKey: String
@available(OSX 10.7, *)
let NSMetadataItemDisplayNameKey: String
@available(OSX 10.7, *)
let NSMetadataItemURLKey: String
@available(OSX 10.7, *)
let NSMetadataItemPathKey: String
@available(OSX 10.7, *)
let NSMetadataItemFSSizeKey: String
@available(OSX 10.7, *)
let NSMetadataItemFSCreationDateKey: String
@available(OSX 10.7, *)
let NSMetadataItemFSContentChangeDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemContentTypeKey: String
@available(OSX 10.9, *)
let NSMetadataItemContentTypeTreeKey: String
@available(OSX 10.7, *)
let NSMetadataItemIsUbiquitousKey: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemHasUnresolvedConflictsKey: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemDownloadingStatusKey: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemDownloadingStatusNotDownloaded: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemDownloadingStatusDownloaded: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemDownloadingStatusCurrent: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemIsDownloadingKey: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemIsUploadedKey: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemIsUploadingKey: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemPercentDownloadedKey: String
@available(OSX 10.7, *)
let NSMetadataUbiquitousItemPercentUploadedKey: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemDownloadingErrorKey: String
@available(OSX 10.9, *)
let NSMetadataUbiquitousItemUploadingErrorKey: String
@available(OSX 10.10, *)
let NSMetadataUbiquitousItemDownloadRequestedKey: String
@available(OSX 10.10, *)
let NSMetadataUbiquitousItemIsExternalDocumentKey: String
@available(OSX 10.10, *)
let NSMetadataUbiquitousItemContainerDisplayNameKey: String
@available(OSX 10.10, *)
let NSMetadataUbiquitousItemURLInLocalContainerKey: String
@available(OSX 10.9, *)
let NSMetadataItemAttributeChangeDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemKeywordsKey: String
@available(OSX 10.9, *)
let NSMetadataItemTitleKey: String
@available(OSX 10.9, *)
let NSMetadataItemAuthorsKey: String
@available(OSX 10.9, *)
let NSMetadataItemEditorsKey: String
@available(OSX 10.9, *)
let NSMetadataItemParticipantsKey: String
@available(OSX 10.9, *)
let NSMetadataItemProjectsKey: String
@available(OSX 10.9, *)
let NSMetadataItemDownloadedDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemWhereFromsKey: String
@available(OSX 10.9, *)
let NSMetadataItemCommentKey: String
@available(OSX 10.9, *)
let NSMetadataItemCopyrightKey: String
@available(OSX 10.9, *)
let NSMetadataItemLastUsedDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemContentCreationDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemContentModificationDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemDateAddedKey: String
@available(OSX 10.9, *)
let NSMetadataItemDurationSecondsKey: String
@available(OSX 10.9, *)
let NSMetadataItemContactKeywordsKey: String
@available(OSX 10.9, *)
let NSMetadataItemVersionKey: String
@available(OSX 10.9, *)
let NSMetadataItemPixelHeightKey: String
@available(OSX 10.9, *)
let NSMetadataItemPixelWidthKey: String
@available(OSX 10.9, *)
let NSMetadataItemPixelCountKey: String
@available(OSX 10.9, *)
let NSMetadataItemColorSpaceKey: String
@available(OSX 10.9, *)
let NSMetadataItemBitsPerSampleKey: String
@available(OSX 10.9, *)
let NSMetadataItemFlashOnOffKey: String
@available(OSX 10.9, *)
let NSMetadataItemFocalLengthKey: String
@available(OSX 10.9, *)
let NSMetadataItemAcquisitionMakeKey: String
@available(OSX 10.9, *)
let NSMetadataItemAcquisitionModelKey: String
@available(OSX 10.9, *)
let NSMetadataItemISOSpeedKey: String
@available(OSX 10.9, *)
let NSMetadataItemOrientationKey: String
@available(OSX 10.9, *)
let NSMetadataItemLayerNamesKey: String
@available(OSX 10.9, *)
let NSMetadataItemWhiteBalanceKey: String
@available(OSX 10.9, *)
let NSMetadataItemApertureKey: String
@available(OSX 10.9, *)
let NSMetadataItemProfileNameKey: String
@available(OSX 10.9, *)
let NSMetadataItemResolutionWidthDPIKey: String
@available(OSX 10.9, *)
let NSMetadataItemResolutionHeightDPIKey: String
@available(OSX 10.9, *)
let NSMetadataItemExposureModeKey: String
@available(OSX 10.9, *)
let NSMetadataItemExposureTimeSecondsKey: String
@available(OSX 10.9, *)
let NSMetadataItemEXIFVersionKey: String
@available(OSX 10.9, *)
let NSMetadataItemCameraOwnerKey: String
@available(OSX 10.9, *)
let NSMetadataItemFocalLength35mmKey: String
@available(OSX 10.9, *)
let NSMetadataItemLensModelKey: String
@available(OSX 10.9, *)
let NSMetadataItemEXIFGPSVersionKey: String
@available(OSX 10.9, *)
let NSMetadataItemAltitudeKey: String
@available(OSX 10.9, *)
let NSMetadataItemLatitudeKey: String
@available(OSX 10.9, *)
let NSMetadataItemLongitudeKey: String
@available(OSX 10.9, *)
let NSMetadataItemSpeedKey: String
@available(OSX 10.9, *)
let NSMetadataItemTimestampKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSTrackKey: String
@available(OSX 10.9, *)
let NSMetadataItemImageDirectionKey: String
@available(OSX 10.9, *)
let NSMetadataItemNamedLocationKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSStatusKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSMeasureModeKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDOPKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSMapDatumKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDestLatitudeKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDestLongitudeKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDestBearingKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDestDistanceKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSProcessingMethodKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSAreaInformationKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDateStampKey: String
@available(OSX 10.9, *)
let NSMetadataItemGPSDifferentalKey: String
@available(OSX 10.9, *)
let NSMetadataItemCodecsKey: String
@available(OSX 10.9, *)
let NSMetadataItemMediaTypesKey: String
@available(OSX 10.9, *)
let NSMetadataItemStreamableKey: String
@available(OSX 10.9, *)
let NSMetadataItemTotalBitRateKey: String
@available(OSX 10.9, *)
let NSMetadataItemVideoBitRateKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudioBitRateKey: String
@available(OSX 10.9, *)
let NSMetadataItemDeliveryTypeKey: String
@available(OSX 10.9, *)
let NSMetadataItemAlbumKey: String
@available(OSX 10.9, *)
let NSMetadataItemHasAlphaChannelKey: String
@available(OSX 10.9, *)
let NSMetadataItemRedEyeOnOffKey: String
@available(OSX 10.9, *)
let NSMetadataItemMeteringModeKey: String
@available(OSX 10.9, *)
let NSMetadataItemMaxApertureKey: String
@available(OSX 10.9, *)
let NSMetadataItemFNumberKey: String
@available(OSX 10.9, *)
let NSMetadataItemExposureProgramKey: String
@available(OSX 10.9, *)
let NSMetadataItemExposureTimeStringKey: String
@available(OSX 10.9, *)
let NSMetadataItemHeadlineKey: String
@available(OSX 10.9, *)
let NSMetadataItemInstructionsKey: String
@available(OSX 10.9, *)
let NSMetadataItemCityKey: String
@available(OSX 10.9, *)
let NSMetadataItemStateOrProvinceKey: String
@available(OSX 10.9, *)
let NSMetadataItemCountryKey: String
@available(OSX 10.9, *)
let NSMetadataItemTextContentKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudioSampleRateKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudioChannelCountKey: String
@available(OSX 10.9, *)
let NSMetadataItemTempoKey: String
@available(OSX 10.9, *)
let NSMetadataItemKeySignatureKey: String
@available(OSX 10.9, *)
let NSMetadataItemTimeSignatureKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudioEncodingApplicationKey: String
@available(OSX 10.9, *)
let NSMetadataItemComposerKey: String
@available(OSX 10.9, *)
let NSMetadataItemLyricistKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudioTrackNumberKey: String
@available(OSX 10.9, *)
let NSMetadataItemRecordingDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemMusicalGenreKey: String
@available(OSX 10.9, *)
let NSMetadataItemIsGeneralMIDISequenceKey: String
@available(OSX 10.9, *)
let NSMetadataItemRecordingYearKey: String
@available(OSX 10.9, *)
let NSMetadataItemOrganizationsKey: String
@available(OSX 10.9, *)
let NSMetadataItemLanguagesKey: String
@available(OSX 10.9, *)
let NSMetadataItemRightsKey: String
@available(OSX 10.9, *)
let NSMetadataItemPublishersKey: String
@available(OSX 10.9, *)
let NSMetadataItemContributorsKey: String
@available(OSX 10.9, *)
let NSMetadataItemCoverageKey: String
@available(OSX 10.9, *)
let NSMetadataItemSubjectKey: String
@available(OSX 10.9, *)
let NSMetadataItemThemeKey: String
@available(OSX 10.9, *)
let NSMetadataItemDescriptionKey: String
@available(OSX 10.9, *)
let NSMetadataItemIdentifierKey: String
@available(OSX 10.9, *)
let NSMetadataItemAudiencesKey: String
@available(OSX 10.9, *)
let NSMetadataItemNumberOfPagesKey: String
@available(OSX 10.9, *)
let NSMetadataItemPageWidthKey: String
@available(OSX 10.9, *)
let NSMetadataItemPageHeightKey: String
@available(OSX 10.9, *)
let NSMetadataItemSecurityMethodKey: String
@available(OSX 10.9, *)
let NSMetadataItemCreatorKey: String
@available(OSX 10.9, *)
let NSMetadataItemEncodingApplicationsKey: String
@available(OSX 10.9, *)
let NSMetadataItemDueDateKey: String
@available(OSX 10.9, *)
let NSMetadataItemStarRatingKey: String
@available(OSX 10.9, *)
let NSMetadataItemPhoneNumbersKey: String
@available(OSX 10.9, *)
let NSMetadataItemEmailAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemInstantMessageAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemKindKey: String
@available(OSX 10.9, *)
let NSMetadataItemRecipientsKey: String
@available(OSX 10.9, *)
let NSMetadataItemFinderCommentKey: String
@available(OSX 10.9, *)
let NSMetadataItemFontsKey: String
@available(OSX 10.9, *)
let NSMetadataItemAppleLoopsRootKeyKey: String
@available(OSX 10.9, *)
let NSMetadataItemAppleLoopsKeyFilterTypeKey: String
@available(OSX 10.9, *)
let NSMetadataItemAppleLoopsLoopModeKey: String
@available(OSX 10.9, *)
let NSMetadataItemAppleLoopDescriptorsKey: String
@available(OSX 10.9, *)
let NSMetadataItemMusicalInstrumentCategoryKey: String
@available(OSX 10.9, *)
let NSMetadataItemMusicalInstrumentNameKey: String
@available(OSX 10.9, *)
let NSMetadataItemCFBundleIdentifierKey: String
@available(OSX 10.9, *)
let NSMetadataItemInformationKey: String
@available(OSX 10.9, *)
let NSMetadataItemDirectorKey: String
@available(OSX 10.9, *)
let NSMetadataItemProducerKey: String
@available(OSX 10.9, *)
let NSMetadataItemGenreKey: String
@available(OSX 10.9, *)
let NSMetadataItemPerformersKey: String
@available(OSX 10.9, *)
let NSMetadataItemOriginalFormatKey: String
@available(OSX 10.9, *)
let NSMetadataItemOriginalSourceKey: String
@available(OSX 10.9, *)
let NSMetadataItemAuthorEmailAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemRecipientEmailAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemAuthorAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemRecipientAddressesKey: String
@available(OSX 10.9, *)
let NSMetadataItemIsLikelyJunkKey: String
@available(OSX 10.9, *)
let NSMetadataItemExecutableArchitecturesKey: String
@available(OSX 10.9, *)
let NSMetadataItemExecutablePlatformKey: String
@available(OSX 10.9, *)
let NSMetadataItemApplicationCategoriesKey: String
@available(OSX 10.9, *)
let NSMetadataItemIsApplicationManagedKey: String
