
var NSXMLNodeOptionsNone: Int { get }
var NSXMLNodeIsCDATA: Int { get }
var NSXMLNodeExpandEmptyElement: Int { get }
var NSXMLNodeCompactEmptyElement: Int { get }
var NSXMLNodeUseSingleQuotes: Int { get }
var NSXMLNodeUseDoubleQuotes: Int { get }
var NSXMLNodeNeverEscapeContents: Int { get }
var NSXMLDocumentTidyHTML: Int { get }
var NSXMLDocumentTidyXML: Int { get }
var NSXMLDocumentValidate: Int { get }
var NSXMLNodeLoadExternalEntitiesAlways: Int { get }
var NSXMLNodeLoadExternalEntitiesSameOriginOnly: Int { get }
var NSXMLNodeLoadExternalEntitiesNever: Int { get }
var NSXMLDocumentXInclude: Int { get }
var NSXMLNodePrettyPrint: Int { get }
var NSXMLDocumentIncludeContentTypeDeclaration: Int { get }
var NSXMLNodePreserveNamespaceOrder: Int { get }
var NSXMLNodePreserveAttributeOrder: Int { get }
var NSXMLNodePreserveEntities: Int { get }
var NSXMLNodePreservePrefixes: Int { get }
var NSXMLNodePreserveCDATA: Int { get }
var NSXMLNodePreserveWhitespace: Int { get }
var NSXMLNodePreserveDTD: Int { get }
var NSXMLNodePreserveCharacterReferences: Int { get }
var NSXMLNodePromoteSignificantWhitespace: Int { get }
var NSXMLNodePreserveEmptyElements: Int { get }
var NSXMLNodePreserveQuotes: Int { get }
var NSXMLNodePreserveAll: Int { get }
