
extension CSSearchableItemAttributeSet {
  var editors: [String]?
  var participants: [String]?
  var projects: [String]?
  var downloadedDate: NSDate?
  var contentSources: [String]?
  var comment: String?
  var copyright: String?
  var lastUsedDate: NSDate?
  var contentCreationDate: NSDate?
  var contentModificationDate: NSDate?
  var addedDate: NSDate?
  var duration: NSNumber?
  var contactKeywords: [String]?
  var version: String?
  var codecs: [String]?
  var mediaTypes: [String]?
  var streamable: NSNumber?
  var totalBitRate: NSNumber?
  var videoBitRate: NSNumber?
  var audioBitRate: NSNumber?
  var deliveryType: NSNumber?
  var organizations: [String]?
  var role: String?
  var languages: [String]?
  var rights: String?
  var publishers: [String]?
  var contributors: [String]?
  var coverage: [String]?
  var rating: NSNumber?
  var ratingDescription: String?
  var playCount: NSNumber?
  var information: String?
  var director: String?
  var producer: String?
  var genre: String?
  var performers: [String]?
  var originalFormat: String?
  var originalSource: String?
  var local: NSNumber?
  var contentRating: NSNumber?
  var url: NSURL?
}
extension CSSearchableItemAttributeSet {
  var audioSampleRate: NSNumber?
  var audioChannelCount: NSNumber?
  var tempo: NSNumber?
  var keySignature: String?
  var timeSignature: String?
  var audioEncodingApplication: String?
  var composer: String?
  var lyricist: String?
  var album: String?
  var artist: String?
  var audioTrackNumber: NSNumber?
  var recordingDate: NSDate?
  var musicalGenre: String?
  var generalMIDISequence: NSNumber?
  var musicalInstrumentCategory: String?
  var musicalInstrumentName: String?
}
