
@available(tvOS 4.0, *)
let AVVideoCodecKey: String
@available(tvOS 4.0, *)
let AVVideoCodecH264: String
@available(tvOS 4.0, *)
let AVVideoCodecJPEG: String
@available(tvOS 4.0, *)
let AVVideoWidthKey: String
@available(tvOS 4.0, *)
let AVVideoHeightKey: String
@available(tvOS 4.0, *)
let AVVideoPixelAspectRatioKey: String
@available(tvOS 4.0, *)
let AVVideoPixelAspectRatioHorizontalSpacingKey: String
@available(tvOS 4.0, *)
let AVVideoPixelAspectRatioVerticalSpacingKey: String
@available(tvOS 4.0, *)
let AVVideoCleanApertureKey: String
@available(tvOS 4.0, *)
let AVVideoCleanApertureWidthKey: String
@available(tvOS 4.0, *)
let AVVideoCleanApertureHeightKey: String
@available(tvOS 4.0, *)
let AVVideoCleanApertureHorizontalOffsetKey: String
@available(tvOS 4.0, *)
let AVVideoCleanApertureVerticalOffsetKey: String
@available(tvOS 5.0, *)
let AVVideoScalingModeKey: String
@available(tvOS 5.0, *)
let AVVideoScalingModeFit: String
@available(tvOS 5.0, *)
let AVVideoScalingModeResize: String
@available(tvOS 5.0, *)
let AVVideoScalingModeResizeAspect: String
@available(tvOS 5.0, *)
let AVVideoScalingModeResizeAspectFill: String
@available(tvOS 4.0, *)
let AVVideoCompressionPropertiesKey: String
@available(tvOS 4.0, *)
let AVVideoAverageBitRateKey: String
@available(tvOS 5.0, *)
let AVVideoQualityKey: String
@available(tvOS 4.0, *)
let AVVideoMaxKeyFrameIntervalKey: String
@available(tvOS 7.0, *)
let AVVideoMaxKeyFrameIntervalDurationKey: String
@available(tvOS 7.0, *)
let AVVideoAllowFrameReorderingKey: String
@available(tvOS 4.0, *)
let AVVideoProfileLevelKey: String
@available(tvOS 4.0, *)
let AVVideoProfileLevelH264Baseline30: String
@available(tvOS 4.0, *)
let AVVideoProfileLevelH264Baseline31: String
@available(tvOS 5.0, *)
let AVVideoProfileLevelH264Baseline41: String
@available(tvOS 7.0, *)
let AVVideoProfileLevelH264BaselineAutoLevel: String
@available(tvOS 4.0, *)
let AVVideoProfileLevelH264Main30: String
@available(tvOS 4.0, *)
let AVVideoProfileLevelH264Main31: String
@available(tvOS 5.0, *)
let AVVideoProfileLevelH264Main32: String
@available(tvOS 5.0, *)
let AVVideoProfileLevelH264Main41: String
@available(tvOS 7.0, *)
let AVVideoProfileLevelH264MainAutoLevel: String
@available(tvOS 6.0, *)
let AVVideoProfileLevelH264High40: String
@available(tvOS 6.0, *)
let AVVideoProfileLevelH264High41: String
@available(tvOS 7.0, *)
let AVVideoProfileLevelH264HighAutoLevel: String
@available(tvOS 7.0, *)
let AVVideoH264EntropyModeKey: String
@available(tvOS 7.0, *)
let AVVideoH264EntropyModeCAVLC: String
@available(tvOS 7.0, *)
let AVVideoH264EntropyModeCABAC: String
@available(tvOS 7.0, *)
let AVVideoExpectedSourceFrameRateKey: String
@available(tvOS 7.0, *)
let AVVideoAverageNonDroppableFrameRateKey: String
