
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_ForegroundColorARGB: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_BackgroundColorARGB: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_CharacterBackgroundColorARGB: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_BoldStyle: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_ItalicStyle: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_UnderlineStyle: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_FontFamilyName: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_GenericFontFamilyName: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Default: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Serif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_SansSerif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Monospace: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_ProportionalSerif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_ProportionalSansSerif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_MonospaceSerif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_MonospaceSansSerif: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Casual: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Cursive: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_Fantasy: CFString
@available(OSX 10.9, *)
let kCMTextMarkupGenericFontName_SmallCapital: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_RelativeFontSize: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_VerticalLayout: CFString
@available(OSX 10.9, *)
let kCMTextVerticalLayout_LeftToRight: CFString
@available(OSX 10.9, *)
let kCMTextVerticalLayout_RightToLeft: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_Alignment: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAlignmentType_Start: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAlignmentType_Middle: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAlignmentType_End: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAlignmentType_Left: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAlignmentType_Right: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_WritingDirectionSizePercentage: CFString
@available(OSX 10.9, *)
let kCMTextMarkupAttribute_CharacterEdgeStyle: CFString
@available(OSX 10.9, *)
let kCMTextMarkupCharacterEdgeStyle_None: CFString
@available(OSX 10.9, *)
let kCMTextMarkupCharacterEdgeStyle_Raised: CFString
@available(OSX 10.9, *)
let kCMTextMarkupCharacterEdgeStyle_Depressed: CFString
@available(OSX 10.9, *)
let kCMTextMarkupCharacterEdgeStyle_Uniform: CFString
@available(OSX 10.9, *)
let kCMTextMarkupCharacterEdgeStyle_DropShadow: CFString
