#ifndef TEST_INTEROP_CXX_VALUE_WITNESS_TABLE_INPUTS_CLASS_TEMPLATE_METADATA_H
#define TEST_INTEROP_CXX_VALUE_WITNESS_TABLE_INPUTS_CLASS_TEMPLATE_METADATA_H

template<class T>
struct ClassTemplate {};

using Spec1 = ClassTemplate<int>;
using Spec2 = ClassTemplate<Spec1>;

#endif // TEST_INTEROP_CXX_VALUE_WITNESS_TABLE_INPUTS_CLASS_TEMPLATE_METADATA_H
