
var TWTweetComposeViewControllerResultCancelled: Int { get }
var TWTweetComposeViewControllerResultDone: Int { get }
typealias TWTweetComposeViewControllerResult = SLComposeViewControllerResult
typealias TWTweetComposeViewControllerCompletionHandler = SLComposeViewControllerCompletionHandler
