import RoundTrip

public func test() {
  roundTripType(SIMD2<Int>.self)
  roundTripType(SIMD3<Int>.self)
  roundTripType(SIMD4<Int>.self)
  roundTripType(SIMD8<Int>.self)
  roundTripType(SIMD16<Int>.self)
  roundTripType(SIMD32<Int>.self)
  roundTripType(SIMD64<Int>.self)

  roundTripType(SIMD2<UInt>.self)
  roundTripType(SIMD3<UInt>.self)
  roundTripType(SIMD4<UInt>.self)
  roundTripType(SIMD8<UInt>.self)
  roundTripType(SIMD16<UInt>.self)
  roundTripType(SIMD32<UInt>.self)
  roundTripType(SIMD64<UInt>.self)

  roundTripType(SIMD2<Float>.self)
  roundTripType(SIMD3<Float>.self)
  roundTripType(SIMD4<Float>.self)
  roundTripType(SIMD8<Float>.self)
  roundTripType(SIMD16<Float>.self)
  roundTripType(SIMD32<Float>.self)
  roundTripType(SIMD64<Float>.self)

  roundTripType(SIMD2<Double>.self)
  roundTripType(SIMD3<Double>.self)
  roundTripType(SIMD4<Double>.self)
  roundTripType(SIMD8<Double>.self)
  roundTripType(SIMD16<Double>.self)
  roundTripType(SIMD32<Double>.self)
  roundTripType(SIMD64<Double>.self)

  roundTripType(SIMD2<Int8>.self)
  roundTripType(SIMD3<Int8>.self)
  roundTripType(SIMD4<Int8>.self)
  roundTripType(SIMD8<Int8>.self)
  roundTripType(SIMD16<Int8>.self)
  roundTripType(SIMD32<Int8>.self)
  roundTripType(SIMD64<Int8>.self)

  roundTripType(SIMD2<Int16>.self)
  roundTripType(SIMD3<Int16>.self)
  roundTripType(SIMD4<Int16>.self)
  roundTripType(SIMD8<Int16>.self)
  roundTripType(SIMD16<Int16>.self)
  roundTripType(SIMD32<Int16>.self)
  roundTripType(SIMD64<Int16>.self)

  roundTripType(SIMD2<Int32>.self)
  roundTripType(SIMD3<Int32>.self)
  roundTripType(SIMD4<Int32>.self)
  roundTripType(SIMD8<Int32>.self)
  roundTripType(SIMD16<Int32>.self)
  roundTripType(SIMD32<Int32>.self)
  roundTripType(SIMD64<Int32>.self)

  roundTripType(SIMD2<Int64>.self)
  roundTripType(SIMD3<Int64>.self)
  roundTripType(SIMD4<Int64>.self)
  roundTripType(SIMD8<Int64>.self)
  roundTripType(SIMD16<Int64>.self)
  roundTripType(SIMD32<Int64>.self)
  roundTripType(SIMD64<Int64>.self)

  roundTripType(SIMD2<UInt8>.self)
  roundTripType(SIMD3<UInt8>.self)
  roundTripType(SIMD4<UInt8>.self)
  roundTripType(SIMD8<UInt8>.self)
  roundTripType(SIMD16<UInt8>.self)
  roundTripType(SIMD32<UInt8>.self)
  roundTripType(SIMD64<UInt8>.self)

  roundTripType(SIMD2<UInt16>.self)
  roundTripType(SIMD3<UInt16>.self)
  roundTripType(SIMD4<UInt16>.self)
  roundTripType(SIMD8<UInt16>.self)
  roundTripType(SIMD16<UInt16>.self)
  roundTripType(SIMD32<UInt16>.self)
  roundTripType(SIMD64<UInt16>.self)

  roundTripType(SIMD2<UInt32>.self)
  roundTripType(SIMD3<UInt32>.self)
  roundTripType(SIMD4<UInt32>.self)
  roundTripType(SIMD8<UInt32>.self)
  roundTripType(SIMD16<UInt32>.self)
  roundTripType(SIMD32<UInt32>.self)
  roundTripType(SIMD64<UInt32>.self)

  roundTripType(SIMD2<UInt64>.self)
  roundTripType(SIMD3<UInt64>.self)
  roundTripType(SIMD4<UInt64>.self)
  roundTripType(SIMD8<UInt64>.self)
  roundTripType(SIMD16<UInt64>.self)
  roundTripType(SIMD32<UInt64>.self)
  roundTripType(SIMD64<UInt64>.self)
}
