
@available(watchOS 2.0, *)
let kUTTypeItem: CFString
@available(watchOS 2.0, *)
let kUTTypeContent: CFString
@available(watchOS 2.0, *)
let kUTTypeCompositeContent: CFString
@available(watchOS 2.0, *)
let kUTTypeMessage: CFString
@available(watchOS 2.0, *)
let kUTTypeContact: CFString
@available(watchOS 2.0, *)
let kUTTypeArchive: CFString
@available(watchOS 2.0, *)
let kUTTypeDiskImage: CFString
@available(watchOS 2.0, *)
let kUTTypeData: CFString
@available(watchOS 2.0, *)
let kUTTypeDirectory: CFString
@available(watchOS 2.0, *)
let kUTTypeResolvable: CFString
@available(watchOS 2.0, *)
let kUTTypeSymLink: CFString
@available(watchOS 2.0, *)
let kUTTypeExecutable: CFString
@available(watchOS 2.0, *)
let kUTTypeMountPoint: CFString
@available(watchOS 2.0, *)
let kUTTypeAliasFile: CFString
@available(watchOS 2.0, *)
let kUTTypeAliasRecord: CFString
@available(watchOS 2.0, *)
let kUTTypeURLBookmarkData: CFString
@available(watchOS 2.0, *)
let kUTTypeURL: CFString
@available(watchOS 2.0, *)
let kUTTypeFileURL: CFString
@available(watchOS 2.0, *)
let kUTTypeText: CFString
@available(watchOS 2.0, *)
let kUTTypePlainText: CFString
@available(watchOS 2.0, *)
let kUTTypeUTF8PlainText: CFString
@available(watchOS 2.0, *)
let kUTTypeUTF16ExternalPlainText: CFString
@available(watchOS 2.0, *)
let kUTTypeUTF16PlainText: CFString
@available(watchOS 2.0, *)
let kUTTypeDelimitedText: CFString
@available(watchOS 2.0, *)
let kUTTypeCommaSeparatedText: CFString
@available(watchOS 2.0, *)
let kUTTypeTabSeparatedText: CFString
@available(watchOS 2.0, *)
let kUTTypeUTF8TabSeparatedText: CFString
@available(watchOS 2.0, *)
let kUTTypeRTF: CFString
@available(watchOS 2.0, *)
let kUTTypeHTML: CFString
@available(watchOS 2.0, *)
let kUTTypeXML: CFString
@available(watchOS 2.0, *)
let kUTTypeSourceCode: CFString
@available(watchOS 2.0, *)
let kUTTypeAssemblyLanguageSource: CFString
@available(watchOS 2.0, *)
let kUTTypeCSource: CFString
@available(watchOS 2.0, *)
let kUTTypeObjectiveCSource: CFString
@available(watchOS 2.0, *)
let kUTTypeSwiftSource: CFString
@available(watchOS 2.0, *)
let kUTTypeCPlusPlusSource: CFString
@available(watchOS 2.0, *)
let kUTTypeObjectiveCPlusPlusSource: CFString
@available(watchOS 2.0, *)
let kUTTypeCHeader: CFString
@available(watchOS 2.0, *)
let kUTTypeCPlusPlusHeader: CFString
@available(watchOS 2.0, *)
let kUTTypeJavaSource: CFString
@available(watchOS 2.0, *)
let kUTTypeScript: CFString
@available(watchOS 2.0, *)
let kUTTypeAppleScript: CFString
@available(watchOS 2.0, *)
let kUTTypeOSAScript: CFString
@available(watchOS 2.0, *)
let kUTTypeOSAScriptBundle: CFString
@available(watchOS 2.0, *)
let kUTTypeJavaScript: CFString
@available(watchOS 2.0, *)
let kUTTypeShellScript: CFString
@available(watchOS 2.0, *)
let kUTTypePerlScript: CFString
@available(watchOS 2.0, *)
let kUTTypePythonScript: CFString
@available(watchOS 2.0, *)
let kUTTypeRubyScript: CFString
@available(watchOS 2.0, *)
let kUTTypePHPScript: CFString
@available(watchOS 2.0, *)
let kUTTypeJSON: CFString
@available(watchOS 2.0, *)
let kUTTypePropertyList: CFString
@available(watchOS 2.0, *)
let kUTTypeXMLPropertyList: CFString
@available(watchOS 2.0, *)
let kUTTypeBinaryPropertyList: CFString
@available(watchOS 2.0, *)
let kUTTypePDF: CFString
@available(watchOS 2.0, *)
let kUTTypeRTFD: CFString
@available(watchOS 2.0, *)
let kUTTypeFlatRTFD: CFString
@available(watchOS 2.0, *)
let kUTTypeTXNTextAndMultimediaData: CFString
@available(watchOS 2.0, *)
let kUTTypeWebArchive: CFString
@available(watchOS 2.0, *)
let kUTTypeImage: CFString
@available(watchOS 2.0, *)
let kUTTypeJPEG: CFString
@available(watchOS 2.0, *)
let kUTTypeJPEG2000: CFString
@available(watchOS 2.0, *)
let kUTTypeTIFF: CFString
@available(watchOS 2.0, *)
let kUTTypePICT: CFString
@available(watchOS 2.0, *)
let kUTTypeGIF: CFString
@available(watchOS 2.0, *)
let kUTTypePNG: CFString
@available(watchOS 2.0, *)
let kUTTypeQuickTimeImage: CFString
@available(watchOS 2.0, *)
let kUTTypeAppleICNS: CFString
@available(watchOS 2.0, *)
let kUTTypeBMP: CFString
@available(watchOS 2.0, *)
let kUTTypeICO: CFString
@available(watchOS 2.0, *)
let kUTTypeRawImage: CFString
@available(watchOS 2.0, *)
let kUTTypeScalableVectorGraphics: CFString
@available(watchOS 2.1, *)
let kUTTypeLivePhoto: CFString
@available(watchOS 2.0, *)
let kUTTypeAudiovisualContent: CFString
@available(watchOS 2.0, *)
let kUTTypeMovie: CFString
@available(watchOS 2.0, *)
let kUTTypeVideo: CFString
@available(watchOS 2.0, *)
let kUTTypeAudio: CFString
@available(watchOS 2.0, *)
let kUTTypeQuickTimeMovie: CFString
@available(watchOS 2.0, *)
let kUTTypeMPEG: CFString
@available(watchOS 2.0, *)
let kUTTypeMPEG2Video: CFString
@available(watchOS 2.0, *)
let kUTTypeMPEG2TransportStream: CFString
@available(watchOS 2.0, *)
let kUTTypeMP3: CFString
@available(watchOS 2.0, *)
let kUTTypeMPEG4: CFString
@available(watchOS 2.0, *)
let kUTTypeMPEG4Audio: CFString
@available(watchOS 2.0, *)
let kUTTypeAppleProtectedMPEG4Audio: CFString
@available(watchOS 2.0, *)
let kUTTypeAppleProtectedMPEG4Video: CFString
@available(watchOS 2.0, *)
let kUTTypeAVIMovie: CFString
@available(watchOS 2.0, *)
let kUTTypeAudioInterchangeFileFormat: CFString
@available(watchOS 2.0, *)
let kUTTypeWaveformAudio: CFString
@available(watchOS 2.0, *)
let kUTTypeMIDIAudio: CFString
@available(watchOS 2.0, *)
let kUTTypePlaylist: CFString
@available(watchOS 2.0, *)
let kUTTypeM3UPlaylist: CFString
@available(watchOS 2.0, *)
let kUTTypeFolder: CFString
@available(watchOS 2.0, *)
let kUTTypeVolume: CFString
@available(watchOS 2.0, *)
let kUTTypePackage: CFString
@available(watchOS 2.0, *)
let kUTTypeBundle: CFString
@available(watchOS 2.0, *)
let kUTTypePluginBundle: CFString
@available(watchOS 2.0, *)
let kUTTypeSpotlightImporter: CFString
@available(watchOS 2.0, *)
let kUTTypeQuickLookGenerator: CFString
@available(watchOS 2.0, *)
let kUTTypeXPCService: CFString
@available(watchOS 2.0, *)
let kUTTypeFramework: CFString
@available(watchOS 2.0, *)
let kUTTypeApplication: CFString
@available(watchOS 2.0, *)
let kUTTypeApplicationBundle: CFString
@available(watchOS 2.0, *)
let kUTTypeApplicationFile: CFString
@available(watchOS 2.0, *)
let kUTTypeUnixExecutable: CFString
@available(watchOS 2.0, *)
let kUTTypeWindowsExecutable: CFString
@available(watchOS 2.0, *)
let kUTTypeJavaClass: CFString
@available(watchOS 2.0, *)
let kUTTypeJavaArchive: CFString
@available(watchOS 2.0, *)
let kUTTypeSystemPreferencesPane: CFString
@available(watchOS 2.0, *)
let kUTTypeGNUZipArchive: CFString
@available(watchOS 2.0, *)
let kUTTypeBzip2Archive: CFString
@available(watchOS 2.0, *)
let kUTTypeZipArchive: CFString
@available(watchOS 2.0, *)
let kUTTypeSpreadsheet: CFString
@available(watchOS 2.0, *)
let kUTTypePresentation: CFString
@available(watchOS 2.0, *)
let kUTTypeDatabase: CFString
@available(watchOS 2.0, *)
let kUTTypeVCard: CFString
@available(watchOS 2.0, *)
let kUTTypeToDoItem: CFString
@available(watchOS 2.0, *)
let kUTTypeCalendarEvent: CFString
@available(watchOS 2.0, *)
let kUTTypeEmailMessage: CFString
@available(watchOS 2.0, *)
let kUTTypeInternetLocation: CFString
@available(watchOS 2.0, *)
let kUTTypeInkText: CFString
@available(watchOS 2.0, *)
let kUTTypeFont: CFString
@available(watchOS 2.0, *)
let kUTTypeBookmark: CFString
@available(watchOS 2.0, *)
let kUTType3DContent: CFString
@available(watchOS 2.0, *)
let kUTTypePKCS12: CFString
@available(watchOS 2.0, *)
let kUTTypeX509Certificate: CFString
@available(watchOS 2.0, *)
let kUTTypeElectronicPublication: CFString
@available(watchOS 2.0, *)
let kUTTypeLog: CFString
