#ifndef TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_A_H
#define TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_A_H

#include "wrapper.h"

WrapperInt getWrapperIntA() {
  return WrapperInt();
}

#endif // TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_A_H
