#ifndef TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_B_H
#define TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_B_H

#include "wrapper.h"

WrapperInt getWrapperIntB() {
  return WrapperInt();
}

#endif // TEST_INTEROP_CXX_TEMPLATES_INPUTS_MULTIPLE_MODULES_B_H
