
@available(OSX 10.7, *)
let AVVideoCodecKey: String
@available(OSX 10.7, *)
let AVVideoCodecH264: String
@available(OSX 10.7, *)
let AVVideoCodecJPEG: String
@available(OSX 10.7, *)
let AVVideoCodecAppleProRes4444: String
@available(OSX 10.7, *)
let AVVideoCodecAppleProRes422: String
@available(OSX 10.7, *)
let AVVideoWidthKey: String
@available(OSX 10.7, *)
let AVVideoHeightKey: String
@available(OSX 10.7, *)
let AVVideoPixelAspectRatioKey: String
@available(OSX 10.7, *)
let AVVideoPixelAspectRatioHorizontalSpacingKey: String
@available(OSX 10.7, *)
let AVVideoPixelAspectRatioVerticalSpacingKey: String
@available(OSX 10.7, *)
let AVVideoCleanApertureKey: String
@available(OSX 10.7, *)
let AVVideoCleanApertureWidthKey: String
@available(OSX 10.7, *)
let AVVideoCleanApertureHeightKey: String
@available(OSX 10.7, *)
let AVVideoCleanApertureHorizontalOffsetKey: String
@available(OSX 10.7, *)
let AVVideoCleanApertureVerticalOffsetKey: String
@available(OSX 10.7, *)
let AVVideoScalingModeKey: String
@available(OSX 10.7, *)
let AVVideoScalingModeFit: String
@available(OSX 10.7, *)
let AVVideoScalingModeResize: String
@available(OSX 10.7, *)
let AVVideoScalingModeResizeAspect: String
@available(OSX 10.7, *)
let AVVideoScalingModeResizeAspectFill: String
@available(OSX 10.7, *)
let AVVideoColorPropertiesKey: String
@available(OSX 10.7, *)
let AVVideoColorPrimariesKey: String
@available(OSX 10.7, *)
let AVVideoColorPrimaries_ITU_R_709_2: String
@available(OSX 10.7, *)
let AVVideoColorPrimaries_EBU_3213: String
@available(OSX 10.7, *)
let AVVideoColorPrimaries_SMPTE_C: String
@available(OSX 10.7, *)
let AVVideoTransferFunctionKey: String
@available(OSX 10.7, *)
let AVVideoTransferFunction_ITU_R_709_2: String
@available(OSX 10.7, *)
let AVVideoTransferFunction_SMPTE_240M_1995: String
@available(OSX 10.7, *)
let AVVideoYCbCrMatrixKey: String
@available(OSX 10.7, *)
let AVVideoYCbCrMatrix_ITU_R_709_2: String
@available(OSX 10.7, *)
let AVVideoYCbCrMatrix_ITU_R_601_4: String
@available(OSX 10.7, *)
let AVVideoYCbCrMatrix_SMPTE_240M_1995: String
@available(OSX 10.7, *)
let AVVideoCompressionPropertiesKey: String
@available(OSX 10.7, *)
let AVVideoAverageBitRateKey: String
@available(OSX 10.7, *)
let AVVideoQualityKey: String
@available(OSX 10.7, *)
let AVVideoMaxKeyFrameIntervalKey: String
@available(OSX 10.9, *)
let AVVideoMaxKeyFrameIntervalDurationKey: String
@available(OSX 10.10, *)
let AVVideoAllowFrameReorderingKey: String
@available(OSX 10.8, *)
let AVVideoProfileLevelKey: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Baseline30: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Baseline31: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Baseline41: String
@available(OSX 10.9, *)
let AVVideoProfileLevelH264BaselineAutoLevel: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Main30: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Main31: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Main32: String
@available(OSX 10.8, *)
let AVVideoProfileLevelH264Main41: String
@available(OSX 10.9, *)
let AVVideoProfileLevelH264MainAutoLevel: String
@available(OSX 10.9, *)
let AVVideoProfileLevelH264High40: String
@available(OSX 10.9, *)
let AVVideoProfileLevelH264High41: String
@available(OSX 10.9, *)
let AVVideoProfileLevelH264HighAutoLevel: String
@available(OSX 10.10, *)
let AVVideoH264EntropyModeKey: String
@available(OSX 10.10, *)
let AVVideoH264EntropyModeCAVLC: String
@available(OSX 10.10, *)
let AVVideoH264EntropyModeCABAC: String
@available(OSX 10.10, *)
let AVVideoExpectedSourceFrameRateKey: String
@available(OSX 10.10, *)
let AVVideoAverageNonDroppableFrameRateKey: String
@available(OSX 10.10, *)
let AVVideoEncoderSpecificationKey: String
