#ifndef TEST_INTEROP_C_LIBC_INPUTS_INCLUDE_SIGNAL_H
#define TEST_INTEROP_C_LIBC_INPUTS_INCLUDE_SIGNAL_H

#include <signal.h>

pid_t returnPidT();

#endif // TEST_INTEROP_C_LIBC_INPUTS_INCLUDE_SIGNAL_H