# Copyright 2019 Saleem Abdulrasool.  All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause

GENCCODE_ASSEMBLY_TYPE=-a gcc
SO=so
SOBJ=so
A=a
LIBPREFIX=@CMAKE_SHARED_LIBRARY_PREFIX@
LIB_EXT_ORDER=.@PROJECT_VERSION_MAJOR@
COMPILE="@CMAKE_COMMAND@" -E echo COMPILE
LIBFLAGS=
GENLIB="@CMAKE_COMMAND@" -E echo GENLIB
LDICUDTFLAGS=-nodefaultlibs -nostdlibs
AR=@CMAKE_AR@
ARFLAGS=
RANLIB=@CMAKE_RANLIB@
INSTALL_CMD="@CMAKE_COMMAND@" -E echo INSTALL
