
@available(tvOS 4.2, *)
let MPMediaItemPropertyPersistentID: String
let MPMediaItemPropertyMediaType: String
let MPMediaItemPropertyTitle: String
let MPMediaItemPropertyAlbumTitle: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyAlbumPersistentID: String
let MPMediaItemPropertyArtist: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyArtistPersistentID: String
let MPMediaItemPropertyAlbumArtist: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyAlbumArtistPersistentID: String
let MPMediaItemPropertyGenre: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyGenrePersistentID: String
let MPMediaItemPropertyComposer: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyComposerPersistentID: String
let MPMediaItemPropertyPlaybackDuration: String
let MPMediaItemPropertyAlbumTrackNumber: String
let MPMediaItemPropertyAlbumTrackCount: String
let MPMediaItemPropertyDiscNumber: String
let MPMediaItemPropertyDiscCount: String
let MPMediaItemPropertyArtwork: String
let MPMediaItemPropertyLyrics: String
let MPMediaItemPropertyIsCompilation: String
@available(tvOS 4.0, *)
let MPMediaItemPropertyReleaseDate: String
@available(tvOS 4.0, *)
let MPMediaItemPropertyBeatsPerMinute: String
@available(tvOS 4.0, *)
let MPMediaItemPropertyComments: String
@available(tvOS 4.0, *)
let MPMediaItemPropertyAssetURL: String
@available(tvOS 6.0, *)
let MPMediaItemPropertyIsCloudItem: String
@available(tvOS 9.2, *)
let MPMediaItemPropertyHasProtectedAsset: String
let MPMediaItemPropertyPodcastTitle: String
@available(tvOS 4.2, *)
let MPMediaItemPropertyPodcastPersistentID: String
let MPMediaItemPropertyPlayCount: String
let MPMediaItemPropertySkipCount: String
let MPMediaItemPropertyRating: String
let MPMediaItemPropertyLastPlayedDate: String
@available(tvOS 4.0, *)
let MPMediaItemPropertyUserGrouping: String
@available(tvOS 6.0, *)
let MPMediaItemPropertyBookmarkTime: String
