import sys
import os
import subprocess
import shlex

# TODO: Convert this in Python
tmp = sys.argv[1]
testcases = sys.argv[2]
build_cmd = sys.argv[3]
lib_pattern = sys.argv[4]
# print("build cmd:", cmd)
print("lib pattern:", lib_pattern)

# RUN:
# for module in %S/Inputs/testcases/*.swift; do
#   modname=$(basename $module .swift);
#   echo "import $modname" >> %t/all-tests.swift;
# done
# TODO: .swift -> strip -> import
for test in os.listdir(testcases):
    if not test.endswith(".swift"):
        continue

    modname = os.path.splitext(test)[0]
    module_path = os.path.join(tmp, f"{modname}.swiftmodule")
    lib_name = lib_pattern.replace("PLACEHOLDER", modname)
    test_path = os.path.join(testcases, test)
    # print("modname:", modname)
    # print("module:", module)

    #   %target-build-swift -g -static
    # -emit-module-path %t/$modname.swiftmodule -emit-module -emit-library #
    # -module-name $modname
    # -o %t/%target-static-library-name($modname)
    # -I%t
    # -L%t
    #  $module
    # -lRoundTrip;
    # FIXME:  File name too long so need to split string
    cmd = shlex.split(build_cmd) + [
        "-g",
        "-static",
        "-emit-module-path",
        module_path,
        "-emit-module",
        "-emit-library",
        "-module-name",
        modname,
        "-o",
        os.path.join(tmp, lib_name),
        f"-I{tmp}",
        f"-L{tmp}",
        test_path,
        "-lRoundTrip",
    ]
    subprocess.check_call(cmd)

    #   echo "  print(\"--- $modname\")" >> %t/all-tests.swift;
    #   echo "  $modname.test()" >> %t/all-tests.swift;
    #   echo "  print(\"\")" >> %t/all-tests.swift;
    #   echo "-l$modname" >> %t/link.txt;


# RUN: echo "func runAllTests() throws {" >> %t/all-tests.swift

# RUN:
# for module in %S/Inputs/testcases/*.swift; do
#   modname=$(basename $module .swift);

#   %target-build-swift -g -static -emit-module-path %t/$modname.swiftmodule -emit-module -emit-library -module-name $modname -o %t/%target-static-library-name($modname) -I%t -L%t $module -lRoundTrip;

#   echo "  print(\"--- $modname\")" >> %t/all-tests.swift;
#   echo "  $modname.test()" >> %t/all-tests.swift;
#   echo "  print(\"\")" >> %t/all-tests.swift;
#   echo "-l$modname" >> %t/link.txt;
# done

# RUN: echo "}" >> %t/all-tests.swift

# RUN: echo "// AUTOGENERATED" > %t/all-tests.swift
# with open(os.path.join(tmp, "all-tests.swift"), "w") as f:
#     f.write("// AUTOGENERATED")
