import sys
import os
import subprocess
import shlex

tmp = sys.argv[1]
testcases = sys.argv[2]
build_cmd = sys.argv[3]
lib_pattern = sys.argv[4]

imports = []
body = []

for test in os.listdir(testcases):
    if not test.endswith(".swift"):
        continue

    modname = os.path.splitext(test)[0]
    module_path = os.path.join(tmp, f"{modname}.swiftmodule")
    lib_name = lib_pattern.replace("PLACEHOLDER", modname)
    test_path = os.path.join(testcases, test)
    
    cmd = shlex.split(build_cmd) + [
        "-g",
        "-static",
        "-emit-module-path",
        module_path,
        "-emit-module",
        "-emit-library",
        "-module-name",
        modname,
        "-o",
        os.path.join(tmp, lib_name),
        f"-I{tmp}",
        f"-L{tmp}",
        test_path,
        "-lRoundTrip",
    ]
    subprocess.check_call(cmd)

    imports.append(f"import {modname}")
    #   echo "  print(\"--- $modname\")" >> %t/all-tests.swift;
    #   echo "  $modname.test()" >> %t/all-tests.swift;
    #   echo "  print(\"\")" >> %t/all-tests.swift;
    #   echo "-l$modname" >> %t/link.txt;


# RUN: echo "// AUTOGENERATED" > %t/all-tests.swift
with open(os.path.join(tmp, "all-tests.swift"), "w") as f:
    f.write("// AUTOGENERATED\n")

    #   echo "import $modname" >> %t/all-tests.swift;
    for line in imports:
        f.write(line + "\n")

    # RUN: echo "func runAllTests() throws {" >> %t/all-tests.swift
    f.write("func runAllTest() throws {\n")

    f.write("}\n")



