
extension CIFilter {
  /*not inherited*/ init!(imageURL url: NSURL!, options options: [NSObject : AnyObject]! = [:])
  /*not inherited*/ init!(imageData data: NSData!, options options: [NSObject : AnyObject]! = [:])
}
@available(OSX 10.5, *)
let kCIInputDecoderVersionKey: String
@available(OSX 10.5, *)
let kCISupportedDecoderVersionsKey: String
@available(OSX 10.5, *)
let kCIInputBoostKey: String
@available(OSX 10.5, *)
let kCIInputNeutralChromaticityXKey: String
@available(OSX 10.5, *)
let kCIInputNeutralChromaticityYKey: String
@available(OSX 10.5, *)
let kCIInputNeutralTemperatureKey: String
@available(OSX 10.5, *)
let kCIInputNeutralTintKey: String
@available(OSX 10.5, *)
let kCIInputNeutralLocationKey: String
@available(OSX 10.5, *)
let kCIInputScaleFactorKey: String
@available(OSX 10.5, *)
let kCIInputAllowDraftModeKey: String
@available(OSX 10.5, *)
let kCIInputIgnoreImageOrientationKey: String
@available(OSX 10.5, *)
let kCIInputImageOrientationKey: String
@available(OSX 10.5, *)
let kCIInputEnableSharpeningKey: String
@available(OSX 10.5, *)
let kCIInputEnableChromaticNoiseTrackingKey: String
@available(OSX 10.7, *)
let kCIInputNoiseReductionAmountKey: String
@available(OSX 10.10, *)
let kCIInputEnableVendorLensCorrectionKey: String
@available(OSX 10.10, *)
let kCIInputLuminanceNoiseReductionAmountKey: String
@available(OSX 10.10, *)
let kCIInputColorNoiseReductionAmountKey: String
@available(OSX 10.10, *)
let kCIInputNoiseReductionSharpnessAmountKey: String
@available(OSX 10.10, *)
let kCIInputNoiseReductionContrastAmountKey: String
@available(OSX 10.10, *)
let kCIInputNoiseReductionDetailAmountKey: String
@available(OSX 10.5, *)
let kCIInputBoostShadowAmountKey: String
@available(OSX 10.7, *)
let kCIInputLinearSpaceFilter: String
@available(OSX 10.5, *)
let kCIOutputNativeSizeKey: String
@available(OSX 10.7, *)
let kCIActiveKeys: String
