# This source file is part of the Swift.org open source project
#
# Copyright (c) 2023 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

name: 🌟 Request a change
description: >
  Request a feature, improvement, or other change.
labels: [feature, triage needed]
body:
  - type: markdown
    attributes:
      value: >
        This repository hosts the Swift compiler, the Swift standard library,
        the Swift runtime, SourceKit, and IDE support for the Swift language.
        It does *not* track feedback on Xcode and other closed source Apple
        developer software such as SwiftUI and UIKit; please direct it to
        [Feedback Assistant](https://developer.apple.com/bug-reporting)
        instead.

        ___


        Swift is guided by a community-driven process referred to as the
        [Swift evolution](https://www.swift.org/swift-evolution)
        process. Submitting this form is not a guarantee that the request will
        be considered or implemented. If the request implies an addition,
        removal, or change to the features of the Swift language or the public
        interface of the Swift standard library, please consider socializing it
        on the
        [Swift forums](https://forums.swift.org/c/evolution/discuss)
        instead. The Swift forums are the preferred space for sharing ideas and
        discussing them with the Swift community.
  - type: textarea
    attributes:
      label: Motivation
      description: >
        Describe the problems that this idea seeks to address. If the
        problem is that some common pattern is currently hard to express, show
        how one can currently get a similar effect and describe its drawbacks.
        If it's completely new functionality that cannot be emulated, motivate
        why this new functionality would help create better Swift code or
        developer tools.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: >
        Describe the solution to the problem. Provide examples and describe how
        they work. Show how this solution is better than current workarounds: is
        it cleaner, safer, or more efficient?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: >
        Any alternative approaches that were considered, and why the *proposed
        solution* was chosen instead.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: >
        Any complementary information that could be valuable to an author of a
        formal proposal, an implementor, or future discussions. For example, a
        link to a discussion or post that motivated this request.
    validations:
      required: false
