
@available(OSX 10.1, *)
let kSCResvLink: CFString
@available(OSX 10.1, *)
let kSCResvInactive: CFString
@available(OSX 10.1, *)
let kSCPropInterfaceName: CFString
@available(OSX 10.1, *)
let kSCPropMACAddress: CFString
@available(OSX 10.1, *)
let kSCPropUserDefinedName: CFString
@available(OSX 10.1, *)
let kSCPropVersion: CFString
@available(OSX 10.1, *)
let kSCPrefCurrentSet: CFString
@available(OSX 10.1, *)
let kSCPrefNetworkServices: CFString
@available(OSX 10.1, *)
let kSCPrefSets: CFString
@available(OSX 10.1, *)
let kSCPrefSystem: CFString
@available(OSX 10.1, *)
let kSCCompNetwork: CFString
@available(OSX 10.1, *)
let kSCCompService: CFString
@available(OSX 10.1, *)
let kSCCompGlobal: CFString
@available(OSX 10.2, *)
let kSCCompHostNames: CFString
@available(OSX 10.1, *)
let kSCCompInterface: CFString
@available(OSX 10.1, *)
let kSCCompSystem: CFString
@available(OSX 10.1, *)
let kSCCompUsers: CFString
@available(OSX 10.1, *)
let kSCCompAnyRegex: CFString
@available(OSX 10.1, *)
let kSCEntNetAirPort: CFString
@available(OSX 10.1, *)
let kSCEntNetDHCP: CFString
@available(OSX 10.1, *)
let kSCEntNetDNS: CFString
@available(OSX 10.1, *)
let kSCEntNetEthernet: CFString
@available(OSX 10.3, *)
let kSCEntNetFireWire: CFString
@available(OSX 10.1, *)
let kSCEntNetInterface: CFString
@available(OSX 10.5, *)
let kSCEntNetIPSec: CFString
@available(OSX 10.1, *)
let kSCEntNetIPv4: CFString
@available(OSX 10.1, *)
let kSCEntNetIPv6: CFString
@available(OSX 10.3, *)
let kSCEntNetL2TP: CFString
@available(OSX 10.1, *)
let kSCEntNetLink: CFString
@available(OSX 10.1, *)
let kSCEntNetModem: CFString
@available(OSX 10.1, *)
let kSCEntNetPPP: CFString
@available(OSX 10.1, *)
let kSCEntNetPPPoE: CFString
@available(OSX 10.3, *)
let kSCEntNetPPPSerial: CFString
@available(OSX 10.3, *)
let kSCEntNetPPTP: CFString
@available(OSX 10.1, *)
let kSCEntNetProxies: CFString
@available(OSX 10.5, *)
let kSCEntNetSMB: CFString
@available(OSX 10.3, *)
let kSCEntNet6to4: CFString
@available(OSX 10.2, *)
let kSCPropNetOverridePrimary: CFString
@available(OSX 10.1, *)
let kSCPropNetServiceOrder: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPOverridePrimary: CFString
@available(OSX 10.2, *)
let kSCPropNetInterfaces: CFString
@available(OSX 10.2, *)
let kSCPropNetLocalHostName: CFString
@available(OSX 10.1, *)
let kSCPropNetDNSDomainName: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSOptions: CFString
@available(OSX 10.1, *)
let kSCPropNetDNSSearchDomains: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSSearchOrder: CFString
@available(OSX 10.1, *)
let kSCPropNetDNSServerAddresses: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSServerPort: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSServerTimeout: CFString
@available(OSX 10.1, *)
let kSCPropNetDNSSortList: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSSupplementalMatchDomains: CFString
@available(OSX 10.4, *)
let kSCPropNetDNSSupplementalMatchOrders: CFString
@available(OSX 10.2, *)
let kSCPropNetEthernetMediaSubType: CFString
@available(OSX 10.2, *)
let kSCPropNetEthernetMediaOptions: CFString
@available(OSX 10.2, *)
let kSCPropNetEthernetMTU: CFString
@available(OSX 10.1, *)
let kSCPropNetInterfaceDeviceName: CFString
@available(OSX 10.1, *)
let kSCPropNetInterfaceHardware: CFString
@available(OSX 10.1, *)
let kSCPropNetInterfaceType: CFString
@available(OSX 10.1, *)
let kSCPropNetInterfaceSubType: CFString
@available(OSX 10.2, *)
let kSCPropNetInterfaceSupportsModemOnHold: CFString
@available(OSX 10.1, *)
let kSCValNetInterfaceTypeEthernet: CFString
@available(OSX 10.3, *)
let kSCValNetInterfaceTypeFireWire: CFString
@available(OSX 10.1, *)
let kSCValNetInterfaceTypePPP: CFString
@available(OSX 10.3, *)
let kSCValNetInterfaceType6to4: CFString
@available(OSX 10.6, *)
let kSCValNetInterfaceTypeIPSec: CFString
@available(OSX 10.1, *)
let kSCValNetInterfaceSubTypePPPoE: CFString
@available(OSX 10.1, *)
let kSCValNetInterfaceSubTypePPPSerial: CFString
@available(OSX 10.2, *)
let kSCValNetInterfaceSubTypePPTP: CFString
@available(OSX 10.3, *)
let kSCValNetInterfaceSubTypeL2TP: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecAuthenticationMethod: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecLocalCertificate: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecLocalIdentifier: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecLocalIdentifierType: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecSharedSecret: CFString
@available(OSX 10.5, *)
let kSCPropNetIPSecSharedSecretEncryption: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecConnectTime: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecRemoteAddress: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecStatus: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecXAuthEnabled: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecXAuthName: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecXAuthPassword: CFString
@available(OSX 10.6, *)
let kSCPropNetIPSecXAuthPasswordEncryption: CFString
@available(OSX 10.5, *)
let kSCValNetIPSecAuthenticationMethodSharedSecret: CFString
@available(OSX 10.5, *)
let kSCValNetIPSecAuthenticationMethodCertificate: CFString
@available(OSX 10.5, *)
let kSCValNetIPSecAuthenticationMethodHybrid: CFString
@available(OSX 10.5, *)
let kSCValNetIPSecLocalIdentifierTypeKeyID: CFString
@available(OSX 10.5, *)
let kSCValNetIPSecSharedSecretEncryptionKeychain: CFString
@available(OSX 10.6, *)
let kSCValNetIPSecXAuthPasswordEncryptionKeychain: CFString
@available(OSX 10.6, *)
let kSCValNetIPSecXAuthPasswordEncryptionPrompt: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4Addresses: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4ConfigMethod: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4DHCPClientID: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4Router: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4SubnetMasks: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4DestAddresses: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv4BroadcastAddresses: CFString
@available(OSX 10.6, *)
let kSCValNetIPv4ConfigMethodAutomatic: CFString
@available(OSX 10.1, *)
let kSCValNetIPv4ConfigMethodBOOTP: CFString
@available(OSX 10.1, *)
let kSCValNetIPv4ConfigMethodDHCP: CFString
@available(OSX 10.1, *)
let kSCValNetIPv4ConfigMethodINFORM: CFString
@available(OSX 10.2, *)
let kSCValNetIPv4ConfigMethodLinkLocal: CFString
@available(OSX 10.1, *)
let kSCValNetIPv4ConfigMethodManual: CFString
@available(OSX 10.1, *)
let kSCValNetIPv4ConfigMethodPPP: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv6Addresses: CFString
@available(OSX 10.1, *)
let kSCPropNetIPv6ConfigMethod: CFString
@available(OSX 10.3, *)
let kSCPropNetIPv6DestAddresses: CFString
@available(OSX 10.3, *)
let kSCPropNetIPv6Flags: CFString
@available(OSX 10.3, *)
let kSCPropNetIPv6PrefixLength: CFString
@available(OSX 10.3, *)
let kSCPropNetIPv6Router: CFString
@available(OSX 10.3, *)
let kSCValNetIPv6ConfigMethodAutomatic: CFString
@available(OSX 10.7, *)
let kSCValNetIPv6ConfigMethodLinkLocal: CFString
@available(OSX 10.3, *)
let kSCValNetIPv6ConfigMethodManual: CFString
@available(OSX 10.3, *)
let kSCValNetIPv6ConfigMethodRouterAdvertisement: CFString
@available(OSX 10.3, *)
let kSCValNetIPv6ConfigMethod6to4: CFString
@available(OSX 10.3, *)
let kSCPropNet6to4Relay: CFString
@available(OSX 10.1, *)
let kSCPropNetLinkActive: CFString
@available(OSX 10.2, *)
let kSCPropNetLinkDetaching: CFString
@available(OSX 10.5, *)
let kSCPropNetModemAccessPointName: CFString
@available(OSX 10.5, *)
let kSCPropNetModemConnectionPersonality: CFString
@available(OSX 10.1, *)
let kSCPropNetModemConnectionScript: CFString
@available(OSX 10.2, *)
let kSCPropNetModemConnectSpeed: CFString
@available(OSX 10.1, *)
let kSCPropNetModemDataCompression: CFString
@available(OSX 10.5, *)
let kSCPropNetModemDeviceContextID: CFString
@available(OSX 10.5, *)
let kSCPropNetModemDeviceModel: CFString
@available(OSX 10.5, *)
let kSCPropNetModemDeviceVendor: CFString
@available(OSX 10.1, *)
let kSCPropNetModemDialMode: CFString
@available(OSX 10.1, *)
let kSCPropNetModemErrorCorrection: CFString
@available(OSX 10.2, *)
let kSCPropNetModemHoldCallWaitingAudibleAlert: CFString
@available(OSX 10.2, *)
let kSCPropNetModemHoldDisconnectOnAnswer: CFString
@available(OSX 10.2, *)
let kSCPropNetModemHoldEnabled: CFString
@available(OSX 10.2, *)
let kSCPropNetModemHoldReminder: CFString
@available(OSX 10.2, *)
let kSCPropNetModemHoldReminderTime: CFString
@available(OSX 10.2, *)
let kSCPropNetModemNote: CFString
@available(OSX 10.1, *)
let kSCPropNetModemPulseDial: CFString
@available(OSX 10.1, *)
let kSCPropNetModemSpeaker: CFString
@available(OSX 10.1, *)
let kSCPropNetModemSpeed: CFString
@available(OSX 10.1, *)
let kSCValNetModemDialModeIgnoreDialTone: CFString
@available(OSX 10.1, *)
let kSCValNetModemDialModeManual: CFString
@available(OSX 10.1, *)
let kSCValNetModemDialModeWaitForDialTone: CFString
@available(OSX 10.3, *)
let kSCPropNetPPPACSPEnabled: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPConnectTime: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPDeviceLastCause: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPDialOnDemand: CFString
@available(OSX 10.4, *)
let kSCPropNetPPPDisconnectOnFastUserSwitch: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPDisconnectOnIdle: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPDisconnectOnIdleTimer: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPDisconnectOnLogout: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPDisconnectOnSleep: CFString
@available(OSX 10.3, *)
let kSCPropNetPPPDisconnectTime: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPIdleReminderTimer: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPIdleReminder: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPLastCause: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLogfile: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPPlugins: CFString
@available(OSX 10.3, *)
let kSCPropNetPPPRetryConnectTime: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPSessionTimer: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPStatus: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPUseSessionTimer: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPVerboseLogging: CFString
@available(OSX 10.3, *)
let kSCPropNetPPPAuthEAPPlugins: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPAuthName: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPAuthPassword: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPAuthPasswordEncryption: CFString
@available(OSX 10.3, *)
let kSCPropNetPPPAuthPrompt: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPAuthProtocol: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthPasswordEncryptionKeychain: CFString
@available(OSX 10.5, *)
let kSCValNetPPPAuthPasswordEncryptionToken: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthPromptBefore: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthPromptAfter: CFString
@available(OSX 10.1, *)
let kSCValNetPPPAuthProtocolCHAP: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthProtocolEAP: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthProtocolMSCHAP1: CFString
@available(OSX 10.3, *)
let kSCValNetPPPAuthProtocolMSCHAP2: CFString
@available(OSX 10.1, *)
let kSCValNetPPPAuthProtocolPAP: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommAlternateRemoteAddress: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommConnectDelay: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommDisplayTerminalWindow: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommRedialCount: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommRedialEnabled: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommRedialInterval: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommRemoteAddress: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPCommTerminalScript: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPCommUseTerminalScript: CFString
@available(OSX 10.2, *)
let kSCPropNetPPPCCPEnabled: CFString
@available(OSX 10.4, *)
let kSCPropNetPPPCCPMPPE40Enabled: CFString
@available(OSX 10.4, *)
let kSCPropNetPPPCCPMPPE128Enabled: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPIPCPCompressionVJ: CFString
@available(OSX 10.4, *)
let kSCPropNetPPPIPCPUsePeerDNS: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPEchoEnabled: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPEchoFailure: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPEchoInterval: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPCompressionACField: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPCompressionPField: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPMRU: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPMTU: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPReceiveACCM: CFString
@available(OSX 10.1, *)
let kSCPropNetPPPLCPTransmitACCM: CFString
@available(OSX 10.3, *)
let kSCPropNetL2TPIPSecSharedSecret: CFString
@available(OSX 10.3, *)
let kSCPropNetL2TPIPSecSharedSecretEncryption: CFString
@available(OSX 10.3, *)
let kSCPropNetL2TPTransport: CFString
@available(OSX 10.3, *)
let kSCValNetL2TPIPSecSharedSecretEncryptionKeychain: CFString
@available(OSX 10.3, *)
let kSCValNetL2TPTransportIP: CFString
@available(OSX 10.3, *)
let kSCValNetL2TPTransportIPSec: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesExceptionsList: CFString
@available(OSX 10.4, *)
let kSCPropNetProxiesExcludeSimpleHostnames: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesFTPEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesFTPPassive: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesFTPPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesFTPProxy: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesGopherEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesGopherPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesGopherProxy: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPProxy: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPSEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPSPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesHTTPSProxy: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesRTSPEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesRTSPPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesRTSPProxy: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesSOCKSEnable: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesSOCKSPort: CFString
@available(OSX 10.1, *)
let kSCPropNetProxiesSOCKSProxy: CFString
@available(OSX 10.4, *)
let kSCPropNetProxiesProxyAutoConfigEnable: CFString
@available(OSX 10.7, *)
let kSCPropNetProxiesProxyAutoConfigJavaScript: CFString
@available(OSX 10.4, *)
let kSCPropNetProxiesProxyAutoConfigURLString: CFString
@available(OSX 10.4, *)
let kSCPropNetProxiesProxyAutoDiscoveryEnable: CFString
@available(OSX 10.5, *)
let kSCPropNetSMBNetBIOSName: CFString
@available(OSX 10.5, *)
let kSCPropNetSMBNetBIOSNodeType: CFString
@available(OSX 10.5, *)
let kSCPropNetSMBWINSAddresses: CFString
@available(OSX 10.5, *)
let kSCPropNetSMBWorkgroup: CFString
@available(OSX 10.5, *)
let kSCValNetSMBNetBIOSNodeTypeBroadcast: CFString
@available(OSX 10.5, *)
let kSCValNetSMBNetBIOSNodeTypePeer: CFString
@available(OSX 10.5, *)
let kSCValNetSMBNetBIOSNodeTypeMixed: CFString
@available(OSX 10.5, *)
let kSCValNetSMBNetBIOSNodeTypeHybrid: CFString
@available(OSX 10.1, *)
let kSCEntUsersConsoleUser: CFString
@available(OSX 10.1, *)
let kSCPropSystemComputerName: CFString
@available(OSX 10.1, *)
let kSCPropSystemComputerNameEncoding: CFString
@available(OSX 10.1, *)
let kSCDynamicStoreDomainFile: CFString
@available(OSX 10.1, *)
let kSCDynamicStoreDomainPlugin: CFString
@available(OSX 10.1, *)
let kSCDynamicStoreDomainSetup: CFString
@available(OSX 10.1, *)
let kSCDynamicStoreDomainState: CFString
@available(OSX 10.1, *)
let kSCDynamicStoreDomainPrefs: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropSetupCurrentSet: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropSetupLastUpdated: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropNetInterfaces: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropNetPrimaryInterface: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropNetPrimaryService: CFString
@available(OSX 10.1, *)
let kSCDynamicStorePropNetServiceIDs: CFString
