
struct BluetoothCompanyIdentifers : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothCompanyIdentiferEricssonTechnologyLicensing: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferNokiaMobilePhones: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferIntel: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferIBM: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferToshiba: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentifer3Com: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMicrosoft: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferLucent: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMotorola: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferInfineonTechnologiesAG: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferCambridgeSiliconRadio: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSiliconWave: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferDigianswerAS: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTexasInstruments: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferParthusTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferBroadcom: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMitelSemiconductor: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferWidcomm: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferZeevo: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAtmel: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMistubishiElectric: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferRTXTelecom: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferKCTechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferNewlogic: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTransilica: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferRohdeandSchwarz: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTTPCom: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSigniaTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferConexantSystems: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferQualcomm: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferInventel: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAVMBerlin: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferBandspeed: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMansella: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferNEC: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferWavePlusTechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAlcatel: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferPhilipsSemiconductor: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferCTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferOpenInterface: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferRFCMicroDevices: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferHitachi: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSymbolTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTenovis: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMacronixInternational: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferGCTSemiconductor: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferNorwoodSystems: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMewTelTechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSTMicroelectronics: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSynopsys: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferRedMCommunications: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferCommil: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferCATC: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferEclipse: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferRenesasTechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMobilian: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTerax: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferIntegratedSystemSolution: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMatsushitaElectricIndustrial: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferGennum: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferResearchInMotion: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferIPextreme: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSystemsAndChips: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferBluetoothSIG: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSeikoEpson: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferIntegratedSiliconSolution: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferCONWISETechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferParrotSA: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSocketCommunications: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAtherosCommunications: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMediaTek: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferBluegiga: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferMarvellTechnologyGroup: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentifer3DSP: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAccelSemiconductor: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferContinentialAutomotiveSystems: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferApple: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferStaccatoCommunications: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAvagoTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferAPT: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSiRFTechnology: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferTZeroTechnologies: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferJandM: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferFree2Move: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentifer3DiJoy: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferPlantronics: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferSonyEricssonMobileCommunications: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferHarmonInternational: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferVisio: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferNordicSemiconductor: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferEMMicroElectronicMarin: BluetoothCompanyIdentifers { get }
var kBluetoothCompanyIdentiferInteropIdentifier: BluetoothCompanyIdentifers { get }
var kBluetoothServiceClassMajorLimitedDiscoverableMode: Int { get }
var kBluetoothServiceClassMajorReserved1: Int { get }
var kBluetoothServiceClassMajorReserved2: Int { get }
var kBluetoothServiceClassMajorPositioning: Int { get }
var kBluetoothServiceClassMajorNetworking: Int { get }
var kBluetoothServiceClassMajorRendering: Int { get }
var kBluetoothServiceClassMajorCapturing: Int { get }
var kBluetoothServiceClassMajorObjectTransfer: Int { get }
var kBluetoothServiceClassMajorAudio: Int { get }
var kBluetoothServiceClassMajorTelephony: Int { get }
var kBluetoothServiceClassMajorInformation: Int { get }
var kBluetoothServiceClassMajorAny: Int { get }
var kBluetoothServiceClassMajorNone: Int { get }
var kBluetoothServiceClassMajorEnd: Int { get }
var kBluetoothDeviceClassMajorMiscellaneous: Int { get }
var kBluetoothDeviceClassMajorComputer: Int { get }
var kBluetoothDeviceClassMajorPhone: Int { get }
var kBluetoothDeviceClassMajorLANAccessPoint: Int { get }
var kBluetoothDeviceClassMajorAudio: Int { get }
var kBluetoothDeviceClassMajorPeripheral: Int { get }
var kBluetoothDeviceClassMajorImaging: Int { get }
var kBluetoothDeviceClassMajorWearable: Int { get }
var kBluetoothDeviceClassMajorToy: Int { get }
var kBluetoothDeviceClassMajorHealth: Int { get }
var kBluetoothDeviceClassMajorUnclassified: Int { get }
var kBluetoothDeviceClassMajorAny: Int { get }
var kBluetoothDeviceClassMajorNone: Int { get }
var kBluetoothDeviceClassMajorEnd: Int { get }
var kBluetoothDeviceClassMinorComputerUnclassified: Int { get }
var kBluetoothDeviceClassMinorComputerDesktopWorkstation: Int { get }
var kBluetoothDeviceClassMinorComputerServer: Int { get }
var kBluetoothDeviceClassMinorComputerLaptop: Int { get }
var kBluetoothDeviceClassMinorComputerHandheld: Int { get }
var kBluetoothDeviceClassMinorComputerPalmSized: Int { get }
var kBluetoothDeviceClassMinorComputerWearable: Int { get }
var kBluetoothDeviceClassMinorPhoneUnclassified: Int { get }
var kBluetoothDeviceClassMinorPhoneCellular: Int { get }
var kBluetoothDeviceClassMinorPhoneCordless: Int { get }
var kBluetoothDeviceClassMinorPhoneSmartPhone: Int { get }
var kBluetoothDeviceClassMinorPhoneWiredModemOrVoiceGateway: Int { get }
var kBluetoothDeviceClassMinorPhoneCommonISDNAccess: Int { get }
var kBluetoothDeviceClassMinorAudioUnclassified: Int { get }
var kBluetoothDeviceClassMinorAudioHeadset: Int { get }
var kBluetoothDeviceClassMinorAudioHandsFree: Int { get }
var kBluetoothDeviceClassMinorAudioReserved1: Int { get }
var kBluetoothDeviceClassMinorAudioMicrophone: Int { get }
var kBluetoothDeviceClassMinorAudioLoudspeaker: Int { get }
var kBluetoothDeviceClassMinorAudioHeadphones: Int { get }
var kBluetoothDeviceClassMinorAudioPortable: Int { get }
var kBluetoothDeviceClassMinorAudioCar: Int { get }
var kBluetoothDeviceClassMinorAudioSetTopBox: Int { get }
var kBluetoothDeviceClassMinorAudioHiFi: Int { get }
var kBluetoothDeviceClassMinorAudioVCR: Int { get }
var kBluetoothDeviceClassMinorAudioVideoCamera: Int { get }
var kBluetoothDeviceClassMinorAudioCamcorder: Int { get }
var kBluetoothDeviceClassMinorAudioVideoMonitor: Int { get }
var kBluetoothDeviceClassMinorAudioVideoDisplayAndLoudspeaker: Int { get }
var kBluetoothDeviceClassMinorAudioVideoConferencing: Int { get }
var kBluetoothDeviceClassMinorAudioReserved2: Int { get }
var kBluetoothDeviceClassMinorAudioGamingToy: Int { get }
var kBluetoothDeviceClassMinorPeripheral1Keyboard: Int { get }
var kBluetoothDeviceClassMinorPeripheral1Pointing: Int { get }
var kBluetoothDeviceClassMinorPeripheral1Combo: Int { get }
var kBluetoothDeviceClassMinorPeripheral2Unclassified: Int { get }
var kBluetoothDeviceClassMinorPeripheral2Joystick: Int { get }
var kBluetoothDeviceClassMinorPeripheral2Gamepad: Int { get }
var kBluetoothDeviceClassMinorPeripheral2RemoteControl: Int { get }
var kBluetoothDeviceClassMinorPeripheral2SensingDevice: Int { get }
var kBluetoothDeviceClassMinorPeripheral2DigitizerTablet: Int { get }
var kBluetoothDeviceClassMinorPeripheral2CardReader: Int { get }
var kBluetoothDeviceClassMinorPeripheral2DigitalPen: Int { get }
var kBluetoothDeviceClassMinorPeripheral2HandheldScanner: Int { get }
var kBluetoothDeviceClassMinorPeripheral2GesturalInputDevice: Int { get }
var kBluetoothDeviceClassMinorPeripheral2AnyPointing: Int { get }
var kBluetoothDeviceClassMinorImaging1Display: Int { get }
var kBluetoothDeviceClassMinorImaging1Camera: Int { get }
var kBluetoothDeviceClassMinorImaging1Scanner: Int { get }
var kBluetoothDeviceClassMinorImaging1Printer: Int { get }
var kBluetoothDeviceClassMinorImaging2Unclassified: Int { get }
var kBluetoothDeviceClassMinorWearableWristWatch: Int { get }
var kBluetoothDeviceClassMinorWearablePager: Int { get }
var kBluetoothDeviceClassMinorWearableJacket: Int { get }
var kBluetoothDeviceClassMinorWearableHelmet: Int { get }
var kBluetoothDeviceClassMinorWearableGlasses: Int { get }
var kBluetoothDeviceClassMinorToyRobot: Int { get }
var kBluetoothDeviceClassMinorToyVehicle: Int { get }
var kBluetoothDeviceClassMinorToyDollActionFigure: Int { get }
var kBluetoothDeviceClassMinorToyController: Int { get }
var kBluetoothDeviceClassMinorToyGame: Int { get }
var kBluetoothDeviceClassMinorHealthUndefined: Int { get }
var kBluetoothDeviceClassMinorHealthBloodPressureMonitor: Int { get }
var kBluetoothDeviceClassMinorHealthThermometer: Int { get }
var kBluetoothDeviceClassMinorHealthScale: Int { get }
var kBluetoothDeviceClassMinorHealthGlucoseMeter: Int { get }
var kBluetoothDeviceClassMinorHealthPulseOximeter: Int { get }
var kBluetoothDeviceClassMinorHealthHeartRateMonitor: Int { get }
var kBluetoothDeviceClassMinorHealthDataDisplay: Int { get }
var kBluetoothDeviceClassMinorAny: Int { get }
var kBluetoothDeviceClassMinorNone: Int { get }
var kBluetoothDeviceClassMinorEnd: Int { get }
var kBluetoothGAPAppearanceUnknown: Int { get }
var kBluetoothGAPAppearanceGenericPhone: Int { get }
var kBluetoothGAPAppearanceGenericComputer: Int { get }
var kBluetoothGAPAppearanceGenericWatch: Int { get }
var kBluetoothGAPAppearanceGenericClock: Int { get }
var kBluetoothGAPAppearanceGenericDisplay: Int { get }
var kBluetoothGAPAppearanceGenericRemoteControl: Int { get }
var kBluetoothGAPAppearanceGenericEyeGlasses: Int { get }
var kBluetoothGAPAppearanceGenericTag: Int { get }
var kBluetoothGAPAppearanceGenericKeyring: Int { get }
var kBluetoothGAPAppearanceGenericMediaPlayer: Int { get }
var kBluetoothGAPAppearanceGenericBarcodeScanner: Int { get }
var kBluetoothGAPAppearanceGenericThermometer: Int { get }
var kBluetoothGAPAppearanceGenericHeartrateSensor: Int { get }
var kBluetoothGAPAppearanceGenericBloodPressure: Int { get }
var kBluetoothGAPAppearanceGenericHumanInterfaceDevice: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceKeyboard: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceMouse: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceJoystick: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceGamepad: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceDigitizerTablet: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceCardReader: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceDigitalPen: Int { get }
var kBluetoothGAPAppearanceHumanInterfaceDeviceBarcodeScanner: Int { get }
var kBluetoothGAPAppearanceGenericGlucoseMeter: Int { get }
var kBluetoothGAPAppearanceGenericRunningWalkingSensor: Int { get }
var kBluetoothGAPAppearanceGenericCycling: Int { get }
var kBluetoothL2CAPPSMSDP: Int { get }
var kBluetoothL2CAPPSMRFCOMM: Int { get }
var kBluetoothL2CAPPSMTCS_BIN: Int { get }
var kBluetoothL2CAPPSMTCS_BIN_Cordless: Int { get }
var kBluetoothL2CAPPSMBNEP: Int { get }
var kBluetoothL2CAPPSMHIDControl: Int { get }
var kBluetoothL2CAPPSMHIDInterrupt: Int { get }
var kBluetoothL2CAPPSMAVCTP: Int { get }
var kBluetoothL2CAPPSMAVDTP: Int { get }
var kBluetoothL2CAPPSMAVCTP_Browsing: Int { get }
var kBluetoothL2CAPPSMUID_C_Plane: Int { get }
var kBluetoothL2CAPPSMATT: Int { get }
var kBluetoothL2CAPPSMReservedStart: Int { get }
var kBluetoothL2CAPPSMReservedEnd: Int { get }
var kBluetoothL2CAPPSMDynamicStart: Int { get }
var kBluetoothL2CAPPSMD2D: Int { get }
var kBluetoothL2CAPPSMDynamicEnd: Int { get }
var kBluetoothL2CAPPSMNone: Int { get }
var kBluetoothSDPUUID16Base: Int { get }
var kBluetoothSDPUUID16SDP: Int { get }
var kBluetoothSDPUUID16UDP: Int { get }
var kBluetoothSDPUUID16RFCOMM: Int { get }
var kBluetoothSDPUUID16TCP: Int { get }
var kBluetoothSDPUUID16TCSBIN: Int { get }
var kBluetoothSDPUUID16TCSAT: Int { get }
var kBluetoothSDPUUID16OBEX: Int { get }
var kBluetoothSDPUUID16IP: Int { get }
var kBluetoothSDPUUID16FTP: Int { get }
var kBluetoothSDPUUID16HTTP: Int { get }
var kBluetoothSDPUUID16WSP: Int { get }
var kBluetoothSDPUUID16BNEP: Int { get }
var kBluetoothSDPUUID16UPNP: Int { get }
var kBluetoothSDPUUID16HIDP: Int { get }
var kBluetoothSDPUUID16HardcopyControlChannel: Int { get }
var kBluetoothSDPUUID16HardcopyDataChannel: Int { get }
var kBluetoothSDPUUID16HardcopyNotification: Int { get }
var kBluetoothSDPUUID16AVCTP: Int { get }
var kBluetoothSDPUUID16AVDTP: Int { get }
var kBluetoothSDPUUID16CMPT: Int { get }
var kBluetoothSDPUUID16UDI_C_Plane: Int { get }
var kBluetoothSDPUUID16MCAPControlChannel: Int { get }
var kBluetoothSDPUUID16MCAPDataChannel: Int { get }
var kBluetoothSDPUUID16L2CAP: Int { get }
struct SDPServiceClasses : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothSDPUUID16ServiceClassServiceDiscoveryServer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassBrowseGroupDescriptor: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPublicBrowseGroup: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassSerialPort: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassLANAccessUsingPPP: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassDialupNetworking: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassIrMCSync: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassOBEXObjectPush: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassOBEXFileTransfer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassIrMCSyncCommand: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHeadset: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassCordlessTelephony: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAudioSource: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAudioSink: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAVRemoteControlTarget: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAdvancedAudioDistribution: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAVRemoteControl: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAVRemoteControlController: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassIntercom: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassFax: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHeadsetAudioGateway: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassWAP: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassWAPClient: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPANU: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassNAP: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGN: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassDirectPrinting: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassReferencePrinting: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassImaging: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassImagingResponder: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassImagingAutomaticArchive: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassImagingReferencedObjects: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHandsFree: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHandsFreeAudioGateway: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassDirectPrintingReferenceObjectsService: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassReflectedUI: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassBasicPrinting: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPrintingStatus: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHumanInterfaceDeviceService: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHardcopyCableReplacement: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHCR_Print: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHCR_Scan: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassCommonISDNAccess: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassVideoConferencingGW: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassUDI_MT: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassUDI_TA: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassAudioVideo: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassSIM_Access: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPhonebookAccess_PCE: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPhonebookAccess_PSE: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPhonebookAccess: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHeadset_HS: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassMessageAccessServer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassMessageNotificationServer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassMessageAccessProfile: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGlobalNavigationSatelliteSystem: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGlobalNavigationSatelliteSystemServer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassPnPInformation: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGenericNetworking: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGenericFileTransfer: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGenericAudio: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassGenericTelephony: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassVideoSource: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassVideoSink: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassVideoDistribution: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHealthDevice: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHealthDeviceSource: SDPServiceClasses { get }
var kBluetoothSDPUUID16ServiceClassHealthDeviceSink: SDPServiceClasses { get }
struct SDPAttributeIdentifierCodes : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothSDPAttributeIdentifierServiceRecordHandle: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceClassIDList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceRecordState: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceID: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierProtocolDescriptorList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierBrowseGroupList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierLanguageBaseAttributeIDList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceInfoTimeToLive: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceAvailability: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierBluetoothProfileDescriptorList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierDocumentationURL: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierClientExecutableURL: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierIconURL: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierAdditionalProtocolsDescriptorList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierVersionNumberList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceDatabaseState: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierGroupID: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierIPSubnet: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDReleaseNumber: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDParserVersion: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDDeviceSubclass: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDCountryCode: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDVirtualCable: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDReconnectInitiate: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDDescriptorList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDLangIDBaseList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDSDPDisable: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDBatteryPower: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDRemoteWake: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDProfileVersion: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDSupervisionTimeout: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDNormallyConnectable: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDBootDevice: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDSSRHostMaxLatency: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHIDSSRHostMinTimeout: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceVersion: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierExternalNetwork: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierNetwork: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSupportedDataStoresList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierFaxClass1Support: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierRemoteAudioVolumeControl: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierFaxClass2_0Support: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSupporterFormatsList: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierFaxClass2Support: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierAudioFeedbackSupport: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierNetworkAddress: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierWAPGateway: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierHomepageURL: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierWAPStackType: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSecurityDescription: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierNetAccessType: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierMaxNetAccessRate: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSupportedCapabilities: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSupportedFeatures: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierSupportedFunctions: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierTotalImagingDataCapacity: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceName: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierServiceDescription: SDPAttributeIdentifierCodes { get }
var kBluetoothSDPAttributeIdentifierProviderName: SDPAttributeIdentifierCodes { get }
struct SDPAttributeDeviceIdentificationRecord : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothSDPAttributeDeviceIdentifierServiceDescription: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierDocumentationURL: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierClientExecutableURL: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierSpecificationID: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierVendorID: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierProductID: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierVersion: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierPrimaryRecord: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierVendorIDSource: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierReservedRangeStart: SDPAttributeDeviceIdentificationRecord { get }
var kBluetoothSDPAttributeDeviceIdentifierReservedRangeEnd: SDPAttributeDeviceIdentificationRecord { get }
struct ProtocolParameters : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothSDPProtocolParameterL2CAPPSM: ProtocolParameters { get }
var kBluetoothSDPProtocolParameterRFCOMMChannel: ProtocolParameters { get }
var kBluetoothSDPProtocolParameterTCPPort: ProtocolParameters { get }
var kBluetoothSDPProtocolParameterUDPPort: ProtocolParameters { get }
var kBluetoothSDPProtocolParameterBNEPVersion: ProtocolParameters { get }
var kBluetoothSDPProtocolParameterBNEPSupportedNetworkPacketTypeList: ProtocolParameters { get }
struct BluetoothHCIExtendedInquiryResponseDataTypes : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothHCIExtendedInquiryResponseDataTypeFlags: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsWithMoreAvailable: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType16BitServiceClassUUIDsCompleteList: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsWithMoreAvailable: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType32BitServiceClassUUIDsCompleteList: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsWithMoreAvailable: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataType128BitServiceClassUUIDsCompleteList: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeShortenedLocalName: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeCompleteLocalName: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeTransmitPowerLevel: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBClassOfDevice: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingHashC: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSSPOOBSimplePairingRandomizerR: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeDeviceID: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSecurityManagerTKValue: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSecurityManagerOOBFlags: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeSlaveConnectionIntervalRange: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeServiceSolicitation16BitUUIDs: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeServiceSolicitation128BitUUIDs: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeServiceData: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypePublicTargetAddress: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeRandomTargetAddress: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeAppearance: BluetoothHCIExtendedInquiryResponseDataTypes { get }
var kBluetoothHCIExtendedInquiryResponseDataTypeManufacturerSpecificData: BluetoothHCIExtendedInquiryResponseDataTypes { get }
struct BluetoothHCIVersions : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothHCIVersionCoreSpecification1_0b: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification1_1: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification1_2: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification2_0EDR: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification2_1EDR: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification3_0HS: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification4_0: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification4_1: BluetoothHCIVersions { get }
var kBluetoothHCIVersionCoreSpecification4_2: BluetoothHCIVersions { get }
struct BluetoothLMPVersions : RawRepresentable, Equatable {
  init(_ rawValue: UInt32)
  init(rawValue rawValue: UInt32)
  var rawValue: UInt32
}
var kBluetoothLMPVersionCoreSpecification1_0b: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification1_1: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification1_2: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification2_0EDR: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification2_1EDR: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification3_0HS: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification4_0: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification4_1: BluetoothLMPVersions { get }
var kBluetoothLMPVersionCoreSpecification4_2: BluetoothLMPVersions { get }
