#ifndef TEST_INTEROP_CXX_MODULES_INPUTS_BRIDGE_HEADER_H
#define TEST_INTEROP_CXX_MODULES_INPUTS_BRIDGE_HEADER_H

namespace Namespace {
struct InNamespace {};
}

#endif // TEST_INTEROP_CXX_MODULES_INPUTS_BRIDGE_HEADER_H
