
@available(OSX 10.4, *)
let kCGImagePropertyTIFFDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGIFDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyRawDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyCIFFDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerMinoltaDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerFujiDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerOlympusDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerPentaxDictionary: CFString
@available(OSX 10.4, *)
let kCGImageProperty8BIMDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGDictionary: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxDictionary: CFString
@available(OSX 10.9, *)
let kCGImagePropertyOpenEXRDictionary: CFString
@available(OSX 10.10, *)
let kCGImagePropertyMakerAppleDictionary: CFString
@available(OSX 10.4, *)
let kCGImagePropertyFileSize: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPixelHeight: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPixelWidth: CFString
@available(OSX 10.4, *)
let kCGImagePropertyDPIHeight: CFString
@available(OSX 10.4, *)
let kCGImagePropertyDPIWidth: CFString
@available(OSX 10.4, *)
let kCGImagePropertyDepth: CFString
@available(OSX 10.4, *)
let kCGImagePropertyOrientation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIsFloat: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIsIndexed: CFString
@available(OSX 10.4, *)
let kCGImagePropertyHasAlpha: CFString
@available(OSX 10.4, *)
let kCGImagePropertyColorModel: CFString
@available(OSX 10.4, *)
let kCGImagePropertyProfileName: CFString
@available(OSX 10.4, *)
let kCGImagePropertyColorModelRGB: CFString
@available(OSX 10.4, *)
let kCGImagePropertyColorModelGray: CFString
@available(OSX 10.4, *)
let kCGImagePropertyColorModelCMYK: CFString
@available(OSX 10.4, *)
let kCGImagePropertyColorModelLab: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFCompression: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFPhotometricInterpretation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFDocumentName: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFImageDescription: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFMake: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFModel: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFOrientation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFXResolution: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFYResolution: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFResolutionUnit: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFSoftware: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFTransferFunction: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFDateTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFArtist: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFHostComputer: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFCopyright: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFWhitePoint: CFString
@available(OSX 10.4, *)
let kCGImagePropertyTIFFPrimaryChromaticities: CFString
@available(OSX 10.11, *)
let kCGImagePropertyTIFFTileWidth: CFString
@available(OSX 10.11, *)
let kCGImagePropertyTIFFTileLength: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFVersion: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFXDensity: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFYDensity: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFDensityUnit: CFString
@available(OSX 10.4, *)
let kCGImagePropertyJFIFIsProgressive: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifExposureTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFNumber: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifExposureProgram: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSpectralSensitivity: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifISOSpeedRatings: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifOECF: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifSensitivityType: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifStandardOutputSensitivity: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifRecommendedExposureIndex: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifISOSpeed: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifISOSpeedLatitudeyyy: CFString
@available(OSX 10.9, *)
let kCGImagePropertyExifISOSpeedLatitudezzz: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifVersion: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifDateTimeOriginal: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifDateTimeDigitized: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifComponentsConfiguration: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifCompressedBitsPerPixel: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifShutterSpeedValue: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifApertureValue: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifBrightnessValue: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifExposureBiasValue: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifMaxApertureValue: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubjectDistance: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifMeteringMode: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifLightSource: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFlash: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFocalLength: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubjectArea: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifMakerNote: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifUserComment: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubsecTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubsecTimeOriginal: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubsecTimeDigitized: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFlashPixVersion: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifColorSpace: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifPixelXDimension: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifPixelYDimension: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifRelatedSoundFile: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFlashEnergy: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSpatialFrequencyResponse: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFocalPlaneXResolution: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFocalPlaneYResolution: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFocalPlaneResolutionUnit: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubjectLocation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifExposureIndex: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSensingMethod: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFileSource: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSceneType: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifCFAPattern: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifCustomRendered: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifExposureMode: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifWhiteBalance: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifDigitalZoomRatio: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifFocalLenIn35mmFilm: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSceneCaptureType: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifGainControl: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifContrast: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSaturation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSharpness: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifDeviceSettingDescription: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubjectDistRange: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifImageUniqueID: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifCameraOwnerName: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifBodySerialNumber: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifLensSpecification: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifLensMake: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifLensModel: CFString
@available(OSX 10.7, *)
let kCGImagePropertyExifLensSerialNumber: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifGamma: CFString
@available(OSX 10.4, *)
let kCGImagePropertyExifSubsecTimeOrginal: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxLensInfo: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxLensModel: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxLensID: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxLensSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxImageNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxFlashCompensation: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxOwnerName: CFString
@available(OSX 10.5, *)
let kCGImagePropertyExifAuxFirmware: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGIFLoopCount: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGIFDelayTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGIFImageColorMap: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGIFHasGlobalColorMap: CFString
@available(OSX 10.7, *)
let kCGImagePropertyGIFUnclampedDelayTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGGamma: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGInterlaceType: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGXPixelsPerMeter: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGYPixelsPerMeter: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGsRGBIntent: CFString
@available(OSX 10.4, *)
let kCGImagePropertyPNGChromaticities: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGAuthor: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGCopyright: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGCreationTime: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGDescription: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGModificationTime: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGSoftware: CFString
@available(OSX 10.7, *)
let kCGImagePropertyPNGTitle: CFString
@available(OSX 10.10, *)
let kCGImagePropertyAPNGLoopCount: CFString
@available(OSX 10.10, *)
let kCGImagePropertyAPNGDelayTime: CFString
@available(OSX 10.10, *)
let kCGImagePropertyAPNGUnclampedDelayTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSVersion: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSLatitudeRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSLatitude: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSLongitudeRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSLongitude: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSAltitudeRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSAltitude: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSTimeStamp: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSSatellites: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSStatus: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSMeasureMode: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDOP: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSSpeedRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSSpeed: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSTrackRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSTrack: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSImgDirectionRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSImgDirection: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSMapDatum: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestLatitudeRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestLatitude: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestLongitudeRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestLongitude: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestBearingRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestBearing: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestDistanceRef: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDestDistance: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSProcessingMethod: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSAreaInformation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDateStamp: CFString
@available(OSX 10.4, *)
let kCGImagePropertyGPSDifferental: CFString
@available(OSX 10.10, *)
let kCGImagePropertyGPSHPositioningError: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCObjectTypeReference: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCObjectAttributeReference: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCObjectName: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCEditStatus: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCEditorialUpdate: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCUrgency: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCSubjectReference: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCategory: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCSupplementalCategory: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCFixtureIdentifier: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCKeywords: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCContentLocationCode: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCContentLocationName: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCReleaseDate: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCReleaseTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCExpirationDate: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCExpirationTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCSpecialInstructions: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCActionAdvised: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCReferenceService: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCReferenceDate: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCReferenceNumber: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCDateCreated: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCTimeCreated: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCDigitalCreationDate: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCDigitalCreationTime: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCOriginatingProgram: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCProgramVersion: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCObjectCycle: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCByline: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCBylineTitle: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCity: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCSubLocation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCProvinceState: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCountryPrimaryLocationCode: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCountryPrimaryLocationName: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCOriginalTransmissionReference: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCHeadline: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCredit: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCSource: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCopyrightNotice: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCContact: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCCaptionAbstract: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCWriterEditor: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCImageType: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCImageOrientation: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCLanguageIdentifier: CFString
@available(OSX 10.4, *)
let kCGImagePropertyIPTCStarRating: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCCreatorContactInfo: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCRightsUsageTerms: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCScene: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoCity: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoCountry: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoAddress: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoPostalCode: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoStateProvince: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoEmails: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoPhones: CFString
@available(OSX 10.6, *)
let kCGImagePropertyIPTCContactInfoWebURLs: CFString
@available(OSX 10.4, *)
let kCGImageProperty8BIMLayerNames: CFString
@available(OSX 10.10, *)
let kCGImageProperty8BIMVersion: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGVersion: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGBackwardVersion: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGUniqueCameraModel: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGLocalizedCameraModel: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGCameraSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyDNGLensInfo: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFDescription: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFFirmware: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFOwnerName: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFImageName: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFImageFileName: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFReleaseMethod: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFReleaseTiming: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFRecordID: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFSelfTimingTime: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFCameraSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFImageSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFContinuousDrive: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFFocusMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFMeteringMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFShootingMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFLensModel: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFLensMaxMM: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFLensMinMM: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFWhiteBalanceIndex: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFFlashExposureComp: CFString
@available(OSX 10.5, *)
let kCGImagePropertyCIFFMeasuredEV: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonISOSetting: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonColorMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonQuality: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonWhiteBalanceMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonSharpenMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonFocusMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonFlashSetting: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonISOSelection: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonFlashExposureComp: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonImageAdjustment: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonLensAdapter: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonLensType: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonLensInfo: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonFocusDistance: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonDigitalZoom: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonShootingMode: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonCameraSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerNikonShutterCount: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonOwnerName: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonCameraSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonImageSerialNumber: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonFlashExposureComp: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonContinuousDrive: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonLensModel: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonFirmware: CFString
@available(OSX 10.5, *)
let kCGImagePropertyMakerCanonAspectRatioInfo: CFString
@available(OSX 10.9, *)
let kCGImagePropertyOpenEXRAspectRatio: CFString
enum CGImagePropertyOrientation : UInt32 {
  init?(rawValue rawValue: UInt32)
  var rawValue: UInt32 { get }
  case up
  case upMirrored
  case down
  case downMirrored
  case leftMirrored
  case right
  case rightMirrored
  case left
}
@available(OSX 10.11, *)
let kCGImagePropertyPNGCompressionFilter: CFString
var IMAGEIO_PNG_NO_FILTERS: Int32 { get }
var IMAGEIO_PNG_FILTER_NONE: Int32 { get }
var IMAGEIO_PNG_FILTER_SUB: Int32 { get }
var IMAGEIO_PNG_FILTER_UP: Int32 { get }
var IMAGEIO_PNG_FILTER_AVG: Int32 { get }
var IMAGEIO_PNG_FILTER_PAETH: Int32 { get }
