RequirementMachine.pdf:
	pdflatex RequirementMachine
	bibtex RequirementMachine
	pdflatex RequirementMachine
	pdflatex RequirementMachine

clean:
	rm *.aux *.bbl *.blg *.idx *.ilg *.ind *.log *.out *.pdf *.toc

.PHONY: clean
