find_program(SCCACHE_EXECUTABLE sccache)

if(SCCACHE_EXECUTABLE)
  set(CMAKE_C_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}" CACHE FILEPATH "")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}" CACHE FILEPATH "")
  message(STATUS "sccache enabled")
endif()
