
var AGL_VERSION_3_0: Int32 { get }
var AGL_NONE: Int32 { get }
var AGL_ALL_RENDERERS: Int32 { get }
var AGL_BUFFER_SIZE: Int32 { get }
var AGL_LEVEL: Int32 { get }
var AGL_RGBA: Int32 { get }
var AGL_DOUBLEBUFFER: Int32 { get }
var AGL_STEREO: Int32 { get }
var AGL_AUX_BUFFERS: Int32 { get }
var AGL_RED_SIZE: Int32 { get }
var AGL_GREEN_SIZE: Int32 { get }
var AGL_BLUE_SIZE: Int32 { get }
var AGL_ALPHA_SIZE: Int32 { get }
var AGL_DEPTH_SIZE: Int32 { get }
var AGL_STENCIL_SIZE: Int32 { get }
var AGL_ACCUM_RED_SIZE: Int32 { get }
var AGL_ACCUM_GREEN_SIZE: Int32 { get }
var AGL_ACCUM_BLUE_SIZE: Int32 { get }
var AGL_ACCUM_ALPHA_SIZE: Int32 { get }
var AGL_PIXEL_SIZE: Int32 { get }
var AGL_MINIMUM_POLICY: Int32 { get }
var AGL_MAXIMUM_POLICY: Int32 { get }
var AGL_OFFSCREEN: Int32 { get }
var AGL_FULLSCREEN: Int32 { get }
var AGL_SAMPLE_BUFFERS_ARB: Int32 { get }
var AGL_SAMPLES_ARB: Int32 { get }
var AGL_AUX_DEPTH_STENCIL: Int32 { get }
var AGL_COLOR_FLOAT: Int32 { get }
var AGL_MULTISAMPLE: Int32 { get }
var AGL_SUPERSAMPLE: Int32 { get }
var AGL_SAMPLE_ALPHA: Int32 { get }
var AGL_RENDERER_ID: Int32 { get }
var AGL_SINGLE_RENDERER: Int32 { get }
var AGL_NO_RECOVERY: Int32 { get }
var AGL_ACCELERATED: Int32 { get }
var AGL_CLOSEST_POLICY: Int32 { get }
var AGL_ROBUST: Int32 { get }
var AGL_BACKING_STORE: Int32 { get }
var AGL_MP_SAFE: Int32 { get }
var AGL_WINDOW: Int32 { get }
var AGL_MULTISCREEN: Int32 { get }
var AGL_VIRTUAL_SCREEN: Int32 { get }
var AGL_COMPLIANT: Int32 { get }
var AGL_DISPLAY_MASK: Int32 { get }
var AGL_PBUFFER: Int32 { get }
var AGL_REMOTE_PBUFFER: Int32 { get }
var AGL_ALLOW_OFFLINE_RENDERERS: Int32 { get }
var AGL_BUFFER_MODES: Int32 { get }
var AGL_MIN_LEVEL: Int32 { get }
var AGL_MAX_LEVEL: Int32 { get }
var AGL_COLOR_MODES: Int32 { get }
var AGL_ACCUM_MODES: Int32 { get }
var AGL_DEPTH_MODES: Int32 { get }
var AGL_STENCIL_MODES: Int32 { get }
var AGL_MAX_AUX_BUFFERS: Int32 { get }
var AGL_VIDEO_MEMORY: Int32 { get }
var AGL_TEXTURE_MEMORY: Int32 { get }
var AGL_RENDERER_COUNT: Int32 { get }
var AGL_SWAP_RECT: Int32 { get }
var AGL_BUFFER_RECT: Int32 { get }
var AGL_SWAP_LIMIT: Int32 { get }
var AGL_COLORMAP_TRACKING: Int32 { get }
var AGL_COLORMAP_ENTRY: Int32 { get }
var AGL_RASTERIZATION: Int32 { get }
var AGL_SWAP_INTERVAL: Int32 { get }
var AGL_STATE_VALIDATION: Int32 { get }
var AGL_BUFFER_NAME: Int32 { get }
var AGL_ORDER_CONTEXT_TO_FRONT: Int32 { get }
var AGL_CONTEXT_SURFACE_ID: Int32 { get }
var AGL_CONTEXT_DISPLAY_ID: Int32 { get }
var AGL_SURFACE_ORDER: Int32 { get }
var AGL_SURFACE_OPACITY: Int32 { get }
var AGL_CLIP_REGION: Int32 { get }
var AGL_FS_CAPTURE_SINGLE: Int32 { get }
var AGL_SURFACE_BACKING_SIZE: Int32 { get }
var AGL_ENABLE_SURFACE_BACKING_SIZE: Int32 { get }
var AGL_SURFACE_VOLATILE: Int32 { get }
var AGL_FORMAT_CACHE_SIZE: Int32 { get }
var AGL_CLEAR_FORMAT_CACHE: Int32 { get }
var AGL_RETAIN_RENDERERS: Int32 { get }
var AGL_MONOSCOPIC_BIT: Int32 { get }
var AGL_STEREOSCOPIC_BIT: Int32 { get }
var AGL_SINGLEBUFFER_BIT: Int32 { get }
var AGL_DOUBLEBUFFER_BIT: Int32 { get }
var AGL_0_BIT: Int32 { get }
var AGL_1_BIT: Int32 { get }
var AGL_2_BIT: Int32 { get }
var AGL_3_BIT: Int32 { get }
var AGL_4_BIT: Int32 { get }
var AGL_5_BIT: Int32 { get }
var AGL_6_BIT: Int32 { get }
var AGL_8_BIT: Int32 { get }
var AGL_10_BIT: Int32 { get }
var AGL_12_BIT: Int32 { get }
var AGL_16_BIT: Int32 { get }
var AGL_24_BIT: Int32 { get }
var AGL_32_BIT: Int32 { get }
var AGL_48_BIT: Int32 { get }
var AGL_64_BIT: Int32 { get }
var AGL_96_BIT: Int32 { get }
var AGL_128_BIT: Int32 { get }
var AGL_RGB8_BIT: Int32 { get }
var AGL_RGB8_A8_BIT: Int32 { get }
var AGL_BGR233_BIT: Int32 { get }
var AGL_BGR233_A8_BIT: Int32 { get }
var AGL_RGB332_BIT: Int32 { get }
var AGL_RGB332_A8_BIT: Int32 { get }
var AGL_RGB444_BIT: Int32 { get }
var AGL_ARGB4444_BIT: Int32 { get }
var AGL_RGB444_A8_BIT: Int32 { get }
var AGL_RGB555_BIT: Int32 { get }
var AGL_ARGB1555_BIT: Int32 { get }
var AGL_RGB555_A8_BIT: Int32 { get }
var AGL_RGB565_BIT: Int32 { get }
var AGL_RGB565_A8_BIT: Int32 { get }
var AGL_RGB888_BIT: Int32 { get }
var AGL_ARGB8888_BIT: Int32 { get }
var AGL_RGB888_A8_BIT: Int32 { get }
var AGL_RGB101010_BIT: Int32 { get }
var AGL_ARGB2101010_BIT: Int32 { get }
var AGL_RGB101010_A8_BIT: Int32 { get }
var AGL_RGB121212_BIT: Int32 { get }
var AGL_ARGB12121212_BIT: Int32 { get }
var AGL_RGB161616_BIT: Int32 { get }
var AGL_ARGB16161616_BIT: Int32 { get }
var AGL_INDEX8_BIT: Int32 { get }
var AGL_INDEX16_BIT: Int32 { get }
var AGL_RGBFLOAT64_BIT: Int32 { get }
var AGL_RGBAFLOAT64_BIT: Int32 { get }
var AGL_RGBFLOAT128_BIT: Int32 { get }
var AGL_RGBAFLOAT128_BIT: Int32 { get }
var AGL_RGBFLOAT256_BIT: Int32 { get }
var AGL_RGBAFLOAT256_BIT: Int32 { get }
var AGL_NO_ERROR: Int32 { get }
var AGL_BAD_ATTRIBUTE: Int32 { get }
var AGL_BAD_PROPERTY: Int32 { get }
var AGL_BAD_PIXELFMT: Int32 { get }
var AGL_BAD_RENDINFO: Int32 { get }
var AGL_BAD_CONTEXT: Int32 { get }
var AGL_BAD_DRAWABLE: Int32 { get }
var AGL_BAD_GDEV: Int32 { get }
var AGL_BAD_STATE: Int32 { get }
var AGL_BAD_VALUE: Int32 { get }
var AGL_BAD_MATCH: Int32 { get }
var AGL_BAD_ENUM: Int32 { get }
var AGL_BAD_OFFSCREEN: Int32 { get }
var AGL_BAD_FULLSCREEN: Int32 { get }
var AGL_BAD_WINDOW: Int32 { get }
var AGL_BAD_POINTER: Int32 { get }
var AGL_BAD_MODULE: Int32 { get }
var AGL_BAD_ALLOC: Int32 { get }
var AGL_BAD_CONNECTION: Int32 { get }
var AGL_INVALID_FUNCTION: Int32 { get }
