#ifndef TEST_INTEROP_CXX_STDLIB_INPUTS_STD_STRING_H
#define TEST_INTEROP_CXX_STDLIB_INPUTS_STD_STRING_H

#include <string>

using CxxString = std::string;

#endif // TEST_INTEROP_CXX_STDLIB_INPUTS_STD_STRING_H