import Foundation

public extension NSCocoaError {
  static let ManagedObjectValidationError = NSCocoaError(rawValue: 1550)
  static let ValidationMultipleErrorsError = NSCocoaError(rawValue: 1560)
  static let ValidationMissingMandatoryPropertyError = NSCocoaError(rawValue: 1570)
  static let ValidationRelationshipLacksMinimumCountError = NSCocoaError(rawValue: 1580)
  static let ValidationRelationshipExceedsMaximumCountError = NSCocoaError(rawValue: 1590)
  static let ValidationRelationshipDeniedDeleteError = NSCocoaError(rawValue: 1600)
  static let ValidationNumberTooLargeError = NSCocoaError(rawValue: 1610)
  static let ValidationNumberTooSmallError = NSCocoaError(rawValue: 1620)
  static let ValidationDateTooLateError = NSCocoaError(rawValue: 1630)
  static let ValidationDateTooSoonError = NSCocoaError(rawValue: 1640)
  static let ValidationInvalidDateError = NSCocoaError(rawValue: 1650)
  static let ValidationStringTooLongError = NSCocoaError(rawValue: 1660)
  static let ValidationStringTooShortError = NSCocoaError(rawValue: 1670)
  static let ValidationStringPatternMatchingError = NSCocoaError(rawValue: 1680)
  static let ManagedObjectContextLockingError = NSCocoaError(rawValue: 132000)
  static let PersistentStoreCoordinatorLockingError = NSCocoaError(rawValue: 132010)
  static let ManagedObjectReferentialIntegrityError = NSCocoaError(rawValue: 133000)
  static let ManagedObjectExternalRelationshipError = NSCocoaError(rawValue: 133010)
  static let ManagedObjectMergeError = NSCocoaError(rawValue: 133020)
  static let ManagedObjectConstraintMergeError = NSCocoaError(rawValue: 133021)
  static let PersistentStoreInvalidTypeError = NSCocoaError(rawValue: 134000)
  static let PersistentStoreTypeMismatchError = NSCocoaError(rawValue: 134010)
  static let PersistentStoreIncompatibleSchemaError = NSCocoaError(rawValue: 134020)
  static let PersistentStoreSaveError = NSCocoaError(rawValue: 134030)
  static let PersistentStoreIncompleteSaveError = NSCocoaError(rawValue: 134040)
  static let PersistentStoreSaveConflictsError = NSCocoaError(rawValue: 134050)
  static let CoreDataError = NSCocoaError(rawValue: 134060)
  static let PersistentStoreOperationError = NSCocoaError(rawValue: 134070)
  static let PersistentStoreOpenError = NSCocoaError(rawValue: 134080)
  static let PersistentStoreTimeoutError = NSCocoaError(rawValue: 134090)
  static let PersistentStoreUnsupportedRequestTypeError = NSCocoaError(rawValue: 134091)
  static let PersistentStoreIncompatibleVersionHashError = NSCocoaError(rawValue: 134100)
  static let MigrationError = NSCocoaError(rawValue: 134110)
  static let MigrationCancelledError = NSCocoaError(rawValue: 134120)
  static let MigrationMissingSourceModelError = NSCocoaError(rawValue: 134130)
  static let MigrationMissingMappingModelError = NSCocoaError(rawValue: 134140)
  static let MigrationManagerSourceStoreError = NSCocoaError(rawValue: 134150)
  static let MigrationManagerDestinationStoreError = NSCocoaError(rawValue: 134160)
  static let EntityMigrationPolicyError = NSCocoaError(rawValue: 134170)
  static let SQLiteError = NSCocoaError(rawValue: 134180)
  static let InferredMappingModelError = NSCocoaError(rawValue: 134190)
  static let ExternalRecordImportError = NSCocoaError(rawValue: 134200)
}

