
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_ScalingMode: CFString
@available(OSX 10.8, *)
let kVTScalingMode_Normal: CFString
@available(OSX 10.8, *)
let kVTScalingMode_CropSourceToCleanAperture: CFString
@available(OSX 10.8, *)
let kVTScalingMode_Letterbox: CFString
@available(OSX 10.8, *)
let kVTScalingMode_Trim: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationCleanAperture: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationPixelAspectRatio: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DownsamplingMode: CFString
@available(OSX 10.8, *)
let kVTDownsamplingMode_Decimate: CFString
@available(OSX 10.8, *)
let kVTDownsamplingMode_Average: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationColorPrimaries: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationTransferFunction: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationICCProfile: CFString
@available(OSX 10.8, *)
let kVTPixelTransferPropertyKey_DestinationYCbCrMatrix: CFString
