
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeOther: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeSecuritySystem: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeBridge: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeDoor: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeDoorLock: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeFan: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeGarageDoorOpener: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeLightbulb: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeOutlet: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeProgrammableSwitch: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeSensor: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeSwitch: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeThermostat: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeWindow: String
@available(watchOS 20000, *)
let HMAccessoryCategoryTypeWindowCovering: String
@available(watchOS 2.2, *)
let HMAccessoryCategoryTypeRangeExtender: String
