
@available(watchOS 20000, *)
let HMCharacteristicPropertySupportsEventNotification: String
@available(watchOS 20000, *)
let HMCharacteristicPropertyReadable: String
@available(watchOS 20000, *)
let HMCharacteristicPropertyWritable: String
@available(watchOS 2.2, *)
let HMCharacteristicPropertyHidden: String
@available(watchOS 20000, *)
let HMCharacteristicTypePowerState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeHue: String
@available(watchOS 20000, *)
let HMCharacteristicTypeSaturation: String
@available(watchOS 20000, *)
let HMCharacteristicTypeBrightness: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTemperatureUnits: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentTemperature: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetTemperature: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentHeatingCooling: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetHeatingCooling: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCoolingThreshold: String
@available(watchOS 20000, *)
let HMCharacteristicTypeHeatingThreshold: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentRelativeHumidity: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetRelativeHumidity: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentDoorState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetDoorState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeObstructionDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeName: String
@available(watchOS 20000, *)
let HMCharacteristicTypeManufacturer: String
@available(watchOS 20000, *)
let HMCharacteristicTypeModel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeSerialNumber: String
@available(watchOS 20000, *)
let HMCharacteristicTypeIdentify: String
@available(watchOS 20000, *)
let HMCharacteristicTypeRotationDirection: String
@available(watchOS 20000, *)
let HMCharacteristicTypeRotationSpeed: String
@available(watchOS 20000, *)
let HMCharacteristicTypeOutletInUse: String
@available(watchOS 20000, *)
let HMCharacteristicTypeVersion: String
@available(watchOS 20000, *)
let HMCharacteristicTypeLogs: String
@available(watchOS 20000, *)
let HMCharacteristicTypeAudioFeedback: String
@available(watchOS 20000, *)
let HMCharacteristicTypeAdminOnlyAccess: String
@available(watchOS 20000, *)
let HMCharacteristicTypeSecuritySystemAlarmType: String
@available(watchOS 20000, *)
let HMCharacteristicTypeMotionDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentLockMechanismState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetLockMechanismState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeLockMechanismLastKnownAction: String
@available(watchOS 20000, *)
let HMCharacteristicTypeLockManagementControlPoint: String
@available(watchOS 20000, *)
let HMCharacteristicTypeLockManagementAutoSecureTimeout: String
@available(watchOS 20000, *)
let HMCharacteristicTypeAirParticulateDensity: String
@available(watchOS 20000, *)
let HMCharacteristicTypeAirParticulateSize: String
@available(watchOS 20000, *)
let HMCharacteristicTypeAirQuality: String
@available(watchOS 20000, *)
let HMCharacteristicTypeBatteryLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonDioxideDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonDioxideLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonDioxidePeakLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonMonoxideDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonMonoxideLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCarbonMonoxidePeakLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeChargingState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeContactState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentHorizontalTilt: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentLightLevel: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentPosition: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentSecuritySystemState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeCurrentVerticalTilt: String
@available(watchOS 20000, *)
let HMCharacteristicTypeFirmwareVersion: String
@available(watchOS 20000, *)
let HMCharacteristicTypeHardwareVersion: String
@available(watchOS 20000, *)
let HMCharacteristicTypeHoldPosition: String
@available(watchOS 20000, *)
let HMCharacteristicTypeInputEvent: String
@available(watchOS 20000, *)
let HMCharacteristicTypeLeakDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeOccupancyDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeOutputState: String
@available(watchOS 20000, *)
let HMCharacteristicTypePositionState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeSmokeDetected: String
@available(watchOS 20000, *)
let HMCharacteristicTypeSoftwareVersion: String
@available(watchOS 20000, *)
let HMCharacteristicTypeStatusActive: String
@available(watchOS 20000, *)
let HMCharacteristicTypeStatusFault: String
@available(watchOS 20000, *)
let HMCharacteristicTypeStatusJammed: String
@available(watchOS 20000, *)
let HMCharacteristicTypeStatusLowBattery: String
@available(watchOS 20000, *)
let HMCharacteristicTypeStatusTampered: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetHorizontalTilt: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetSecuritySystemState: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetPosition: String
@available(watchOS 20000, *)
let HMCharacteristicTypeTargetVerticalTilt: String
