
@available(watchOS 20000, *)
let HMServiceTypeLightbulb: String
@available(watchOS 20000, *)
let HMServiceTypeSwitch: String
@available(watchOS 20000, *)
let HMServiceTypeThermostat: String
@available(watchOS 20000, *)
let HMServiceTypeGarageDoorOpener: String
@available(watchOS 20000, *)
let HMServiceTypeAccessoryInformation: String
@available(watchOS 20000, *)
let HMServiceTypeFan: String
@available(watchOS 20000, *)
let HMServiceTypeOutlet: String
@available(watchOS 20000, *)
let HMServiceTypeLockMechanism: String
@available(watchOS 20000, *)
let HMServiceTypeLockManagement: String
@available(watchOS 20000, *)
let HMServiceTypeAirQualitySensor: String
@available(watchOS 20000, *)
let HMServiceTypeBattery: String
@available(watchOS 20000, *)
let HMServiceTypeCarbonDioxideSensor: String
@available(watchOS 20000, *)
let HMServiceTypeCarbonMonoxideSensor: String
@available(watchOS 20000, *)
let HMServiceTypeContactSensor: String
@available(watchOS 20000, *)
let HMServiceTypeDoor: String
@available(watchOS 20000, *)
let HMServiceTypeHumiditySensor: String
@available(watchOS 20000, *)
let HMServiceTypeLeakSensor: String
@available(watchOS 20000, *)
let HMServiceTypeLightSensor: String
@available(watchOS 20000, *)
let HMServiceTypeMotionSensor: String
@available(watchOS 20000, *)
let HMServiceTypeOccupancySensor: String
@available(watchOS 20000, *)
let HMServiceTypeSecuritySystem: String
@available(watchOS 20000, *)
let HMServiceTypeStatefulProgrammableSwitch: String
@available(watchOS 20000, *)
let HMServiceTypeStatelessProgrammableSwitch: String
@available(watchOS 20000, *)
let HMServiceTypeSmokeSensor: String
@available(watchOS 20000, *)
let HMServiceTypeTemperatureSensor: String
@available(watchOS 20000, *)
let HMServiceTypeWindow: String
@available(watchOS 20000, *)
let HMServiceTypeWindowCovering: String
