
var AC_APPLE_UNIVERSAL_BUILD: Int32 { get }
var ENABLE_IPV6: Int32 { get }
var HAVE_ACOSH: Int32 { get }
var HAVE_ADDRINFO: Int32 { get }
var HAVE_ALARM: Int32 { get }
var HAVE_ALLOCA_H: Int32 { get }
var HAVE_ASINH: Int32 { get }
var HAVE_ATANH: Int32 { get }
var HAVE_BROKEN_SEM_GETVALUE: Int32 { get }
var HAVE_C99_BOOL: Int32 { get }
var HAVE_CHFLAGS: Int32 { get }
var HAVE_CHOWN: Int32 { get }
var HAVE_CHROOT: Int32 { get }
var HAVE_CLOCK: Int32 { get }
var HAVE_CONFSTR: Int32 { get }
var HAVE_COPYSIGN: Int32 { get }
var HAVE_CTERMID: Int32 { get }
var HAVE_CTERMID_R: Int32 { get }
var HAVE_CURSES_H: Int32 { get }
var HAVE_CURSES_IS_TERM_RESIZED: Int32 { get }
var HAVE_CURSES_RESIZETERM: Int32 { get }
var HAVE_CURSES_RESIZE_TERM: Int32 { get }
var HAVE_DECL_ISFINITE: Int32 { get }
var HAVE_DECL_ISINF: Int32 { get }
var HAVE_DECL_ISNAN: Int32 { get }
var HAVE_DEVICE_MACROS: Int32 { get }
var HAVE_DEV_PTMX: Int32 { get }
var HAVE_DIRENT_H: Int32 { get }
var HAVE_DLFCN_H: Int32 { get }
var HAVE_DLOPEN: Int32 { get }
var HAVE_DUP2: Int32 { get }
var HAVE_DYNAMIC_LOADING: Int32 { get }
var HAVE_ERF: Int32 { get }
var HAVE_ERFC: Int32 { get }
var HAVE_ERRNO_H: Int32 { get }
var HAVE_EXECV: Int32 { get }
var HAVE_EXPM1: Int32 { get }
var HAVE_FCHDIR: Int32 { get }
var HAVE_FCHMOD: Int32 { get }
var HAVE_FCHOWN: Int32 { get }
var HAVE_FCNTL_H: Int32 { get }
var HAVE_FINITE: Int32 { get }
var HAVE_FLOCK: Int32 { get }
var HAVE_FORK: Int32 { get }
var HAVE_FORKPTY: Int32 { get }
var HAVE_FPATHCONF: Int32 { get }
var HAVE_FSEEKO: Int32 { get }
var HAVE_FSTATVFS: Int32 { get }
var HAVE_FSYNC: Int32 { get }
var HAVE_FTELLO: Int32 { get }
var HAVE_FTIME: Int32 { get }
var HAVE_FTRUNCATE: Int32 { get }
var HAVE_GAI_STRERROR: Int32 { get }
var HAVE_GAMMA: Int32 { get }
var HAVE_GETADDRINFO: Int32 { get }
var HAVE_GETCWD: Int32 { get }
var HAVE_GETC_UNLOCKED: Int32 { get }
var HAVE_GETGROUPS: Int32 { get }
var HAVE_GETHOSTBYNAME: Int32 { get }
var HAVE_GETITIMER: Int32 { get }
var HAVE_GETLOADAVG: Int32 { get }
var HAVE_GETLOGIN: Int32 { get }
var HAVE_GETNAMEINFO: Int32 { get }
var HAVE_GETPAGESIZE: Int32 { get }
var HAVE_GETPEERNAME: Int32 { get }
var HAVE_GETPGID: Int32 { get }
var HAVE_GETPGRP: Int32 { get }
var HAVE_GETPID: Int32 { get }
var HAVE_GETPRIORITY: Int32 { get }
var HAVE_GETPWENT: Int32 { get }
var HAVE_GETSID: Int32 { get }
var HAVE_GETTIMEOFDAY: Int32 { get }
var HAVE_GETWD: Int32 { get }
var HAVE_GRP_H: Int32 { get }
var HAVE_HSTRERROR: Int32 { get }
var HAVE_HYPOT: Int32 { get }
var HAVE_INET_ATON: Int32 { get }
var HAVE_INET_PTON: Int32 { get }
var HAVE_INITGROUPS: Int32 { get }
var HAVE_INT32_T: Int32 { get }
var HAVE_INT64_T: Int32 { get }
var HAVE_INTTYPES_H: Int32 { get }
var HAVE_KILL: Int32 { get }
var HAVE_KILLPG: Int32 { get }
var HAVE_KQUEUE: Int32 { get }
var HAVE_LANGINFO_H: Int32 { get }
var HAVE_LCHFLAGS: Int32 { get }
var HAVE_LCHMOD: Int32 { get }
var HAVE_LCHOWN: Int32 { get }
var HAVE_LGAMMA: Int32 { get }
var HAVE_LIBDL: Int32 { get }
var HAVE_LIBREADLINE: Int32 { get }
var HAVE_LIBUTIL_H: Int32 { get }
var HAVE_LINK: Int32 { get }
var HAVE_LOG1P: Int32 { get }
var HAVE_LONG_DOUBLE: Int32 { get }
var HAVE_LONG_LONG: Int32 { get }
var HAVE_LSTAT: Int32 { get }
var HAVE_MAKEDEV: Int32 { get }
var HAVE_MEMMOVE: Int32 { get }
var HAVE_MEMORY_H: Int32 { get }
var HAVE_MKFIFO: Int32 { get }
var HAVE_MKNOD: Int32 { get }
var HAVE_MKTIME: Int32 { get }
var HAVE_MMAP: Int32 { get }
var HAVE_NCURSES_H: Int32 { get }
var HAVE_NICE: Int32 { get }
var HAVE_OPENPTY: Int32 { get }
var HAVE_OSX105_SDK: Int32 { get }
var HAVE_PATHCONF: Int32 { get }
var HAVE_PAUSE: Int32 { get }
var HAVE_PROTOTYPES: Int32 { get }
var HAVE_PTHREAD_ATFORK: Int32 { get }
var HAVE_PTHREAD_H: Int32 { get }
var HAVE_PTHREAD_SIGMASK: Int32 { get }
var HAVE_PUTENV: Int32 { get }
var HAVE_RAND_EGD: Int32 { get }
var HAVE_READLINK: Int32 { get }
var HAVE_REALPATH: Int32 { get }
var HAVE_RL_CALLBACK: Int32 { get }
var HAVE_RL_COMPLETION_APPEND_CHARACTER: Int32 { get }
var HAVE_RL_COMPLETION_MATCHES: Int32 { get }
var HAVE_RL_PRE_INPUT_HOOK: Int32 { get }
var HAVE_ROUND: Int32 { get }
var HAVE_SELECT: Int32 { get }
var HAVE_SEM_GETVALUE: Int32 { get }
var HAVE_SEM_OPEN: Int32 { get }
var HAVE_SEM_UNLINK: Int32 { get }
var HAVE_SETEGID: Int32 { get }
var HAVE_SETEUID: Int32 { get }
var HAVE_SETGID: Int32 { get }
var HAVE_SETGROUPS: Int32 { get }
var HAVE_SETITIMER: Int32 { get }
var HAVE_SETLOCALE: Int32 { get }
var HAVE_SETPGID: Int32 { get }
var HAVE_SETPGRP: Int32 { get }
var HAVE_SETREGID: Int32 { get }
var HAVE_SETREUID: Int32 { get }
var HAVE_SETSID: Int32 { get }
var HAVE_SETUID: Int32 { get }
var HAVE_SETVBUF: Int32 { get }
var HAVE_SIGACTION: Int32 { get }
var HAVE_SIGINTERRUPT: Int32 { get }
var HAVE_SIGNAL_H: Int32 { get }
var HAVE_SIGRELSE: Int32 { get }
var HAVE_SNPRINTF: Int32 { get }
var HAVE_SOCKADDR_SA_LEN: Int32 { get }
var HAVE_SOCKADDR_STORAGE: Int32 { get }
var HAVE_SOCKETPAIR: Int32 { get }
var HAVE_SPAWN_H: Int32 { get }
var HAVE_SSIZE_T: Int32 { get }
var HAVE_STATVFS: Int32 { get }
var HAVE_STAT_TV_NSEC2: Int32 { get }
var HAVE_STDARG_PROTOTYPES: Int32 { get }
var HAVE_STDINT_H: Int32 { get }
var HAVE_STDLIB_H: Int32 { get }
var HAVE_STRDUP: Int32 { get }
var HAVE_STRFTIME: Int32 { get }
var HAVE_STRINGS_H: Int32 { get }
var HAVE_STRING_H: Int32 { get }
var HAVE_STRUCT_STAT_ST_BIRTHTIME: Int32 { get }
var HAVE_STRUCT_STAT_ST_BLKSIZE: Int32 { get }
var HAVE_STRUCT_STAT_ST_BLOCKS: Int32 { get }
var HAVE_STRUCT_STAT_ST_FLAGS: Int32 { get }
var HAVE_STRUCT_STAT_ST_GEN: Int32 { get }
var HAVE_STRUCT_STAT_ST_RDEV: Int32 { get }
var HAVE_STRUCT_TM_TM_ZONE: Int32 { get }
var HAVE_ST_BLOCKS: Int32 { get }
var HAVE_SYMLINK: Int32 { get }
var HAVE_SYSCONF: Int32 { get }
var HAVE_SYSEXITS_H: Int32 { get }
var HAVE_SYS_EVENT_H: Int32 { get }
var HAVE_SYS_FILE_H: Int32 { get }
var HAVE_SYS_LOCK_H: Int32 { get }
var HAVE_SYS_PARAM_H: Int32 { get }
var HAVE_SYS_POLL_H: Int32 { get }
var HAVE_SYS_RESOURCE_H: Int32 { get }
var HAVE_SYS_SELECT_H: Int32 { get }
var HAVE_SYS_SOCKET_H: Int32 { get }
var HAVE_SYS_STATVFS_H: Int32 { get }
var HAVE_SYS_STAT_H: Int32 { get }
var HAVE_SYS_TIMES_H: Int32 { get }
var HAVE_SYS_TIME_H: Int32 { get }
var HAVE_SYS_TYPES_H: Int32 { get }
var HAVE_SYS_UN_H: Int32 { get }
var HAVE_SYS_UTSNAME_H: Int32 { get }
var HAVE_SYS_WAIT_H: Int32 { get }
var HAVE_TCGETPGRP: Int32 { get }
var HAVE_TCSETPGRP: Int32 { get }
var HAVE_TEMPNAM: Int32 { get }
var HAVE_TERMIOS_H: Int32 { get }
var HAVE_TERM_H: Int32 { get }
var HAVE_TGAMMA: Int32 { get }
var HAVE_TIMEGM: Int32 { get }
var HAVE_TIMES: Int32 { get }
var HAVE_TMPFILE: Int32 { get }
var HAVE_TMPNAM: Int32 { get }
var HAVE_TM_ZONE: Int32 { get }
var HAVE_TRUNCATE: Int32 { get }
var HAVE_UINT32_T: Int32 { get }
var HAVE_UINT64_T: Int32 { get }
var HAVE_UINTPTR_T: Int32 { get }
var HAVE_UNAME: Int32 { get }
var HAVE_UNISTD_H: Int32 { get }
var HAVE_UNSETENV: Int32 { get }
var HAVE_UTIL_H: Int32 { get }
var HAVE_UTIMES: Int32 { get }
var HAVE_UTIME_H: Int32 { get }
var HAVE_WAIT3: Int32 { get }
var HAVE_WAIT4: Int32 { get }
var HAVE_WAITPID: Int32 { get }
var HAVE_WCHAR_H: Int32 { get }
var HAVE_WCSCOLL: Int32 { get }
var HAVE_WORKING_TZSET: Int32 { get }
var HAVE_ZLIB_COPY: Int32 { get }
var MVWDELCH_IS_EXPRESSION: Int32 { get }
var PTHREAD_SYSTEM_SCHED_SUPPORTED: Int32 { get }
var PY_FORMAT_LONG_LONG: String { get }
var Py_UNICODE_SIZE: Int32 { get }
var Py_USING_UNICODE: Int32 { get }
var SHLIB_EXT: String { get }
var SIZEOF_DOUBLE: Int32 { get }
var SIZEOF_FLOAT: Int32 { get }
var SIZEOF_FPOS_T: Int32 { get }
var SIZEOF_INT: Int32 { get }
var SIZEOF_LONG_DOUBLE: Int32 { get }
var SIZEOF_LONG_LONG: Int32 { get }
var SIZEOF_OFF_T: Int32 { get }
var SIZEOF_PID_T: Int32 { get }
var SIZEOF_SHORT: Int32 { get }
var SIZEOF_WCHAR_T: Int32 { get }
var STDC_HEADERS: Int32 { get }
var SYS_SELECT_WITH_SYS_TIME: Int32 { get }
var TANH_PRESERVES_ZERO_SIGN: Int32 { get }
var TIME_WITH_SYS_TIME: Int32 { get }
var _ALL_SOURCE: Int32 { get }
var _POSIX_PTHREAD_SEMANTICS: Int32 { get }
var _TANDEM_SOURCE: Int32 { get }
var USE_TOOLBOX_OBJECT_GLUE: Int32 { get }
var WITH_DOC_STRINGS: Int32 { get }
var WITH_DYLD: Int32 { get }
var WITH_NEXT_FRAMEWORK: Int32 { get }
var WITH_PYMALLOC: Int32 { get }
var WITH_THREAD: Int32 { get }
var _BSD_TYPES: Int32 { get }
var _DARWIN_C_SOURCE: Int32 { get }
var _FILE_OFFSET_BITS: Int32 { get }
var _GNU_SOURCE: Int32 { get }
var _LARGEFILE_SOURCE: Int32 { get }
var _NETBSD_SOURCE: Int32 { get }
var _REENTRANT: Int32 { get }
var __BSD_VISIBLE: Int32 { get }
var __EXTENSIONS__: Int32 { get }
