
@available(watchOS 2.0, *)
let NSMetadataItemFSNameKey: String
@available(watchOS 2.0, *)
let NSMetadataItemDisplayNameKey: String
@available(watchOS 2.0, *)
let NSMetadataItemURLKey: String
@available(watchOS 2.0, *)
let NSMetadataItemPathKey: String
@available(watchOS 2.0, *)
let NSMetadataItemFSSizeKey: String
@available(watchOS 2.0, *)
let NSMetadataItemFSCreationDateKey: String
@available(watchOS 2.0, *)
let NSMetadataItemFSContentChangeDateKey: String
@available(watchOS 2.0, *)
let NSMetadataItemContentTypeKey: String
@available(watchOS 2.0, *)
let NSMetadataItemContentTypeTreeKey: String
@available(watchOS 2.0, *)
let NSMetadataItemIsUbiquitousKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemHasUnresolvedConflictsKey: String
@available(watchOS, introduced: 2.0, deprecated: 2.0, message: "Use NSMetadataUbiquitousItemDownloadingStatusKey instead")
let NSMetadataUbiquitousItemIsDownloadedKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadingStatusKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadingStatusNotDownloaded: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadingStatusDownloaded: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadingStatusCurrent: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemIsDownloadingKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemIsUploadedKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemIsUploadingKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemPercentDownloadedKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemPercentUploadedKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadingErrorKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemUploadingErrorKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemDownloadRequestedKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemIsExternalDocumentKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemContainerDisplayNameKey: String
@available(watchOS 2.0, *)
let NSMetadataUbiquitousItemURLInLocalContainerKey: String
