#ifndef TEST_INTEROP_CXX_CLASS_INPUTS_FORWARD_DECLARED_IN_NAMESPACE_H
#define TEST_INTEROP_CXX_CLASS_INPUTS_FORWARD_DECLARED_IN_NAMESPACE_H

namespace Space {

struct C;

struct C {
  void test() const;
};

}

#endif // TEST_INTEROP_CXX_CLASS_INPUTS_FORWARD_DECLARED_IN_NAMESPACE_H
