#!/usr/bin/env python
# mock-distcc - discc mock used from tests ----------------------*- python -*-
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

from __future__ import print_function

import sys


try:
    if sys.argv[1] == '-j':
        print('6')
        sys.exit(0)
except Exception:
    pass

print("Error: invalid option", file=sys.stderr)
sys.exit(1)
