
var kDSStdMachPortName: String { get }
var kDSStdMachDebugPortName: String { get }
var kDSStdMachLocalPortName: String { get }
var kDSStdMachDSLookupPortName: String { get }
var kDSRecordsAll: String { get }
var kDSRecordsStandardAll: String { get }
var kDSRecordsNativeAll: String { get }
var kDSStdRecordTypePrefix: String { get }
var kDSNativeRecordTypePrefix: String { get }
var kDSStdRecordTypeAll: String { get }
var kDSStdUserNamesMeta: String { get }
var kDSStdRecordTypePlugins: String { get }
var kDSStdRecordTypeRefTableEntries: String { get }
var kDSStdRecordTypeRecordTypes: String { get }
var kDSStdRecordTypeAttributeTypes: String { get }
var kDSStdRecordTypeAccessControls: String { get }
var kDSStdRecordTypeAFPServer: String { get }
var kDSStdRecordTypeAFPUserAliases: String { get }
var kDSStdRecordTypeAliases: String { get }
var kDSStdRecordTypeAugments: String { get }
var kDSStdRecordTypeAutomount: String { get }
var kDSStdRecordTypeAutomountMap: String { get }
var kDSStdRecordTypeAutoServerSetup: String { get }
var kDSStdRecordTypeBootp: String { get }
var kDSStdRecordTypeCertificateAuthorities: String { get }
var kDSStdRecordTypeComputerLists: String { get }
var kDSStdRecordTypeComputerGroups: String { get }
var kDSStdRecordTypeComputers: String { get }
var kDSStdRecordTypeConfig: String { get }
var kDSStdRecordTypeEthernets: String { get }
var kDSStdRecordTypeFileMakerServers: String { get }
var kDSStdRecordTypeFTPServer: String { get }
var kDSStdRecordTypeGroupAliases: String { get }
var kDSStdRecordTypeGroups: String { get }
var kDSStdRecordTypeHostServices: String { get }
var kDSStdRecordTypeHosts: String { get }
var kDSStdRecordTypeLDAPServer: String { get }
var kDSStdRecordTypeLocations: String { get }
var kDSStdRecordTypeMachines: String { get }
var kDSStdRecordTypeMeta: String { get }
var kDSStdRecordTypeMounts: String { get }
var kDSStdRecordTypMounts: String { get }
var kDSStdRecordTypeNeighborhoods: String { get }
var kDSStdRecordTypeNFS: String { get }
var kDSStdRecordTypeNetDomains: String { get }
var kDSStdRecordTypeNetGroups: String { get }
var kDSStdRecordTypeNetworks: String { get }
var kDSStdRecordTypePasswordServer: String { get }
var kDSStdRecordTypePeople: String { get }
var kDSStdRecordTypePresetComputers: String { get }
var kDSStdRecordTypePresetComputerGroups: String { get }
var kDSStdRecordTypePresetComputerLists: String { get }
var kDSStdRecordTypePresetGroups: String { get }
var kDSStdRecordTypePresetUsers: String { get }
var kDSStdRecordTypePrintService: String { get }
var kDSStdRecordTypePrintServiceUser: String { get }
var kDSStdRecordTypePrinters: String { get }
var kDSStdRecordTypeProtocols: String { get }
var kDSStdRecordTypProtocols: String { get }
var kDSStdRecordTypeQTSServer: String { get }
var kDSStdRecordTypeResources: String { get }
var kDSStdRecordTypeRPC: String { get }
var kDSStdRecordTypRPC: String { get }
var kDSStdRecordTypeSMBServer: String { get }
var kDSStdRecordTypeServer: String { get }
var kDSStdRecordTypeServices: String { get }
var kDSStdRecordTypeSharePoints: String { get }
var kDSStdRecordTypeUserAliases: String { get }
var kDSStdRecordTypeUsers: String { get }
var kDSStdRecordTypeWebServer: String { get }
var kDSAttributesAll: String { get }
var kDSAttributesStandardAll: String { get }
var kDSAttributesNativeAll: String { get }
var kDSStdAttrTypePrefix: String { get }
var kDSNativeAttrTypePrefix: String { get }
var kDSAttrNone: String { get }
var kDS1AttrAdminLimits: String { get }
var kDS1AttrAliasData: String { get }
var kDS1AttrAlternateDatastoreLocation: String { get }
var kDS1AttrAuthenticationHint: String { get }
var kDSNAttrAttributeTypes: String { get }
var kDS1AttrAuthorityRevocationList: String { get }
var kDS1AttrBirthday: String { get }
var kDS1AttrBootFile: String { get }
var kDS1AttrCACertificate: String { get }
var kDS1AttrCapabilities: String { get }
var kDS1AttrCapacity: String { get }
var kDS1AttrCategory: String { get }
var kDS1AttrCertificateRevocationList: String { get }
var kDS1AttrChange: String { get }
var kDS1AttrComment: String { get }
var kDS1AttrContactGUID: String { get }
var kDS1AttrContactPerson: String { get }
var kDS1AttrCreationTimestamp: String { get }
var kDS1AttrCrossCertificatePair: String { get }
var kDS1AttrDataStamp: String { get }
var kDS1AttrDistinguishedName: String { get }
var kDS1AttrDNSDomain: String { get }
var kDS1AttrDNSNameServer: String { get }
var kDS1AttrENetAddress: String { get }
var kDS1AttrExpire: String { get }
var kDS1AttrFirstName: String { get }
var kDS1AttrGeneratedUID: String { get }
var kDS1AttrHomeDirectoryQuota: String { get }
var kDS1AttrHomeDirectorySoftQuota: String { get }
var kDS1AttrHomeLocOwner: String { get }
var kDS1StandardAttrHomeLocOwner: String { get }
var kDS1AttrInternetAlias: String { get }
var kDS1AttrKDCConfigData: String { get }
var kDS1AttrLastName: String { get }
var kDS1AttrLDAPSearchBaseSuffix: String { get }
var kDS1AttrLocation: String { get }
var kDS1AttrMapGUID: String { get }
var kDS1AttrMCXFlags: String { get }
var kDS1AttrMCXSettings: String { get }
var kDS1AttrMailAttribute: String { get }
var kDS1AttrMetaAutomountMap: String { get }
var kDS1AttrMiddleName: String { get }
var kDS1AttrModificationTimestamp: String { get }
var kDSNAttrNeighborhoodAlias: String { get }
var kDS1AttrNeighborhoodType: String { get }
var kDS1AttrNetworkView: String { get }
var kDS1AttrNFSHomeDirectory: String { get }
var kDS1AttrNote: String { get }
var kDS1AttrOwner: String { get }
var kDS1AttrOwnerGUID: String { get }
var kDS1AttrPassword: String { get }
var kDS1AttrPasswordPlus: String { get }
var kDS1AttrPasswordPolicyOptions: String { get }
var kDS1AttrPasswordServerList: String { get }
var kDS1AttrPasswordServerLocation: String { get }
var kDS1AttrPicture: String { get }
var kDS1AttrPort: String { get }
var kDS1AttrPresetUserIsAdmin: String { get }
var kDS1AttrPrimaryComputerGUID: String { get }
var kDS1AttrPrimaryComputerList: String { get }
var kDS1AttrPrimaryGroupID: String { get }
var kDS1AttrPrinter1284DeviceID: String { get }
var kDS1AttrPrinterLPRHost: String { get }
var kDS1AttrPrinterLPRQueue: String { get }
var kDS1AttrPrinterMakeAndModel: String { get }
var kDS1AttrPrinterType: String { get }
var kDS1AttrPrinterURI: String { get }
var kDSNAttrPrinterXRISupported: String { get }
var kDS1AttrPrintServiceInfoText: String { get }
var kDS1AttrPrintServiceInfoXML: String { get }
var kDS1AttrPrintServiceUserData: String { get }
var kDS1AttrRealUserID: String { get }
var kDS1AttrRelativeDNPrefix: String { get }
var kDS1AttrSMBAcctFlags: String { get }
var kDS1AttrSMBHome: String { get }
var kDS1AttrSMBHomeDrive: String { get }
var kDS1AttrSMBKickoffTime: String { get }
var kDS1AttrSMBLogoffTime: String { get }
var kDS1AttrSMBLogonTime: String { get }
var kDS1AttrSMBPrimaryGroupSID: String { get }
var kDS1AttrSMBPWDLastSet: String { get }
var kDS1AttrSMBProfilePath: String { get }
var kDS1AttrSMBRID: String { get }
var kDS1AttrSMBScriptPath: String { get }
var kDS1AttrSMBSID: String { get }
var kDS1AttrSMBUserWorkstations: String { get }
var kDS1AttrServiceType: String { get }
var kDS1AttrSetupAdvertising: String { get }
var kDS1AttrSetupAutoRegister: String { get }
var kDS1AttrSetupLocation: String { get }
var kDS1AttrSetupOccupation: String { get }
var kDS1AttrTimeToLive: String { get }
var kDS1AttrUniqueID: String { get }
var kDS1AttrUserCertificate: String { get }
var kDS1AttrUserPKCS12Data: String { get }
var kDS1AttrUserShell: String { get }
var kDS1AttrUserSMIMECertificate: String { get }
var kDS1AttrVFSDumpFreq: String { get }
var kDS1AttrVFSLinkDir: String { get }
var kDS1AttrVFSPassNo: String { get }
var kDS1AttrVFSType: String { get }
var kDS1AttrWeblogURI: String { get }
var kDS1AttrXMLPlist: String { get }
var kDS1AttrProtocolNumber: String { get }
var kDS1AttrRPCNumber: String { get }
var kDS1AttrNetworkNumber: String { get }
var kDSNAttrAccessControlEntry: String { get }
var kDSNAttrAddressLine1: String { get }
var kDSNAttrAddressLine2: String { get }
var kDSNAttrAddressLine3: String { get }
var kDSNAttrAreaCode: String { get }
var kDSNAttrAuthenticationAuthority: String { get }
var kDSNAttrAutomountInformation: String { get }
var kDSNAttrBootParams: String { get }
var kDSNAttrBuilding: String { get }
var kDSNAttrServicesLocator: String { get }
var kDSNAttrCity: String { get }
var kDSNAttrCompany: String { get }
var kDSNAttrComputerAlias: String { get }
var kDSNAttrComputers: String { get }
var kDSNAttrCountry: String { get }
var kDSNAttrDepartment: String { get }
var kDSNAttrDNSName: String { get }
var kDSNAttrEMailAddress: String { get }
var kDSNAttrEMailContacts: String { get }
var kDSNAttrFaxNumber: String { get }
var kDSNAttrGroup: String { get }
var kDSNAttrGroupMembers: String { get }
var kDSNAttrGroupMembership: String { get }
var kDSNAttrGroupServices: String { get }
var kDSNAttrHomePhoneNumber: String { get }
var kDSNAttrHTML: String { get }
var kDSNAttrHomeDirectory: String { get }
var kDSNAttrIMHandle: String { get }
var kDSNAttrIPAddress: String { get }
var kDSNAttrIPAddressAndENetAddress: String { get }
var kDSNAttrIPv6Address: String { get }
var kDSNAttrJPEGPhoto: String { get }
var kDSNAttrJobTitle: String { get }
var kDSNAttrKDCAuthKey: String { get }
var kDSNAttrKeywords: String { get }
var kDSNAttrLDAPReadReplicas: String { get }
var kDSNAttrLDAPWriteReplicas: String { get }
var kDSNAttrMachineServes: String { get }
var kDSNAttrMapCoordinates: String { get }
var kDSNAttrMapURI: String { get }
var kDSNAttrMCXSettings: String { get }
var kDSNAttrMIME: String { get }
var kDSNAttrMember: String { get }
var kDSNAttrMobileNumber: String { get }
var kDSNAttrNBPEntry: String { get }
var kDSNAttrNestedGroups: String { get }
var kDSNAttrNetGroups: String { get }
var kDSNAttrNickName: String { get }
var kDSNAttrNodePathXMLPlist: String { get }
var kDSNAttrOrganizationInfo: String { get }
var kDSNAttrOrganizationName: String { get }
var kDSNAttrPagerNumber: String { get }
var kDSNAttrPhoneContacts: String { get }
var kDSNAttrPhoneNumber: String { get }
var kDSNAttrPGPPublicKey: String { get }
var kDSNAttrPostalAddress: String { get }
var kDSNAttrPostalAddressContacts: String { get }
var kDSNAttrPostalCode: String { get }
var kDSNAttrNamePrefix: String { get }
var kDSNAttrProtocols: String { get }
var kDSNAttrRecordName: String { get }
var kDSNAttrRelationships: String { get }
var kDSNAttrResourceInfo: String { get }
var kDSNAttrResourceType: String { get }
var kDSNAttrState: String { get }
var kDSNAttrStreet: String { get }
var kDSNAttrNameSuffix: String { get }
var kDSNAttrURL: String { get }
var kDSNAttrURLForNSL: String { get }
var kDSNAttrVFSOpts: String { get }
var kDS1AttrAdminStatus: String { get }
var kDS1AttrAlias: String { get }
var kDS1AttrAuthCredential: String { get }
var kDS1AttrCopyTimestamp: String { get }
var kDS1AttrDateRecordCreated: String { get }
var kDS1AttrKerberosRealm: String { get }
var kDS1AttrNTDomainComputerAccount: String { get }
var kDSNAttrOriginalHomeDirectory: String { get }
var kDS1AttrOriginalNFSHomeDirectory: String { get }
var kDS1AttrOriginalNodeName: String { get }
var kDS1AttrPrimaryNTDomain: String { get }
var kDS1AttrPwdAgingPolicy: String { get }
var kDS1AttrRARA: String { get }
var kDS1AttrReadOnlyNode: String { get }
var kDS1AttrRecordImage: String { get }
var kDS1AttrSMBGroupRID: String { get }
var kDS1AttrTimePackage: String { get }
var kDS1AttrTotalSize: String { get }
var kDSNAttrAllNames: String { get }
var kDSNAttrAuthMethod: String { get }
var kDSNAttrMetaNodeLocation: String { get }
var kDSNAttrNodePath: String { get }
var kDSNAttrPlugInInfo: String { get }
var kDSNAttrRecordAlias: String { get }
var kDSNAttrRecordType: String { get }
var kDSNAttrSchema: String { get }
var kDSNAttrSetPasswdMethod: String { get }
var kDSNAttrSubNodes: String { get }
var kStandardSourceAlias: String { get }
var kStandardTargetAlias: String { get }
var kDSNAttrNetGroupTriplet: String { get }
var kDS1AttrSearchPath: String { get }
var kDSNAttrSearchPath: String { get }
var kDS1AttrSearchPolicy: String { get }
var kDS1AttrNSPSearchPath: String { get }
var kDSNAttrNSPSearchPath: String { get }
var kDS1AttrLSPSearchPath: String { get }
var kDSNAttrLSPSearchPath: String { get }
var kDS1AttrCSPSearchPath: String { get }
var kDSNAttrCSPSearchPath: String { get }
var kDSStdAuthMethodPrefix: String { get }
var kDSNativeAuthMethodPrefix: String { get }
var kDSSetPasswdBestOf: String { get }
var kDSValueAuthAuthorityDefault: String { get }
var kDSValueAuthAuthorityBasic: String { get }
var kDSTagAuthAuthorityBasic: String { get }
var kDSValueAuthAuthorityLocalWindowsHash: String { get }
var kDSTagAuthAuthorityLocalWindowsHash: String { get }
var kDSValueAuthAuthorityShadowHash: String { get }
var kDSTagAuthAuthorityShadowHash: String { get }
var kDSTagAuthAuthorityBetterHashOnly: String { get }
var kDSValueAuthAuthorityPasswordServerPrefix: String { get }
var kDSTagAuthAuthorityPasswordServer: String { get }
var kDSValueAuthAuthorityKerberosv5: String { get }
var kDSTagAuthAuthorityKerberosv5: String { get }
var kDSValueAuthAuthorityLocalCachedUser: String { get }
var kDSTagAuthAuthorityLocalCachedUser: String { get }
var kDSValueAuthAuthorityDisabledUser: String { get }
var kDSTagAuthAuthorityDisabledUser: String { get }
var kDSValueNonCryptPasswordMarker: String { get }
var kDSStdAuth2WayRandom: String { get }
var kDSStdAuth2WayRandomChangePasswd: String { get }
var kDSStdAuthAPOP: String { get }
var kDSStdAuthCHAP: String { get }
var kDSStdAuthCRAM_MD5: String { get }
var kDSStdAuthChangePasswd: String { get }
var kDSStdAuthClearText: String { get }
var kDSStdAuthCrypt: String { get }
var kDSStdAuthDIGEST_MD5: String { get }
var kDSStdAuthDeleteUser: String { get }
var kDSStdAuthGetEffectivePolicy: String { get }
var kDSStdAuthGetGlobalPolicy: String { get }
var kDSStdAuthGetKerberosPrincipal: String { get }
var kDSStdAuthGetPolicy: String { get }
var kDSStdAuthGetUserData: String { get }
var kDSStdAuthGetUserName: String { get }
var kDSStdAuthKerberosTickets: String { get }
var kDSStdAuthMASKE_A: String { get }
var kDSStdAuthMASKE_B: String { get }
var kDSStdAuthMPPEMasterKeys: String { get }
var kDSStdAuthMSCHAP1: String { get }
var kDSStdAuthMSCHAP2: String { get }
var kDSStdAuthNTLMv2: String { get }
var kDSStdAuthNTLMv2WithSessionKey: String { get }
var kDSStdAuthNewUser: String { get }
var kDSStdAuthNewUserWithPolicy: String { get }
var kDSStdAuthNodeNativeClearTextOK: String { get }
var kDSStdAuthNodeNativeNoClearText: String { get }
var kDSStdAuthReadSecureHash: String { get }
var kDSStdAuthSMBNTv2UserSessionKey: String { get }
var kDSStdAuthSMBWorkstationCredentialSessionKey: String { get }
var kDSStdAuthSMB_LM_Key: String { get }
var kDSStdAuthSMB_NT_Key: String { get }
var kDSStdAuthSMB_NT_UserSessionKey: String { get }
var kDSStdAuthSMB_NT_WithUserSessionKey: String { get }
var kDSStdAuthSecureHash: String { get }
var kDSStdAuthSetGlobalPolicy: String { get }
var kDSStdAuthSetLMHash: String { get }
var kDSStdAuthSetNTHash: String { get }
var kDSStdAuthSetPasswd: String { get }
var kDSStdAuthSetPasswdAsRoot: String { get }
var kDSStdAuthSetPolicy: String { get }
var kDSStdAuthSetPolicyAsRoot: String { get }
var kDSStdAuthSetUserData: String { get }
var kDSStdAuthSetUserName: String { get }
var kDSStdAuthSetWorkstationPasswd: String { get }
var kDSStdAuthWithAuthorizationRef: String { get }
var kDSStdAuthWriteSecureHash: String { get }
var kDSStdAuthGetMethodsForUser: String { get }
var kDSValueNSLDynamicNeighborhoodType: String { get }
var kDSValueNSLLocalNeighborhoodType: String { get }
var kDSValueNSLStaticNeighborhoodType: String { get }
var kDSValueNSLTopLevelNeighborhoodType: String { get }
var kDS1AttrBuildVersion: String { get }
var kDS1AttrConfigAvail: String { get }
var kDS1AttrConfigFile: String { get }
var kDS1AttrCoreFWVersion: String { get }
var kDS1AttrFunctionalState: String { get }
var kDS1AttrFWVersion: String { get }
var kDS1AttrPluginIndex: String { get }
var kDS1AttrRefNumTableList: String { get }
var kDS1AttrVersion: String { get }
var kDS1AttrPIDValue: String { get }
var kDS1AttrProcessName: String { get }
var kDS1AttrTotalRefCount: String { get }
var kDS1AttrDirRefCount: String { get }
var kDS1AttrNodeRefCount: String { get }
var kDS1AttrRecRefCount: String { get }
var kDS1AttrAttrListRefCount: String { get }
var kDS1AttrAttrListValueRefCount: String { get }
var kDSNAttrDirRefs: String { get }
var kDSNAttrNodeRefs: String { get }
var kDSNAttrRecRefs: String { get }
var kDSNAttrAttrListRefs: String { get }
var kDSNAttrAttrListValueRefs: String { get }
