
let NSTextLineTooLongException: String
let NSTextNoSelectionException: String
let NSWordTablesWriteException: String
let NSWordTablesReadException: String
let NSTextReadException: String
let NSTextWriteException: String
let NSPasteboardCommunicationException: String
let NSPrintingCommunicationException: String
let NSAbortModalException: String
let NSAbortPrintingException: String
let NSIllegalSelectorException: String
let NSAppKitVirtualMemoryException: String
let NSBadRTFDirectiveException: String
let NSBadRTFFontTableException: String
let NSBadRTFStyleSheetException: String
let NSTypedStreamVersionException: String
let NSTIFFException: String
let NSPrintPackageException: String
let NSBadRTFColorTableException: String
let NSDraggingException: String
let NSColorListIOException: String
let NSColorListNotEditableException: String
let NSBadBitmapParametersException: String
let NSWindowServerCommunicationException: String
let NSFontUnavailableException: String
let NSPPDIncludeNotFoundException: String
let NSPPDParseException: String
let NSPPDIncludeStackOverflowException: String
let NSPPDIncludeStackUnderflowException: String
let NSRTFPropertyStackOverflowException: String
let NSAppKitIgnoredException: String
let NSBadComparisonException: String
let NSImageCacheException: String
let NSNibLoadingException: String
let NSBrowserIllegalDelegateException: String
@available(OSX, introduced: 10.1, deprecated: 10.11, message: "Exceptions are no longer appropriate for indicating errors in accessibility API. Unexpected values should be handled through appropriate type checking.")
let NSAccessibilityException: String
