#!/bin/bash

SWIFT_PATH=/home/amr/swift
PATH=/home/amr/resources/git-plus:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PARAM=x$1
cd $SWIFT_PATH

if [ ${PARAM} = "x-c" ] ; then
echo ========== Cleaning ===========
PARAM="x-u"
rm -rf build
rm -f swift/*.tar.gz
fi

if [ ${PARAM} = "x-u" ] ; then
echo ========== Syncing ==========
git multi pull
git multi fetch upstream
git multi merge upstream/master
fi

echo ========== Running script ==========
./swift/utils/build-toolchain local.swift || exit

echo ========== Finishing ==========
cd $SWIFT_PATH
test -e swift/swift-nightly-install || exit 
rm -rf toolchains/swift-toolchain-$(date "+%u")
mv toolchains/swift-toolchain toolchains/swift-toolchain-$(date "+%u")
cp -r swift/swift-nightly-install toolchains/swift-toolchain

