#!/bin/bash

#echo ========== Setup ===========
SWIFT_PATH=/home/amr/swift
PATH=/home/amr/resources/git-plus:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cd $SWIFT_PATH
#rm -rf build
#mkdir -p build/buildbot_linux/swift-linux-x86_64/lib/swift/linux/x86_64
#cp $SWIFT_PATH/toolchains/swift-preview/usr/lib/swift/linux/x86_64/glibc.modulemap $SWIFT_PATH/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux/x86_64
#rm -f swift/*.tar.gz

#echo ========== Syncing ==========
git multi commit -am "auto commit from build-toolchain-daily"
git multi push
git multi checkout stable
git multi checkout master
git multi pull
git multi fetch upstream
git multi merge upstream/master
git multi push
git multi checkout develop
git multi pull
git multi merge master
git multi push

echo ========== Running script ==========
./swift/utils/build-toolchain local.swift

echo ========== Finishing ==========
cd $SWIFT_PATH
test -e swift/swift-nightly-install || exit 
rm -rf toolchains/swift-toolchain-$(date "+%u")
mv toolchains/swift-toolchain toolchains/swift-toolchain-$(date "+%u")
cp swift/swift-nightly-install toolchains/swift-toolchain

