
typealias CMIOControlID = CMIOObjectID
var kCMIOControlClassID: Int { get }
var kCMIOBooleanControlClassID: Int { get }
var kCMIOSelectorControlClassID: Int { get }
var kCMIOFeatureControlClassID: Int { get }
var kCMIOJackControlClassID: Int { get }
var kCMIODirectionControlClassID: Int { get }
var kCMIODataSourceControlClassID: Int { get }
var kCMIODataDestinationControlClassID: Int { get }
var kCMIOBlackLevelControlClassID: Int { get }
var kCMIOWhiteLevelControlClassID: Int { get }
var kCMIOHueControlClassID: Int { get }
var kCMIOSaturationControlClassID: Int { get }
var kCMIOContrastControlClassID: Int { get }
var kCMIOSharpnessControlClassID: Int { get }
var kCMIOBrightnessControlClassID: Int { get }
var kCMIOGainControlClassID: Int { get }
var kCMIOIrisControlClassID: Int { get }
var kCMIOShutterControlClassID: Int { get }
var kCMIOExposureControlClassID: Int { get }
var kCMIOWhiteBalanceUControlClassID: Int { get }
var kCMIOWhiteBalanceVControlClassID: Int { get }
var kCMIOWhiteBalanceControlClassID: Int { get }
var kCMIOGammaControlClassID: Int { get }
var kCMIOTemperatureControlClassID: Int { get }
var kCMIOZoomControlClassID: Int { get }
var kCMIOFocusControlClassID: Int { get }
var kCMIOPanControlClassID: Int { get }
var kCMIOTiltControlClassID: Int { get }
var kCMIOOpticalFilterClassID: Int { get }
var kCMIOBacklightCompensationControlClassID: Int { get }
var kCMIOPowerLineFrequencyControlClassID: Int { get }
var kCMIONoiseReductionControlClassID: Int { get }
var kCMIOControlPropertyScope: Int { get }
var kCMIOControlPropertyElement: Int { get }
var kCMIOControlPropertyVariant: Int { get }
var kCMIOBooleanControlPropertyValue: Int { get }
var kCMIOSelectorControlPropertyCurrentItem: Int { get }
var kCMIOSelectorControlPropertyAvailableItems: Int { get }
var kCMIOSelectorControlPropertyItemName: Int { get }
var kCMIOFeatureControlPropertyOnOff: Int { get }
var kCMIOFeatureControlPropertyAutomaticManual: Int { get }
var kCMIOFeatureControlPropertyAbsoluteNative: Int { get }
var kCMIOFeatureControlPropertyTune: Int { get }
var kCMIOFeatureControlPropertyNativeValue: Int { get }
var kCMIOFeatureControlPropertyAbsoluteValue: Int { get }
var kCMIOFeatureControlPropertyNativeRange: Int { get }
var kCMIOFeatureControlPropertyAbsoluteRange: Int { get }
var kCMIOFeatureControlPropertyConvertNativeToAbsolute: Int { get }
var kCMIOFeatureControlPropertyConvertAbsoluteToNative: Int { get }
var kCMIOFeatureControlPropertyAbsoluteUnitName: Int { get }
var kCMIOExposureControlPropertyRegionOfInterest: Int { get }
var kCMIOExposureControlPropertyLockThreshold: Int { get }
var kCMIOExposureControlPropertyUnlockThreshold: Int { get }
var kCMIOExposureControlPropertyTarget: Int { get }
var kCMIOExposureControlPropertyConvergenceSpeed: Int { get }
var kCMIOExposureControlPropertyStability: Int { get }
var kCMIOExposureControlPropertyStable: Int { get }
var kCMIOExposureControlPropertyIntegrationTime: Int { get }
var kCMIOExposureControlPropertyMaximumGain: Int { get }
