# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for Swift project authors

FROM ubuntu:16.04
# Install related packages.
RUN apt-get -q update && \
    apt-get -q install -y \
    git \
    cmake \
    ninja-build \
    clang \
    python \
	uuid-dev \
	libicu-dev \
	icu-devtools \
	libbsd-dev \
	libedit-dev \
	libxml2-dev \
	libsqlite3-dev \
	swig \
	libpython-dev \
	libncurses5-dev \
	pkg-config \
	libblocksruntime-dev \
	libcurl4-openssl-dev \
	systemtap-sdt-dev \
	tzdata \
	rsync
