
extension NSObject {
  class func webPlugInInitialize()
  func webPlugInInitialize()
  class func webPlugInStart()
  func webPlugInStart()
  class func webPlugInStop()
  func webPlugInStop()
  class func webPlugInDestroy()
  func webPlugInDestroy()
  class func webPlug(inSetIsSelected isSelected: Bool)
  func webPlug(inSetIsSelected isSelected: Bool)
  var objectForWebScript: AnyObject! { get }
  @available(OSX 10.6, *)
  class func webPlug(inMainResourceDidReceive response: NSURLResponse!)
  @available(OSX 10.6, *)
  func webPlug(inMainResourceDidReceive response: NSURLResponse!)
  @available(OSX 10.6, *)
  class func webPlug(inMainResourceDidReceive data: NSData!)
  @available(OSX 10.6, *)
  func webPlug(inMainResourceDidReceive data: NSData!)
  @available(OSX 10.6, *)
  class func webPlugInMainResourceDidFailWithError(_ error: NSError!)
  @available(OSX 10.6, *)
  func webPlugInMainResourceDidFailWithError(_ error: NSError!)
  @available(OSX 10.6, *)
  class func webPlugInMainResourceDidFinishLoading()
  @available(OSX 10.6, *)
  func webPlugInMainResourceDidFinishLoading()
  class func objectForWebScript() -> AnyObject!
}
