
var kAudioSessionNoError: Int { get }
var kAudioSessionNotInitialized: Int { get }
var kAudioSessionAlreadyInitialized: Int { get }
var kAudioSessionInitializationError: Int { get }
var kAudioSessionUnsupportedPropertyError: Int { get }
var kAudioSessionBadPropertySizeError: Int { get }
var kAudioSessionNotActiveError: Int { get }
var kAudioServicesNoHardwareError: Int { get }
var kAudioSessionNoCategorySet: Int { get }
var kAudioSessionIncompatibleCategory: Int { get }
var kAudioSessionUnspecifiedError: Int { get }
typealias AudioSessionPropertyID = UInt32
var kAudioSessionBeginInterruption: Int { get }
var kAudioSessionEndInterruption: Int { get }
var kAudioSessionCategory_AmbientSound: Int { get }
var kAudioSessionCategory_SoloAmbientSound: Int { get }
var kAudioSessionCategory_MediaPlayback: Int { get }
var kAudioSessionCategory_RecordAudio: Int { get }
var kAudioSessionCategory_PlayAndRecord: Int { get }
var kAudioSessionCategory_AudioProcessing: Int { get }
var kAudioSessionOverrideAudioRoute_None: Int { get }
var kAudioSessionOverrideAudioRoute_Speaker: Int { get }
var kAudioSessionRouteChangeReason_Unknown: Int { get }
var kAudioSessionRouteChangeReason_NewDeviceAvailable: Int { get }
var kAudioSessionRouteChangeReason_OldDeviceUnavailable: Int { get }
var kAudioSessionRouteChangeReason_CategoryChange: Int { get }
var kAudioSessionRouteChangeReason_Override: Int { get }
var kAudioSessionRouteChangeReason_WakeFromSleep: Int { get }
var kAudioSessionRouteChangeReason_NoSuitableRouteForCategory: Int { get }
var kAudioSessionRouteChangeReason_RouteConfigurationChange: Int { get }
var kAudioSession_AudioRouteChangeKey_Reason: String { get }
var kAudioSessionInterruptionType_ShouldResume: Int { get }
var kAudioSessionInterruptionType_ShouldNotResume: Int { get }
typealias AudioSessionInterruptionType = UInt32
var kAudioSessionMode_Default: Int { get }
var kAudioSessionMode_VoiceChat: Int { get }
var kAudioSessionMode_VideoRecording: Int { get }
var kAudioSessionMode_Measurement: Int { get }
var kAudioSessionMode_GameChat: Int { get }
var kAudioSessionProperty_PreferredHardwareSampleRate: Int { get }
var kAudioSessionProperty_PreferredHardwareIOBufferDuration: Int { get }
var kAudioSessionProperty_AudioCategory: Int { get }
var kAudioSessionProperty_AudioRouteChange: Int { get }
var kAudioSessionProperty_CurrentHardwareSampleRate: Int { get }
var kAudioSessionProperty_CurrentHardwareInputNumberChannels: Int { get }
var kAudioSessionProperty_CurrentHardwareOutputNumberChannels: Int { get }
var kAudioSessionProperty_CurrentHardwareOutputVolume: Int { get }
var kAudioSessionProperty_CurrentHardwareInputLatency: Int { get }
var kAudioSessionProperty_CurrentHardwareOutputLatency: Int { get }
var kAudioSessionProperty_CurrentHardwareIOBufferDuration: Int { get }
var kAudioSessionProperty_OtherAudioIsPlaying: Int { get }
var kAudioSessionProperty_OverrideAudioRoute: Int { get }
var kAudioSessionProperty_AudioInputAvailable: Int { get }
var kAudioSessionProperty_ServerDied: Int { get }
var kAudioSessionProperty_OtherMixableAudioShouldDuck: Int { get }
var kAudioSessionProperty_OverrideCategoryMixWithOthers: Int { get }
var kAudioSessionProperty_OverrideCategoryDefaultToSpeaker: Int { get }
var kAudioSessionProperty_OverrideCategoryEnableBluetoothInput: Int { get }
var kAudioSessionProperty_InterruptionType: Int { get }
var kAudioSessionProperty_Mode: Int { get }
var kAudioSessionProperty_InputSources: Int { get }
var kAudioSessionProperty_OutputDestinations: Int { get }
var kAudioSessionProperty_InputSource: Int { get }
var kAudioSessionProperty_OutputDestination: Int { get }
var kAudioSessionProperty_InputGainAvailable: Int { get }
var kAudioSessionProperty_InputGainScalar: Int { get }
var kAudioSessionProperty_AudioRouteDescription: Int { get }
typealias AudioSessionInterruptionListener = @convention(c) (UnsafeMutablePointer<Void>!, UInt32) -> Void
typealias AudioSessionPropertyListener = @convention(c) (UnsafeMutablePointer<Void>!, AudioSessionPropertyID, UInt32, UnsafePointer<Void>!) -> Void
var kAudioSessionSetActiveFlag_NotifyOthersOnDeactivation: Int { get }
var kAudioSessionCategory_UserInterfaceSoundEffects: Int { get }
var kAudioSessionCategory_LiveAudio: Int { get }
var kAudioSessionProperty_AudioRoute: Int { get }
var kAudioSession_AudioRouteChangeKey_OldRoute: String { get }
