
var GLUT_API_VERSION: Int32 { get }
var GLUT_XLIB_IMPLEMENTATION: Int32 { get }
var GLUT_MACOSX_IMPLEMENTATION: Int32 { get }
var GLUT_RGB: Int32 { get }
var GLUT_RGBA: Int32 { get }
var GLUT_INDEX: Int32 { get }
var GLUT_SINGLE: Int32 { get }
var GLUT_DOUBLE: Int32 { get }
var GLUT_ACCUM: Int32 { get }
var GLUT_ALPHA: Int32 { get }
var GLUT_DEPTH: Int32 { get }
var GLUT_STENCIL: Int32 { get }
var GLUT_MULTISAMPLE: Int32 { get }
var GLUT_STEREO: Int32 { get }
var GLUT_LUMINANCE: Int32 { get }
var GLUT_NO_RECOVERY: Int32 { get }
var GLUT_3_2_CORE_PROFILE: Int32 { get }
var GLUT_LEFT_BUTTON: Int32 { get }
var GLUT_MIDDLE_BUTTON: Int32 { get }
var GLUT_RIGHT_BUTTON: Int32 { get }
var GLUT_DOWN: Int32 { get }
var GLUT_UP: Int32 { get }
var GLUT_KEY_F1: Int32 { get }
var GLUT_KEY_F2: Int32 { get }
var GLUT_KEY_F3: Int32 { get }
var GLUT_KEY_F4: Int32 { get }
var GLUT_KEY_F5: Int32 { get }
var GLUT_KEY_F6: Int32 { get }
var GLUT_KEY_F7: Int32 { get }
var GLUT_KEY_F8: Int32 { get }
var GLUT_KEY_F9: Int32 { get }
var GLUT_KEY_F10: Int32 { get }
var GLUT_KEY_F11: Int32 { get }
var GLUT_KEY_F12: Int32 { get }
var GLUT_KEY_LEFT: Int32 { get }
var GLUT_KEY_UP: Int32 { get }
var GLUT_KEY_RIGHT: Int32 { get }
var GLUT_KEY_DOWN: Int32 { get }
var GLUT_KEY_PAGE_UP: Int32 { get }
var GLUT_KEY_PAGE_DOWN: Int32 { get }
var GLUT_KEY_HOME: Int32 { get }
var GLUT_KEY_END: Int32 { get }
var GLUT_KEY_INSERT: Int32 { get }
var GLUT_LEFT: Int32 { get }
var GLUT_ENTERED: Int32 { get }
var GLUT_MENU_NOT_IN_USE: Int32 { get }
var GLUT_MENU_IN_USE: Int32 { get }
var GLUT_NOT_VISIBLE: Int32 { get }
var GLUT_VISIBLE: Int32 { get }
var GLUT_HIDDEN: Int32 { get }
var GLUT_FULLY_RETAINED: Int32 { get }
var GLUT_PARTIALLY_RETAINED: Int32 { get }
var GLUT_FULLY_COVERED: Int32 { get }
var GLUT_RED: Int32 { get }
var GLUT_GREEN: Int32 { get }
var GLUT_BLUE: Int32 { get }
var glutStrokeRoman: UnsafeMutablePointer<Void>!
var glutStrokeMonoRoman: UnsafeMutablePointer<Void>!
var glutBitmap9By15: UnsafeMutablePointer<Void>!
var glutBitmap8By13: UnsafeMutablePointer<Void>!
var glutBitmapTimesRoman10: UnsafeMutablePointer<Void>!
var glutBitmapTimesRoman24: UnsafeMutablePointer<Void>!
var glutBitmapHelvetica10: UnsafeMutablePointer<Void>!
var glutBitmapHelvetica12: UnsafeMutablePointer<Void>!
var glutBitmapHelvetica18: UnsafeMutablePointer<Void>!
var GLUT_WINDOW_X: Int32 { get }
var GLUT_WINDOW_Y: Int32 { get }
var GLUT_WINDOW_WIDTH: Int32 { get }
var GLUT_WINDOW_HEIGHT: Int32 { get }
var GLUT_WINDOW_BUFFER_SIZE: Int32 { get }
var GLUT_WINDOW_STENCIL_SIZE: Int32 { get }
var GLUT_WINDOW_DEPTH_SIZE: Int32 { get }
var GLUT_WINDOW_RED_SIZE: Int32 { get }
var GLUT_WINDOW_GREEN_SIZE: Int32 { get }
var GLUT_WINDOW_BLUE_SIZE: Int32 { get }
var GLUT_WINDOW_ALPHA_SIZE: Int32 { get }
var GLUT_WINDOW_ACCUM_RED_SIZE: Int32 { get }
var GLUT_WINDOW_ACCUM_GREEN_SIZE: Int32 { get }
var GLUT_WINDOW_ACCUM_BLUE_SIZE: Int32 { get }
var GLUT_WINDOW_ACCUM_ALPHA_SIZE: Int32 { get }
var GLUT_WINDOW_DOUBLEBUFFER: Int32 { get }
var GLUT_WINDOW_RGBA: Int32 { get }
var GLUT_WINDOW_PARENT: Int32 { get }
var GLUT_WINDOW_NUM_CHILDREN: Int32 { get }
var GLUT_WINDOW_COLORMAP_SIZE: Int32 { get }
var GLUT_WINDOW_NUM_SAMPLES: Int32 { get }
var GLUT_WINDOW_STEREO: Int32 { get }
var GLUT_WINDOW_CURSOR: Int32 { get }
var GLUT_SCREEN_WIDTH: Int32 { get }
var GLUT_SCREEN_HEIGHT: Int32 { get }
var GLUT_SCREEN_WIDTH_MM: Int32 { get }
var GLUT_SCREEN_HEIGHT_MM: Int32 { get }
var GLUT_MENU_NUM_ITEMS: Int32 { get }
var GLUT_DISPLAY_MODE_POSSIBLE: Int32 { get }
var GLUT_INIT_WINDOW_X: Int32 { get }
var GLUT_INIT_WINDOW_Y: Int32 { get }
var GLUT_INIT_WINDOW_WIDTH: Int32 { get }
var GLUT_INIT_WINDOW_HEIGHT: Int32 { get }
var GLUT_INIT_DISPLAY_MODE: Int32 { get }
var GLUT_ELAPSED_TIME: Int32 { get }
var GLUT_WINDOW_FORMAT_ID: Int32 { get }
var GLUT_HAS_KEYBOARD: Int32 { get }
var GLUT_HAS_MOUSE: Int32 { get }
var GLUT_HAS_SPACEBALL: Int32 { get }
var GLUT_HAS_DIAL_AND_BUTTON_BOX: Int32 { get }
var GLUT_HAS_TABLET: Int32 { get }
var GLUT_NUM_MOUSE_BUTTONS: Int32 { get }
var GLUT_NUM_SPACEBALL_BUTTONS: Int32 { get }
var GLUT_NUM_BUTTON_BOX_BUTTONS: Int32 { get }
var GLUT_NUM_DIALS: Int32 { get }
var GLUT_NUM_TABLET_BUTTONS: Int32 { get }
var GLUT_DEVICE_IGNORE_KEY_REPEAT: Int32 { get }
var GLUT_DEVICE_KEY_REPEAT: Int32 { get }
var GLUT_HAS_JOYSTICK: Int32 { get }
var GLUT_OWNS_JOYSTICK: Int32 { get }
var GLUT_JOYSTICK_BUTTONS: Int32 { get }
var GLUT_JOYSTICK_AXES: Int32 { get }
var GLUT_JOYSTICK_POLL_RATE: Int32 { get }
var GLUT_OVERLAY_POSSIBLE: Int32 { get }
var GLUT_LAYER_IN_USE: Int32 { get }
var GLUT_HAS_OVERLAY: Int32 { get }
var GLUT_TRANSPARENT_INDEX: Int32 { get }
var GLUT_NORMAL_DAMAGED: Int32 { get }
var GLUT_OVERLAY_DAMAGED: Int32 { get }
var GLUT_VIDEO_RESIZE_POSSIBLE: Int32 { get }
var GLUT_VIDEO_RESIZE_IN_USE: Int32 { get }
var GLUT_VIDEO_RESIZE_X_DELTA: Int32 { get }
var GLUT_VIDEO_RESIZE_Y_DELTA: Int32 { get }
var GLUT_VIDEO_RESIZE_WIDTH_DELTA: Int32 { get }
var GLUT_VIDEO_RESIZE_HEIGHT_DELTA: Int32 { get }
var GLUT_VIDEO_RESIZE_X: Int32 { get }
var GLUT_VIDEO_RESIZE_Y: Int32 { get }
var GLUT_VIDEO_RESIZE_WIDTH: Int32 { get }
var GLUT_VIDEO_RESIZE_HEIGHT: Int32 { get }
var GLUT_NORMAL: Int32 { get }
var GLUT_OVERLAY: Int32 { get }
var GLUT_ACTIVE_SHIFT: Int32 { get }
var GLUT_ACTIVE_CTRL: Int32 { get }
var GLUT_ACTIVE_ALT: Int32 { get }
var GLUT_CURSOR_RIGHT_ARROW: Int32 { get }
var GLUT_CURSOR_LEFT_ARROW: Int32 { get }
var GLUT_CURSOR_INFO: Int32 { get }
var GLUT_CURSOR_DESTROY: Int32 { get }
var GLUT_CURSOR_HELP: Int32 { get }
var GLUT_CURSOR_CYCLE: Int32 { get }
var GLUT_CURSOR_SPRAY: Int32 { get }
var GLUT_CURSOR_WAIT: Int32 { get }
var GLUT_CURSOR_TEXT: Int32 { get }
var GLUT_CURSOR_CROSSHAIR: Int32 { get }
var GLUT_CURSOR_UP_DOWN: Int32 { get }
var GLUT_CURSOR_LEFT_RIGHT: Int32 { get }
var GLUT_CURSOR_TOP_SIDE: Int32 { get }
var GLUT_CURSOR_BOTTOM_SIDE: Int32 { get }
var GLUT_CURSOR_LEFT_SIDE: Int32 { get }
var GLUT_CURSOR_RIGHT_SIDE: Int32 { get }
var GLUT_CURSOR_TOP_LEFT_CORNER: Int32 { get }
var GLUT_CURSOR_TOP_RIGHT_CORNER: Int32 { get }
var GLUT_CURSOR_BOTTOM_RIGHT_CORNER: Int32 { get }
var GLUT_CURSOR_BOTTOM_LEFT_CORNER: Int32 { get }
var GLUT_CURSOR_INHERIT: Int32 { get }
var GLUT_CURSOR_NONE: Int32 { get }
var GLUT_CURSOR_FULL_CROSSHAIR: Int32 { get }
var GLUT_KEY_REPEAT_OFF: Int32 { get }
var GLUT_KEY_REPEAT_ON: Int32 { get }
var GLUT_KEY_REPEAT_DEFAULT: Int32 { get }
var GLUT_JOYSTICK_BUTTON_A: Int32 { get }
var GLUT_JOYSTICK_BUTTON_B: Int32 { get }
var GLUT_JOYSTICK_BUTTON_C: Int32 { get }
var GLUT_JOYSTICK_BUTTON_D: Int32 { get }
var GLUT_GAME_MODE_ACTIVE: Int32 { get }
var GLUT_GAME_MODE_POSSIBLE: Int32 { get }
var GLUT_GAME_MODE_WIDTH: Int32 { get }
var GLUT_GAME_MODE_HEIGHT: Int32 { get }
var GLUT_GAME_MODE_PIXEL_DEPTH: Int32 { get }
var GLUT_GAME_MODE_REFRESH_RATE: Int32 { get }
var GLUT_GAME_MODE_DISPLAY_CHANGED: Int32 { get }
