// RUN: %swift-ide-test -generate-api-annotation -o %t
// RUN: llvm-bcanalyzer %t | FileCheck %s
// RUN: %swift-ide-test -check-api-annotation %t

// CHECK: Block ID #0 (BLOCKINFO_BLOCK)
// CHECK: Block ID #[[IDENTIFIER_BLOCK:[0-9]+]] (IDENTIFIER_BLOCK)
// CHECK: IDENTIFIER_DATA
// CHECK: Block ID #[[OBJC_CLASS_BLOCK:[0-9]+]] (OBJC_CLASS_BLOCK)
// CHECK: OBJC_CLASS_DATA
// CHECK: Block ID #[[OBJC_PROPERTY_BLOCK:[0-9]+]] (OBJC_PROPERTY_BLOCK)
// CHECK: OBJC_PROPERTY_DATA
// CHECK: Block ID #[[OBJC_METHOD_BLOCK:[0-9]+]] (OBJC_METHOD_BLOCK)
// CHECK: OBJC_METHOD_DATA
// CHECK: Block ID #[[OBJC_SELECTOR_BLOCK:[0-9]+]] (OBJC_SELECTOR_BLOCK)
// CHECK: OBJC_SELECTOR_DATA
