
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBodyMassIndex: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBodyFatPercentage: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierHeight: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBodyMass: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierLeanBodyMass: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierStepCount: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDistanceWalkingRunning: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDistanceCycling: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBasalEnergyBurned: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierActiveEnergyBurned: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierFlightsClimbed: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierNikeFuel: String
@available(watchOS 2.2, *)
let HKQuantityTypeIdentifierAppleExerciseTime: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierHeartRate: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBodyTemperature: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBasalBodyTemperature: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBloodPressureSystolic: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBloodPressureDiastolic: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierRespiratoryRate: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierOxygenSaturation: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierPeripheralPerfusionIndex: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBloodGlucose: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierNumberOfTimesFallen: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierElectrodermalActivity: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierInhalerUsage: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierBloodAlcoholContent: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierForcedVitalCapacity: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierForcedExpiratoryVolume1: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierPeakExpiratoryFlowRate: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFatTotal: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFatPolyunsaturated: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFatMonounsaturated: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFatSaturated: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryCholesterol: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietarySodium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryCarbohydrates: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFiber: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietarySugar: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryEnergyConsumed: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryProtein: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminA: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminB6: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminB12: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminC: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminD: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminE: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryVitaminK: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryCalcium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryIron: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryThiamin: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryRiboflavin: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryNiacin: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryFolate: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryBiotin: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryPantothenicAcid: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryPhosphorus: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryIodine: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryMagnesium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryZinc: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietarySelenium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryCopper: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryManganese: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryChromium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryMolybdenum: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryChloride: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryPotassium: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryCaffeine: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierDietaryWater: String
@available(watchOS 2.0, *)
let HKQuantityTypeIdentifierUVExposure: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierSleepAnalysis: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierAppleStandHour: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierCervicalMucusQuality: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierOvulationTestResult: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierMenstrualFlow: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierIntermenstrualBleeding: String
@available(watchOS 2.0, *)
let HKCategoryTypeIdentifierSexualActivity: String
@available(watchOS 2.0, *)
let HKCharacteristicTypeIdentifierBiologicalSex: String
@available(watchOS 2.0, *)
let HKCharacteristicTypeIdentifierBloodType: String
@available(watchOS 2.0, *)
let HKCharacteristicTypeIdentifierDateOfBirth: String
@available(watchOS 2.0, *)
let HKCharacteristicTypeIdentifierFitzpatrickSkinType: String
@available(watchOS 2.0, *)
let HKCorrelationTypeIdentifierBloodPressure: String
@available(watchOS 2.0, *)
let HKCorrelationTypeIdentifierFood: String
@available(watchOS 2.0, *)
let HKWorkoutTypeIdentifier: String
