
typealias SSLCipherSuite = UInt32
var SSL_NULL_WITH_NULL_NULL: SSLCipherSuite { get }
var SSL_RSA_WITH_NULL_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_NULL_SHA: SSLCipherSuite { get }
var SSL_RSA_EXPORT_WITH_RC4_40_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_RC4_128_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_IDEA_CBC_SHA: SSLCipherSuite { get }
var SSL_RSA_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_RSA_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_DSS_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_RSA_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_DSS_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_RSA_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_anon_EXPORT_WITH_RC4_40_MD5: SSLCipherSuite { get }
var SSL_DH_anon_WITH_RC4_128_MD5: SSLCipherSuite { get }
var SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_anon_WITH_DES_CBC_SHA: SSLCipherSuite { get }
var SSL_DH_anon_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var SSL_FORTEZZA_DMS_WITH_NULL_SHA: SSLCipherSuite { get }
var SSL_FORTEZZA_DMS_WITH_FORTEZZA_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_anon_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_ECDH_anon_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_anon_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_ECDH_anon_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_NULL_WITH_NULL_NULL: SSLCipherSuite { get }
var TLS_RSA_WITH_NULL_MD5: SSLCipherSuite { get }
var TLS_RSA_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_RC4_128_MD5: SSLCipherSuite { get }
var TLS_RSA_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_NULL_SHA256: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_anon_WITH_RC4_128_MD5: SSLCipherSuite { get }
var TLS_DH_anon_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_256_CBC_SHA256: SSLCipherSuite { get }
var TLS_PSK_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_PSK_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_RC4_128_SHA: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_128_CBC_SHA: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_256_CBC_SHA: SSLCipherSuite { get }
var TLS_PSK_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_NULL_SHA: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_RSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DHE_RSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DH_RSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DHE_DSS_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DH_DSS_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DH_anon_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_PSK_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_PSK_WITH_NULL_SHA256: SSLCipherSuite { get }
var TLS_PSK_WITH_NULL_SHA384: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_NULL_SHA256: SSLCipherSuite { get }
var TLS_DHE_PSK_WITH_NULL_SHA384: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_NULL_SHA256: SSLCipherSuite { get }
var TLS_RSA_PSK_WITH_NULL_SHA384: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256: SSLCipherSuite { get }
var TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384: SSLCipherSuite { get }
var TLS_EMPTY_RENEGOTIATION_INFO_SCSV: SSLCipherSuite { get }
var SSL_RSA_WITH_RC2_CBC_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_IDEA_CBC_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_DES_CBC_MD5: SSLCipherSuite { get }
var SSL_RSA_WITH_3DES_EDE_CBC_MD5: SSLCipherSuite { get }
var SSL_NO_SUCH_CIPHERSUITE: SSLCipherSuite { get }
