
struct cssm_spi_kr_funcs {
  var RegistrationRequest: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, UnsafePointer<cssm_access_credentials>!, CSSM_KR_POLICY_FLAGS, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!) -> CSSM_RETURN)!
  var RegistrationRetrieve: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<sint32>!, UnsafeMutablePointer<cssm_kr_profile>!) -> CSSM_RETURN)!
  var GenerateRecoveryFields: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, CSSM_KR_POLICY_FLAGS, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!
  var ProcessRecoveryFields: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, CSSM_KR_POLICY_FLAGS, UnsafePointer<cssm_data>!) -> CSSM_RETURN)!
  var RecoveryRequest: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, UnsafePointer<cssm_access_credentials>!, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!) -> CSSM_RETURN)!
  var RecoveryRetrieve: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!, UnsafeMutablePointer<uint32>!) -> CSSM_RETURN)!
  var GetRecoveredObject: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, uint32, CSSM_CSP_HANDLE, UnsafePointer<cssm_resource_control_context>!, uint32, UnsafeMutablePointer<cssm_key>!, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!
  var RecoveryRequestAbort: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE) -> CSSM_RETURN)!
  var PassThrough: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, uint32, UnsafePointer<Void>!, UnsafeMutablePointer<UnsafeMutablePointer<Void>?>!) -> CSSM_RETURN)!
  init()
  init(RegistrationRequest RegistrationRequest: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, UnsafePointer<cssm_access_credentials>!, CSSM_KR_POLICY_FLAGS, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!) -> CSSM_RETURN)!, RegistrationRetrieve RegistrationRetrieve: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<sint32>!, UnsafeMutablePointer<cssm_kr_profile>!) -> CSSM_RETURN)!, GenerateRecoveryFields GenerateRecoveryFields: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, CSSM_KR_POLICY_FLAGS, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!, ProcessRecoveryFields ProcessRecoveryFields: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, CSSM_KR_POLICY_FLAGS, UnsafePointer<cssm_data>!) -> CSSM_RETURN)!, RecoveryRequest RecoveryRequest: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, UnsafePointer<cssm_data>!, UnsafePointer<cssm_access_credentials>!, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!) -> CSSM_RETURN)!, RecoveryRetrieve RecoveryRetrieve: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<sint32>!, CSSM_HANDLE_PTR!, UnsafeMutablePointer<uint32>!) -> CSSM_RETURN)!, GetRecoveredObject GetRecoveredObject: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE, uint32, CSSM_CSP_HANDLE, UnsafePointer<cssm_resource_control_context>!, uint32, UnsafeMutablePointer<cssm_key>!, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!, RecoveryRequestAbort RecoveryRequestAbort: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_HANDLE) -> CSSM_RETURN)!, PassThrough PassThrough: (@convention(c) (CSSM_KRSP_HANDLE, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, CSSM_CC_HANDLE, UnsafePointer<cssm_context>!, uint32, UnsafePointer<Void>!, UnsafeMutablePointer<UnsafeMutablePointer<Void>?>!) -> CSSM_RETURN)!)
}
