
typealias MDS_HANDLE = CSSM_DL_HANDLE
typealias MDS_DB_HANDLE = cssm_dl_db_handle
struct mds_funcs {
  var DbOpen: (@convention(c) (MDS_HANDLE, UnsafePointer<Int8>!, UnsafePointer<cssm_net_address>!, CSSM_DB_ACCESS_TYPE, UnsafePointer<cssm_access_credentials>!, UnsafePointer<Void>!, UnsafeMutablePointer<CSSM_DB_HANDLE>!) -> CSSM_RETURN)!
  var DbClose: (@convention(c) (MDS_DB_HANDLE) -> CSSM_RETURN)!
  var GetDbNames: (@convention(c) (MDS_HANDLE, UnsafeMutablePointer<UnsafeMutablePointer<cssm_name_list>?>!) -> CSSM_RETURN)!
  var GetDbNameFromHandle: (@convention(c) (MDS_DB_HANDLE, UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>!) -> CSSM_RETURN)!
  var FreeNameList: (@convention(c) (MDS_HANDLE, UnsafeMutablePointer<cssm_name_list>!) -> CSSM_RETURN)!
  var DataInsert: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafePointer<cssm_db_record_attribute_data>!, UnsafePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!
  var DataDelete: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_db_unique_record>!) -> CSSM_RETURN)!
  var DataModify: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafeMutablePointer<cssm_db_unique_record>!, UnsafePointer<cssm_db_record_attribute_data>!, UnsafePointer<cssm_data>!, CSSM_DB_MODIFY_MODE) -> CSSM_RETURN)!
  var DataGetFirst: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_query>!, CSSM_HANDLE_PTR!, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!
  var DataGetNext: (@convention(c) (MDS_DB_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!
  var DataAbortQuery: (@convention(c) (MDS_DB_HANDLE, CSSM_HANDLE) -> CSSM_RETURN)!
  var DataGetFromUniqueRecordId: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_db_unique_record>!, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!
  var FreeUniqueRecord: (@convention(c) (MDS_DB_HANDLE, UnsafeMutablePointer<cssm_db_unique_record>!) -> CSSM_RETURN)!
  var CreateRelation: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafePointer<Int8>!, uint32, UnsafePointer<cssm_db_schema_attribute_info>!, uint32, UnsafePointer<cssm_db_schema_index_info>!) -> CSSM_RETURN)!
  var DestroyRelation: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE) -> CSSM_RETURN)!
  init()
  init(DbOpen DbOpen: (@convention(c) (MDS_HANDLE, UnsafePointer<Int8>!, UnsafePointer<cssm_net_address>!, CSSM_DB_ACCESS_TYPE, UnsafePointer<cssm_access_credentials>!, UnsafePointer<Void>!, UnsafeMutablePointer<CSSM_DB_HANDLE>!) -> CSSM_RETURN)!, DbClose DbClose: (@convention(c) (MDS_DB_HANDLE) -> CSSM_RETURN)!, GetDbNames GetDbNames: (@convention(c) (MDS_HANDLE, UnsafeMutablePointer<UnsafeMutablePointer<cssm_name_list>?>!) -> CSSM_RETURN)!, GetDbNameFromHandle GetDbNameFromHandle: (@convention(c) (MDS_DB_HANDLE, UnsafeMutablePointer<UnsafeMutablePointer<Int8>?>!) -> CSSM_RETURN)!, FreeNameList FreeNameList: (@convention(c) (MDS_HANDLE, UnsafeMutablePointer<cssm_name_list>!) -> CSSM_RETURN)!, DataInsert DataInsert: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafePointer<cssm_db_record_attribute_data>!, UnsafePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!, DataDelete DataDelete: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_db_unique_record>!) -> CSSM_RETURN)!, DataModify DataModify: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafeMutablePointer<cssm_db_unique_record>!, UnsafePointer<cssm_db_record_attribute_data>!, UnsafePointer<cssm_data>!, CSSM_DB_MODIFY_MODE) -> CSSM_RETURN)!, DataGetFirst DataGetFirst: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_query>!, CSSM_HANDLE_PTR!, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!, DataGetNext DataGetNext: (@convention(c) (MDS_DB_HANDLE, CSSM_HANDLE, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!, UnsafeMutablePointer<UnsafeMutablePointer<cssm_db_unique_record>?>!) -> CSSM_RETURN)!, DataAbortQuery DataAbortQuery: (@convention(c) (MDS_DB_HANDLE, CSSM_HANDLE) -> CSSM_RETURN)!, DataGetFromUniqueRecordId DataGetFromUniqueRecordId: (@convention(c) (MDS_DB_HANDLE, UnsafePointer<cssm_db_unique_record>!, UnsafeMutablePointer<cssm_db_record_attribute_data>!, UnsafeMutablePointer<cssm_data>!) -> CSSM_RETURN)!, FreeUniqueRecord FreeUniqueRecord: (@convention(c) (MDS_DB_HANDLE, UnsafeMutablePointer<cssm_db_unique_record>!) -> CSSM_RETURN)!, CreateRelation CreateRelation: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE, UnsafePointer<Int8>!, uint32, UnsafePointer<cssm_db_schema_attribute_info>!, uint32, UnsafePointer<cssm_db_schema_index_info>!) -> CSSM_RETURN)!, DestroyRelation DestroyRelation: (@convention(c) (MDS_DB_HANDLE, CSSM_DB_RECORDTYPE) -> CSSM_RETURN)!)
}
