
@available(OSX 10.7, *)
let kSecOIDADC_CERT_POLICY: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_CERT_POLICY: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_CODE_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_CODE_SIGNING_DEV: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_ICHAT_ENCRYPTION: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_ICHAT_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_RESOURCE_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EKU_SYSTEM_IDENTITY: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_ADC_APPLE_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_ADC_DEV_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_APPLE_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_CODE_SIGNING: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_INTERMEDIATE_MARKER: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_WWDR_INTERMEDIATE: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_ITMS_INTERMEDIATE: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_AAI_INTERMEDIATE: CFString
@available(OSX 10.7, *)
let kSecOIDAPPLE_EXTENSION_APPLEID_INTERMEDIATE: CFString
@available(OSX 10.7, *)
let kSecOIDAuthorityInfoAccess: CFString
@available(OSX 10.7, *)
let kSecOIDAuthorityKeyIdentifier: CFString
@available(OSX 10.7, *)
let kSecOIDBasicConstraints: CFString
@available(OSX 10.7, *)
let kSecOIDBiometricInfo: CFString
@available(OSX 10.7, *)
let kSecOIDCSSMKeyStruct: CFString
@available(OSX 10.7, *)
let kSecOIDCertIssuer: CFString
@available(OSX 10.7, *)
let kSecOIDCertificatePolicies: CFString
@available(OSX 10.7, *)
let kSecOIDClientAuth: CFString
@available(OSX 10.7, *)
let kSecOIDCollectiveStateProvinceName: CFString
@available(OSX 10.7, *)
let kSecOIDCollectiveStreetAddress: CFString
@available(OSX 10.7, *)
let kSecOIDCommonName: CFString
@available(OSX 10.7, *)
let kSecOIDCountryName: CFString
@available(OSX 10.7, *)
let kSecOIDCrlDistributionPoints: CFString
@available(OSX 10.7, *)
let kSecOIDCrlNumber: CFString
@available(OSX 10.7, *)
let kSecOIDCrlReason: CFString
@available(OSX 10.7, *)
let kSecOIDDOTMAC_CERT_EMAIL_ENCRYPT: CFString
@available(OSX 10.7, *)
let kSecOIDDOTMAC_CERT_EMAIL_SIGN: CFString
@available(OSX 10.7, *)
let kSecOIDDOTMAC_CERT_EXTENSION: CFString
@available(OSX 10.7, *)
let kSecOIDDOTMAC_CERT_IDENTITY: CFString
@available(OSX 10.7, *)
let kSecOIDDOTMAC_CERT_POLICY: CFString
@available(OSX 10.7, *)
let kSecOIDDeltaCrlIndicator: CFString
@available(OSX 10.7, *)
let kSecOIDDescription: CFString
@available(OSX 10.7, *)
let kSecOIDEKU_IPSec: CFString
@available(OSX 10.7, *)
let kSecOIDEmailAddress: CFString
@available(OSX 10.7, *)
let kSecOIDEmailProtection: CFString
@available(OSX 10.7, *)
let kSecOIDExtendedKeyUsage: CFString
@available(OSX 10.7, *)
let kSecOIDExtendedKeyUsageAny: CFString
@available(OSX 10.7, *)
let kSecOIDExtendedUseCodeSigning: CFString
@available(OSX 10.7, *)
let kSecOIDGivenName: CFString
@available(OSX 10.7, *)
let kSecOIDHoldInstructionCode: CFString
@available(OSX 10.7, *)
let kSecOIDInvalidityDate: CFString
@available(OSX 10.7, *)
let kSecOIDIssuerAltName: CFString
@available(OSX 10.7, *)
let kSecOIDIssuingDistributionPoint: CFString
@available(OSX 10.7, *)
let kSecOIDIssuingDistributionPoints: CFString
@available(OSX 10.7, *)
let kSecOIDKERBv5_PKINIT_KP_CLIENT_AUTH: CFString
@available(OSX 10.7, *)
let kSecOIDKERBv5_PKINIT_KP_KDC: CFString
@available(OSX 10.7, *)
let kSecOIDKeyUsage: CFString
@available(OSX 10.7, *)
let kSecOIDLocalityName: CFString
@available(OSX 10.7, *)
let kSecOIDMS_NTPrincipalName: CFString
@available(OSX 10.7, *)
let kSecOIDMicrosoftSGC: CFString
@available(OSX 10.7, *)
let kSecOIDNameConstraints: CFString
@available(OSX 10.7, *)
let kSecOIDNetscapeCertSequence: CFString
@available(OSX 10.7, *)
let kSecOIDNetscapeCertType: CFString
@available(OSX 10.7, *)
let kSecOIDNetscapeSGC: CFString
@available(OSX 10.7, *)
let kSecOIDOCSPSigning: CFString
@available(OSX 10.7, *)
let kSecOIDOrganizationName: CFString
@available(OSX 10.7, *)
let kSecOIDOrganizationalUnitName: CFString
@available(OSX 10.7, *)
let kSecOIDPolicyConstraints: CFString
@available(OSX 10.7, *)
let kSecOIDPolicyMappings: CFString
@available(OSX 10.7, *)
let kSecOIDPrivateKeyUsagePeriod: CFString
@available(OSX 10.7, *)
let kSecOIDQC_Statements: CFString
@available(OSX 10.7, *)
let kSecOIDSerialNumber: CFString
@available(OSX 10.7, *)
let kSecOIDServerAuth: CFString
@available(OSX 10.7, *)
let kSecOIDStateProvinceName: CFString
@available(OSX 10.7, *)
let kSecOIDStreetAddress: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectAltName: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectDirectoryAttributes: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectEmailAddress: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectInfoAccess: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectKeyIdentifier: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectPicture: CFString
@available(OSX 10.7, *)
let kSecOIDSubjectSignatureBitmap: CFString
@available(OSX 10.7, *)
let kSecOIDSurname: CFString
@available(OSX 10.7, *)
let kSecOIDTimeStamping: CFString
@available(OSX 10.7, *)
let kSecOIDTitle: CFString
@available(OSX 10.7, *)
let kSecOIDUseExemptions: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1CertificateIssuerUniqueId: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1CertificateSubjectUniqueId: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1IssuerName: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1IssuerNameCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1IssuerNameLDAP: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1IssuerNameStd: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SerialNumber: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1Signature: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SignatureAlgorithm: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SignatureAlgorithmParameters: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SignatureAlgorithmTBS: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SignatureCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SignatureStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectName: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectNameCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectNameLDAP: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectNameStd: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectPublicKey: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectPublicKeyAlgorithm: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectPublicKeyAlgorithmParameters: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1SubjectPublicKeyCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1ValidityNotAfter: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1ValidityNotBefore: CFString
@available(OSX 10.7, *)
let kSecOIDX509V1Version: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3Certificate: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionCritical: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionId: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionType: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionValue: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionsCStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateExtensionsStruct: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3CertificateNumberOfExtensions: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3SignedCertificate: CFString
@available(OSX 10.7, *)
let kSecOIDX509V3SignedCertificateCStruct: CFString
@available(OSX 10.8, *)
let kSecOIDSRVName: CFString
