#ifndef TAPI_CORE_ARCHITECTURE_CONFIG_H
#define TAPI_CORE_ARCHITECTURE_CONFIG_H

#define SUPPORT_ARCH_I386 1
#define SUPPORT_ARCH_X86_64 1
#define SUPPORT_ARCH_X86_64H 1
#define SUPPORT_ARCH_ARMV4T 1
#define SUPPORT_ARCH_ARMV6 1
#define SUPPORT_ARCH_ARMV5 1
#define SUPPORT_ARCH_ARMV7 1
#define SUPPORT_ARCH_ARMV7S 1
#define SUPPORT_ARCH_ARMV7K 1
#define SUPPORT_ARCH_ARMV6M 1
#define SUPPORT_ARCH_ARMV7M 1
#define SUPPORT_ARCH_ARMV7EM 1
#define SUPPORT_ARCH_ARM64 1

#endif // TAPI_CORE_ARCHITECTURE_CONFIG_H
