#!/usr/bin/env python
# utils/build-script - The ultimate tool for building Swift -----*- python -*-
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2016 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
#
# ----------------------------------------------------------------------------

import os
import sys


PYTHONPATH = os.path.join(os.path.dirname(__file__), 'build-script-impl')
if "PYTHONPATH" in os.environ:
    PYTHONPATH += os.pathsep + os.environ["PYTHONPATH"]

env = dict(os.environ)
env.update(PYTHONPATH=PYTHONPATH)

os.execve(sys.executable,
          [sys.executable, '-m', 'build_script'] + sys.argv,
          env)
