
@available(watchOS 2.0, *)
let kSecClass: CFString
@available(watchOS 2.0, *)
let kSecClassGenericPassword: CFString
@available(watchOS 2.0, *)
let kSecClassInternetPassword: CFString
@available(watchOS 2.0, *)
let kSecClassCertificate: CFString
@available(watchOS 2.0, *)
let kSecClassKey: CFString
@available(watchOS 2.0, *)
let kSecClassIdentity: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessible: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessControl: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessGroup: CFString
@available(watchOS 2.0, *)
let kSecAttrSynchronizable: CFString
@available(watchOS 2.0, *)
let kSecAttrCreationDate: CFString
@available(watchOS 2.0, *)
let kSecAttrModificationDate: CFString
@available(watchOS 2.0, *)
let kSecAttrDescription: CFString
@available(watchOS 2.0, *)
let kSecAttrComment: CFString
@available(watchOS 2.0, *)
let kSecAttrCreator: CFString
@available(watchOS 2.0, *)
let kSecAttrType: CFString
@available(watchOS 2.0, *)
let kSecAttrLabel: CFString
@available(watchOS 2.0, *)
let kSecAttrIsInvisible: CFString
@available(watchOS 2.0, *)
let kSecAttrIsNegative: CFString
@available(watchOS 2.0, *)
let kSecAttrAccount: CFString
@available(watchOS 2.0, *)
let kSecAttrService: CFString
@available(watchOS 2.0, *)
let kSecAttrGeneric: CFString
@available(watchOS 2.0, *)
let kSecAttrSecurityDomain: CFString
@available(watchOS 2.0, *)
let kSecAttrServer: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocol: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationType: CFString
@available(watchOS 2.0, *)
let kSecAttrPort: CFString
@available(watchOS 2.0, *)
let kSecAttrPath: CFString
@available(watchOS 2.0, *)
let kSecAttrSubject: CFString
@available(watchOS 2.0, *)
let kSecAttrIssuer: CFString
@available(watchOS 2.0, *)
let kSecAttrSerialNumber: CFString
@available(watchOS 2.0, *)
let kSecAttrSubjectKeyID: CFString
@available(watchOS 2.0, *)
let kSecAttrPublicKeyHash: CFString
@available(watchOS 2.0, *)
let kSecAttrCertificateType: CFString
@available(watchOS 2.0, *)
let kSecAttrCertificateEncoding: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyClass: CFString
@available(watchOS 2.0, *)
let kSecAttrApplicationLabel: CFString
@available(watchOS 2.0, *)
let kSecAttrIsPermanent: CFString
@available(watchOS 2.0, *)
let kSecAttrApplicationTag: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyType: CFString
@available(watchOS 2.0, *)
let kSecAttrKeySizeInBits: CFString
@available(watchOS 2.0, *)
let kSecAttrEffectiveKeySize: CFString
@available(watchOS 2.0, *)
let kSecAttrCanEncrypt: CFString
@available(watchOS 2.0, *)
let kSecAttrCanDecrypt: CFString
@available(watchOS 2.0, *)
let kSecAttrCanDerive: CFString
@available(watchOS 2.0, *)
let kSecAttrCanSign: CFString
@available(watchOS 2.0, *)
let kSecAttrCanVerify: CFString
@available(watchOS 2.0, *)
let kSecAttrCanWrap: CFString
@available(watchOS 2.0, *)
let kSecAttrCanUnwrap: CFString
@available(watchOS 2.0, *)
let kSecAttrSyncViewHint: CFString
@available(watchOS 2.0, *)
let kSecAttrTokenID: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleWhenUnlocked: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleAfterFirstUnlock: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleAlways: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleWhenUnlockedThisDeviceOnly: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly: CFString
@available(watchOS 2.0, *)
let kSecAttrAccessibleAlwaysThisDeviceOnly: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolFTP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolFTPAccount: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolHTTP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolIRC: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolNNTP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolPOP3: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolSMTP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolSOCKS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolIMAP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolLDAP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolAppleTalk: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolAFP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolTelnet: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolSSH: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolFTPS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolHTTPS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolHTTPProxy: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolHTTPSProxy: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolFTPProxy: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolSMB: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolRTSP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolRTSPProxy: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolDAAP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolEPPC: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolIPP: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolNNTPS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolLDAPS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolTelnetS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolIMAPS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolIRCS: CFString
@available(watchOS 2.0, *)
let kSecAttrProtocolPOP3S: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeNTLM: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeMSN: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeDPA: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeRPA: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeHTTPBasic: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeHTTPDigest: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeHTMLForm: CFString
@available(watchOS 2.0, *)
let kSecAttrAuthenticationTypeDefault: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyClassPublic: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyClassPrivate: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyClassSymmetric: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyTypeRSA: CFString
@available(watchOS 2.0, *)
let kSecAttrKeyTypeEC: CFString
@available(watchOS 2.0, *)
let kSecAttrSynchronizableAny: CFString
@available(watchOS 2.0, *)
let kSecMatchPolicy: CFString
@available(watchOS 2.0, *)
let kSecMatchItemList: CFString
@available(watchOS 2.0, *)
let kSecMatchSearchList: CFString
@available(watchOS 2.0, *)
let kSecMatchIssuers: CFString
@available(watchOS 2.0, *)
let kSecMatchEmailAddressIfPresent: CFString
@available(watchOS 2.0, *)
let kSecMatchSubjectContains: CFString
@available(watchOS 2.0, *)
let kSecMatchCaseInsensitive: CFString
@available(watchOS 2.0, *)
let kSecMatchTrustedOnly: CFString
@available(watchOS 2.0, *)
let kSecMatchValidOnDate: CFString
@available(watchOS 2.0, *)
let kSecMatchLimit: CFString
@available(watchOS 2.0, *)
let kSecMatchLimitOne: CFString
@available(watchOS 2.0, *)
let kSecMatchLimitAll: CFString
@available(watchOS 2.0, *)
let kSecReturnData: CFString
@available(watchOS 2.0, *)
let kSecReturnAttributes: CFString
@available(watchOS 2.0, *)
let kSecReturnRef: CFString
@available(watchOS 2.0, *)
let kSecReturnPersistentRef: CFString
@available(watchOS 2.0, *)
let kSecValueData: CFString
@available(watchOS 2.0, *)
let kSecValueRef: CFString
@available(watchOS 2.0, *)
let kSecValuePersistentRef: CFString
@available(watchOS 2.0, *)
let kSecUseItemList: CFString
@available(watchOS 2.0, *)
let kSecUseOperationPrompt: CFString
@available(watchOS, introduced: 2.0, deprecated: 2.0, message: "Use a kSecAuthenticationUI instead.")
let kSecUseNoAuthenticationUI: CFString
@available(watchOS 2.0, *)
let kSecUseAuthenticationUI: CFString
@available(watchOS 2.0, *)
let kSecUseAuthenticationContext: CFString
@available(watchOS 2.0, *)
let kSecUseAuthenticationUIAllow: CFString
@available(watchOS 2.0, *)
let kSecUseAuthenticationUIFail: CFString
@available(watchOS 2.0, *)
let kSecUseAuthenticationUISkip: CFString
@available(watchOS 2.0, *)
let kSecAttrTokenIDSecureEnclave: CFString
@available(watchOS 2.0, *)
@discardableResult
func SecItemCopyMatching(_ query: CFDictionary, _ result: UnsafeMutablePointer<CFTypeRef?>?) -> OSStatus
@available(watchOS 2.0, *)
@discardableResult
func SecItemAdd(_ attributes: CFDictionary, _ result: UnsafeMutablePointer<CFTypeRef?>?) -> OSStatus
@available(watchOS 2.0, *)
@discardableResult
func SecItemUpdate(_ query: CFDictionary, _ attributesToUpdate: CFDictionary) -> OSStatus
@available(watchOS 2.0, *)
@discardableResult
func SecItemDelete(_ query: CFDictionary) -> OSStatus
