
@available(tvOS 4.0, *)
let kCVImageBufferCGColorSpaceKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferCleanApertureKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferCleanApertureWidthKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferCleanApertureHeightKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferCleanApertureHorizontalOffsetKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferCleanApertureVerticalOffsetKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferPreferredCleanApertureKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldCountKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldDetailKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldDetailTemporalTopFirst: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldDetailTemporalBottomFirst: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldDetailSpatialFirstLineEarly: CFString
@available(tvOS 4.0, *)
let kCVImageBufferFieldDetailSpatialFirstLineLate: CFString
@available(tvOS 4.0, *)
let kCVImageBufferPixelAspectRatioKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferPixelAspectRatioHorizontalSpacingKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferPixelAspectRatioVerticalSpacingKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferDisplayDimensionsKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferDisplayWidthKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferDisplayHeightKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferGammaLevelKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferICCProfileKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferYCbCrMatrixKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferYCbCrMatrix_ITU_R_709_2: CFString
@available(tvOS 4.0, *)
let kCVImageBufferYCbCrMatrix_ITU_R_601_4: CFString
@available(tvOS 4.0, *)
let kCVImageBufferYCbCrMatrix_SMPTE_240M_1995: CFString
@available(tvOS 9.0, *)
let kCVImageBufferYCbCrMatrix_DCI_P3: CFString
@available(tvOS 9.0, *)
let kCVImageBufferYCbCrMatrix_P3_D65: CFString
@available(tvOS 9.0, *)
let kCVImageBufferYCbCrMatrix_ITU_R_2020: CFString
@available(tvOS 4.0, *)
let kCVImageBufferColorPrimariesKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferColorPrimaries_ITU_R_709_2: CFString
@available(tvOS 4.0, *)
let kCVImageBufferColorPrimaries_EBU_3213: CFString
@available(tvOS 4.0, *)
let kCVImageBufferColorPrimaries_SMPTE_C: CFString
@available(tvOS 6.0, *)
let kCVImageBufferColorPrimaries_P22: CFString
@available(tvOS 9.0, *)
let kCVImageBufferColorPrimaries_DCI_P3: CFString
@available(tvOS 9.0, *)
let kCVImageBufferColorPrimaries_P3_D65: CFString
@available(tvOS 9.0, *)
let kCVImageBufferColorPrimaries_ITU_R_2020: CFString
@available(tvOS 4.0, *)
let kCVImageBufferTransferFunctionKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferTransferFunction_ITU_R_709_2: CFString
@available(tvOS 4.0, *)
let kCVImageBufferTransferFunction_SMPTE_240M_1995: CFString
@available(tvOS 4.0, *)
let kCVImageBufferTransferFunction_UseGamma: CFString
@available(tvOS 9.0, *)
let kCVImageBufferTransferFunction_ITU_R_2020: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocationTopFieldKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocationBottomFieldKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_Left: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_Center: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_TopLeft: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_Top: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_BottomLeft: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_Bottom: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaLocation_DV420: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaSubsamplingKey: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaSubsampling_420: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaSubsampling_422: CFString
@available(tvOS 4.0, *)
let kCVImageBufferChromaSubsampling_411: CFString
@available(tvOS 8.0, *)
let kCVImageBufferAlphaChannelIsOpaque: CFString
typealias CVImageBuffer = CVBuffer
@available(tvOS 4.0, *)
@discardableResult
func CVImageBufferGetEncodedSize(_ imageBuffer: CVImageBuffer) -> CGSize
@available(tvOS 4.0, *)
@discardableResult
func CVImageBufferGetDisplaySize(_ imageBuffer: CVImageBuffer) -> CGSize
@available(tvOS 4.0, *)
@discardableResult
func CVImageBufferGetCleanRect(_ imageBuffer: CVImageBuffer) -> CGRect
@available(tvOS 4.0, *)
@discardableResult
func CVImageBufferIsFlipped(_ imageBuffer: CVImageBuffer) -> Bool
