
@available(OSX 10.2, *)
let kDRStatusStateKey: CFString!
@available(OSX 10.2, *)
let kDRStatusPercentCompleteKey: CFString!
@available(OSX 10.2, *)
let kDRStatusCurrentSpeedKey: CFString!
@available(OSX 10.2, *)
let kDRStatusCurrentSessionKey: CFString!
@available(OSX 10.2, *)
let kDRStatusCurrentTrackKey: CFString!
@available(OSX 10.2, *)
let kDRStatusTotalSessionsKey: CFString!
@available(OSX 10.2, *)
let kDRStatusTotalTracksKey: CFString!
@available(OSX 10.2, *)
let kDRStatusEraseTypeKey: CFString!
@available(OSX 10.2, *)
let kDRStatusStateNone: CFString!
@available(OSX 10.2, *)
let kDRStatusStatePreparing: CFString!
@available(OSX 10.2, *)
let kDRStatusStateVerifying: CFString!
@available(OSX 10.2, *)
let kDRStatusStateDone: CFString!
@available(OSX 10.2, *)
let kDRStatusStateFailed: CFString!
@available(OSX 10.2, *)
let kDRStatusStateSessionOpen: CFString!
@available(OSX 10.2, *)
let kDRStatusStateTrackOpen: CFString!
@available(OSX 10.2, *)
let kDRStatusStateTrackWrite: CFString!
@available(OSX 10.2, *)
let kDRStatusStateTrackClose: CFString!
@available(OSX 10.2, *)
let kDRStatusStateSessionClose: CFString!
@available(OSX 10.2, *)
let kDRStatusStateFinishing: CFString!
@available(OSX 10.2, *)
let kDRStatusStateErasing: CFString!
@available(OSX 10.4, *)
let kDRStatusProgressInfoKey: CFString!
@available(OSX 10.4, *)
let kDRStatusProgressCurrentKPS: CFString!
@available(OSX 10.4, *)
let kDRStatusProgressCurrentXFactor: CFString!
