
@available(OSX 10.2, *)
let DRStatusStateKey: String
@available(OSX 10.2, *)
let DRStatusPercentCompleteKey: String
@available(OSX 10.2, *)
let DRStatusCurrentSessionKey: String
@available(OSX 10.2, *)
let DRStatusCurrentTrackKey: String
@available(OSX 10.2, *)
let DRStatusTotalSessionsKey: String
@available(OSX 10.2, *)
let DRStatusTotalTracksKey: String
@available(OSX 10.2, *)
let DRStatusCurrentSpeedKey: String
@available(OSX 10.2, *)
let DRStatusEraseTypeKey: String
@available(OSX 10.2, *)
let DRStatusStateNone: String
@available(OSX 10.2, *)
let DRStatusStatePreparing: String
@available(OSX 10.2, *)
let DRStatusStateVerifying: String
@available(OSX 10.2, *)
let DRStatusStateDone: String
@available(OSX 10.2, *)
let DRStatusStateFailed: String
@available(OSX 10.2, *)
let DRStatusStateSessionOpen: String
@available(OSX 10.2, *)
let DRStatusStateTrackOpen: String
@available(OSX 10.2, *)
let DRStatusStateTrackWrite: String
@available(OSX 10.2, *)
let DRStatusStateTrackClose: String
@available(OSX 10.2, *)
let DRStatusStateSessionClose: String
@available(OSX 10.2, *)
let DRStatusStateFinishing: String
@available(OSX 10.2, *)
let DRStatusStateErasing: String
@available(OSX 10.4, *)
let DRStatusProgressInfoKey: String
@available(OSX 10.4, *)
let DRStatusProgressCurrentKPS: String
@available(OSX 10.4, *)
let DRStatusProgressCurrentXFactor: String
@available(OSX 10.2, *)
let DRErrorStatusKey: String
@available(OSX 10.2, *)
let DRErrorStatusErrorKey: String
@available(OSX 10.2, *)
let DRErrorStatusErrorStringKey: String
@available(OSX 10.4, *)
let DRErrorStatusErrorInfoStringKey: String
@available(OSX 10.2, *)
let DRErrorStatusSenseKey: String
@available(OSX 10.2, *)
let DRErrorStatusSenseCodeStringKey: String
@available(OSX 10.2, *)
let DRErrorStatusAdditionalSenseStringKey: String
